/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Linking, Pressable, Share, StyleSheet, Text, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { Badge, Card, Empty, ErrorBox, Header, Loading, Screen } from '@/components/ui';
import { supabase } from '@/lib/supabase';
import { colors } from '@/lib/theme';
type Row=Record<string,any>;

export default function WorkerDetail(){const{id}=useLocalSearchParams<{id:string}>();const{profile}=useAuth();const[worker,setWorker]=useState<Row|null>(null);const[documents,setDocuments]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=async()=>{setLoading(true);const[w,d]=await Promise.all([supabase.from('maestro_personal').select('*').eq('id',Number(id)).eq('empresa',profile!.empresa).maybeSingle(),supabase.from('rrhh_documentos_trabajadores').select('*').eq('trabajador_id',Number(id)).eq('empresa',profile!.empresa).order('created_at',{ascending:false})]);if(w.error||d.error)setError((w.error||d.error)?.message||'No fue posible cargar la ficha.');else{setWorker(w.data);setDocuments(d.data||[])}setLoading(false)};useEffect(()=>{load()},[id,profile]);const signedUrl=async(document:Row)=>{const{data,error:urlError}=await supabase.storage.from('rrhh-documentos').createSignedUrl(document.archivo_path,3600);if(urlError||!data?.signedUrl){Alert.alert('No fue posible abrir',urlError?.message||'Documento no disponible.');return null}return data.signedUrl};const open=async(document:Row)=>{const url=await signedUrl(document);if(url)Linking.openURL(url)};const share=async(document:Row)=>{const url=await signedUrl(document);if(url)Share.share({title:document.archivo_nombre,message:`Documento de ${worker?.nombre||'trabajador'} (enlace válido por 1 hora): ${url}`,url})};if(loading)return <Screen><Loading/></Screen>;return <Screen refreshing={loading} onRefresh={load}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={20}/><Text style={s.backText}>Volver a personal</Text></Pressable><Header title={worker?.nombre||'Trabajador'} subtitle={`${worker?.rut||'Sin RUT'} · ${worker?.cargo||'Sin cargo'}`} icon="person-outline"/><ErrorBox text={error}/><Card><Text style={s.label}>Asignación vigente</Text><Text style={s.value}>{worker?.obra_nombre||'Sin asignación'}</Text><Text style={s.meta}>{worker?.tipo_contrato||'Contrato no informado'}</Text></Card><Text style={s.section}>Documentación</Text>{documents.length?documents.map(document=><Card key={document.id}><View style={s.row}><View style={s.flex}><Text style={s.value}>{document.tipo_documento||document.archivo_nombre}</Text><Text style={s.meta}>{document.archivo_nombre}</Text><Text style={s.meta}>Vence: {document.fecha_vencimiento||'Sin vencimiento'}</Text></View><Badge tone={String(document.estado_vigencia).includes('Vencido')?'red':String(document.estado_vigencia).includes('vencer')?'amber':'green'}>{document.estado_vigencia||'Registrado'}</Badge></View><View style={s.actions}><Action icon="eye-outline" label="Ver" onPress={()=>open(document)}/><Action icon="share-social-outline" label="Compartir" onPress={()=>share(document)}/></View></Card>):<Empty text="Este trabajador no tiene documentos cargados."/>}</Screen>}
function Action({icon,label,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;onPress:()=>void}){return <Pressable style={s.action} onPress={onPress}><Ionicons name={icon} size={17} color={colors.blue}/><Text style={s.actionText}>{label}</Text></Pressable>}
const s=StyleSheet.create({back:{flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800',color:colors.ink},label:{fontSize:10,fontWeight:'900',textTransform:'uppercase',color:colors.muted},value:{fontSize:14,fontWeight:'900',color:colors.ink},meta:{fontSize:11,color:colors.muted},section:{fontSize:12,fontWeight:'900',textTransform:'uppercase',color:colors.ink},row:{flexDirection:'row',alignItems:'center',gap:9},flex:{flex:1},actions:{flexDirection:'row',gap:8},action:{height:42,borderRadius:11,backgroundColor:colors.soft,flex:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},actionText:{fontSize:11,fontWeight:'900',color:colors.blue}});
