import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { colors, shadow } from '@/lib/theme';
export default function Login(){const{signIn}=useAuth();const[u,setU]=useState('');const[e,setE]=useState('');const[p,setP]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const submit=async()=>{setBusy(true);setError('');try{await signIn(u,e,p);router.replace('/inicio')}catch(x){setError(x instanceof Error?x.message:'No fue posible ingresar.')}finally{setBusy(false)}};return <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.root}><View style={s.brand}><View style={s.mark}><Text style={s.ox}>OX</Text></View><Text style={s.name}>OBRAXIS</Text><Text style={s.tag}>OBRA EN TERRENO</Text></View><View style={s.card}><Text style={s.title}>Ingresar</Text><Text style={s.sub}>Accede con las mismas credenciales de la plataforma.</Text>{error?<Text style={s.error}>{error}</Text>:null}<Field icon="person-outline" placeholder="Usuario" value={u} onChangeText={setU}/><Field icon="business-outline" placeholder="Empresa" value={e} onChangeText={setE}/><Field icon="lock-closed-outline" placeholder="Contraseña" value={p} onChangeText={setP} secureTextEntry/><Pressable disabled={busy||!u||!e||!p} onPress={submit} style={[s.button,(busy||!u||!e||!p)&&{opacity:.5}]}>{busy?<ActivityIndicator color="white"/>:<><Text style={s.buttonText}>Ingresar</Text><Ionicons name="arrow-forward" size={18} color="white"/></>}</Pressable></View></KeyboardAvoidingView>}
function Field(props:any){return <View style={s.field}><Ionicons name={props.icon} size={20} color={colors.muted}/><TextInput {...props} autoCapitalize="none" placeholderTextColor="#98A2B3" style={s.input}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.navy,justifyContent:'center',padding:22},brand:{alignItems:'center',marginBottom:28},mark:{width:82,height:82,borderRadius:26,backgroundColor:colors.white,alignItems:'center',justifyContent:'center',transform:[{rotate:'-3deg'}]},ox:{fontSize:31,fontWeight:'900',color:colors.orange},name:{fontSize:26,fontWeight:'900',letterSpacing:6,color:'white',marginTop:14},tag:{fontSize:10,fontWeight:'800',letterSpacing:3,color:'#AEB9D0',marginTop:6},card:{backgroundColor:'white',borderRadius:26,padding:22,gap:14,...shadow},title:{fontSize:26,fontWeight:'900',color:colors.ink},sub:{fontSize:13,color:colors.muted,marginBottom:4},error:{fontSize:12,color:colors.red,backgroundColor:'#FFF1F2',padding:10,borderRadius:10},field:{height:55,borderWidth:1,borderColor:colors.line,borderRadius:14,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:10},input:{flex:1,fontSize:15,color:colors.ink},button:{height:56,borderRadius:15,backgroundColor:colors.orange,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:4},buttonText:{color:'white',fontWeight:'900',fontSize:15}});
