import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { Card, ErrorBox, Header, Loading, Screen } from '@/components/ui';
import { supabase } from '@/lib/supabase';
import { colors } from '@/lib/theme';
type Row=Record<string,any>;
const fieldsOf=(value:any)=>Array.isArray(value)?value:Array.isArray(value?.items)?value.items:[];
export default function RecordDetail(){const{id}=useLocalSearchParams<{id:string}>();const{profile}=useAuth();const[data,setData]=useState<Row|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{void(async()=>{const{data:row,error:loadError}=await supabase.from('prevencion_respuestas').select('*,prevencion_formularios!inner(*)').eq('id',Number(id)).eq('prevencion_formularios.empresa',profile!.empresa).maybeSingle();if(loadError)setError(loadError.message);else setData(row);setLoading(false)})()},[id,profile]);if(loading)return <Screen><Loading/></Screen>;const form=data?.prevencion_formularios||{};return <Screen><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={20}/><Text style={s.backText}>Volver a registros</Text></Pressable><Header title={form.titulo||'Registro'} subtitle={`${data?.inspector||'Sin informante'} · ${data?.proyecto_nombre||'Nivel empresa'}`} icon="document-text-outline"/><ErrorBox text={error}/>{fieldsOf(form.campos).map((field:Row)=><Card key={field.id}><Text style={s.label}>{field.label}</Text><Answer field={field} value={data?.respuestas?.[field.id]||(field.type==='signature'?data?.firma_url:null)}/></Card>)}</Screen>}
function Answer({field,value}:{field:Row;value:any}){if((field.type==='photo'||field.type==='signature')&&typeof value==='string')return <Image source={{uri:value}} style={field.type==='photo'?s.photo:s.signature}/>;if(field.type==='repeater'&&Array.isArray(value))return <View>{value.map((row:Row,index:number)=><View key={index} style={s.group}>{Object.entries(row).map(([key,item])=>{const sub=field.subFields?.find((candidate:Row)=>candidate.id===key)||{label:key};return <View key={key}><Text style={s.subLabel}>{sub.label}</Text>{(sub.type==='signature'||sub.type==='photo')&&typeof item==='string'?<Image source={{uri:item}} style={sub.type==='photo'?s.photo:s.signature}/>:<Text style={s.value}>{Array.isArray(item)?item.join(', '):String(item||'Sin respuesta')}</Text>}</View>})}</View>)}</View>;return <Text style={s.value}>{Array.isArray(value)?value.join(', '):String(value??'Sin respuesta')}</Text>}
const s=StyleSheet.create({back:{flexDirection:'row',gap:7,alignItems:'center'},backText:{fontSize:12,fontWeight:'800',color:colors.ink},label:{fontSize:10,fontWeight:'900',textTransform:'uppercase',color:colors.muted},subLabel:{fontSize:10,fontWeight:'800',color:colors.muted,marginTop:7},value:{fontSize:14,color:colors.ink,lineHeight:20},photo:{width:'100%',height:220,borderRadius:12,resizeMode:'contain'},signature:{width:'100%',height:120,resizeMode:'contain'},group:{borderBottomWidth:1,borderBottomColor:colors.line,paddingVertical:8}});
