-- =====================================================================
-- MASTER SCHEMA OBRAXIS (PORTAL PROYECTOS)
-- Incluye la estructura de todas las tablas y políticas de seguridad RLS
-- =====================================================================

-- 1. CONFIGURACIÓN Y EMPRESA
CREATE TABLE IF NOT EXISTS config_empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa TEXT NOT NULL,
    logo_base64 TEXT,
    modulos_activos TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS config_correos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa TEXT NOT NULL,
    modulo TEXT NOT NULL,
    emails TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    rol TEXT NOT NULL DEFAULT 'Inspector',
    empresa TEXT NOT NULL,
    modulos TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    permisos TEXT,
    empresa TEXT NOT NULL
);

-- 2. OBRAS Y PERSONAL
CREATE TABLE IF NOT EXISTS obras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    ubicacion TEXT,
    empresa TEXT NOT NULL,
    estado TEXT DEFAULT 'Activa',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS maestro_personal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    rut TEXT NOT NULL,
    cargo TEXT,
    obra_nombre TEXT,
    fecha_asig TEXT,
    empresa TEXT NOT NULL,
    estado TEXT DEFAULT 'Activo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS inventario_maquinaria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patente TEXT NOT NULL,
    tipo TEXT NOT NULL,
    marca TEXT,
    obra_nombre TEXT,
    empresa TEXT NOT NULL,
    estado TEXT DEFAULT 'Operativo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. ACREDITACIONES
CREATE TABLE IF NOT EXISTS acreditaciones_config_docs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_entidad TEXT NOT NULL,
    nombre_doc TEXT NOT NULL,
    obligatorio BOOLEAN DEFAULT true,
    empresa TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS acreditaciones_proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_nombre TEXT NOT NULL,
    rut_empresa TEXT NOT NULL,
    obra_asociada TEXT,
    correo_contacto TEXT,
    token_acceso TEXT UNIQUE,
    estado TEXT DEFAULT 'Pendiente',
    company_docs JSONB,
    equipo_docs JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS acreditaciones_subcontratos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_nombre TEXT NOT NULL,
    rut_empresa TEXT NOT NULL,
    obra_asociada TEXT,
    correo_contacto TEXT,
    token_acceso TEXT UNIQUE,
    estado TEXT DEFAULT 'Pendiente',
    company_docs JSONB,
    worker_docs JSONB,
    equipo_docs JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS acreditaciones_internas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    rut TEXT NOT NULL,
    obra_asociada TEXT,
    documentos JSONB,
    estado TEXT DEFAULT 'Pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. FORMULARIOS Y PREVENCIÓN
CREATE TABLE IF NOT EXISTS prevencion_formularios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descripcion TEXT,
    modulo_asignado TEXT DEFAULT 'general',
    campos JSONB,
    token_publico TEXT UNIQUE,
    creador_email TEXT,
    empresa TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS prevencion_respuestas_formularios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    formulario_id BIGINT,
    formulario_titulo TEXT,
    usuario_nombre TEXT,
    usuario_rut TEXT,
    respuestas JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS prevencion_capacitaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descripcion TEXT,
    tipo TEXT DEFAULT 'Charla 5 Minutos',
    modulo_asignado TEXT DEFAULT 'general',
    preguntas JSONB,
    token_publico TEXT UNIQUE,
    creador_email TEXT,
    empresa TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. SEGURIDAD RLS Y PERMISOS DE ACCESO HABILITADOS
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', r.tablename);
        EXECUTE format('DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON public.%I;', r.tablename);
        EXECUTE format('CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON public.%I FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);', r.tablename);
    END LOOP;
END $$;

GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
