-- Estados de Pago contractuales por obra. Los ítems son una foto de la valorización al momento de emitir el documento.
CREATE TABLE IF NOT EXISTS estados_pago_obra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT NOT NULL,
  obra_nombre TEXT NOT NULL,
  numero INTEGER NOT NULL,
  fecha_corte DATE NOT NULL,
  monto_bruto NUMERIC NOT NULL DEFAULT 0,
  retencion_pct NUMERIC NOT NULL DEFAULT 0,
  retencion_monto NUMERIC NOT NULL DEFAULT 0,
  anticipo_descontado NUMERIC NOT NULL DEFAULT 0,
  monto_neto NUMERIC NOT NULL DEFAULT 0,
  observaciones TEXT,
  estado TEXT NOT NULL DEFAULT 'Borrador' CHECK (estado IN ('Borrador', 'En revisión', 'Aprobado', 'Enviado', 'Pagado', 'Rechazado')),
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (empresa, obra_nombre, numero)
);

CREATE INDEX IF NOT EXISTS estados_pago_obra_obra_numero_idx ON estados_pago_obra (empresa, obra_nombre, numero DESC);
ALTER TABLE estados_pago_obra ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON estados_pago_obra;
CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON estados_pago_obra FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
GRANT ALL ON estados_pago_obra TO anon, authenticated;
GRANT ALL ON SEQUENCE estados_pago_obra_id_seq TO anon, authenticated;

-- Condiciones económicas que se mantienen por obra y alimentan el cálculo de cada estado de pago.
CREATE TABLE IF NOT EXISTS condiciones_pago_obra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT NOT NULL,
  obra_nombre TEXT NOT NULL,
  anticipo_pct NUMERIC NOT NULL DEFAULT 0 CHECK (anticipo_pct >= 0 AND anticipo_pct <= 100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (empresa, obra_nombre)
);
ALTER TABLE condiciones_pago_obra ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON condiciones_pago_obra;
CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON condiciones_pago_obra FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
GRANT ALL ON condiciones_pago_obra TO anon, authenticated;
GRANT ALL ON SEQUENCE condiciones_pago_obra_id_seq TO anon, authenticated;

ALTER TABLE condiciones_pago_obra ADD COLUMN IF NOT EXISTS revisor_nombre TEXT;
ALTER TABLE condiciones_pago_obra ADD COLUMN IF NOT EXISTS revisor_email TEXT;
ALTER TABLE condiciones_pago_obra ADD COLUMN IF NOT EXISTS aprobador_nombre TEXT;
ALTER TABLE condiciones_pago_obra ADD COLUMN IF NOT EXISTS aprobador_email TEXT;
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS preparado_por TEXT;
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS revisor_nombre TEXT;
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS revisor_email TEXT;
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS aprobador_nombre TEXT;
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS aprobador_email TEXT;
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS token_revision TEXT UNIQUE;
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS token_aprobacion TEXT UNIQUE;
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS observacion_revision TEXT;
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS observacion_aprobacion TEXT;
-- Solo se almacena el hash de la clave temporal enviada al revisor/aprobador.
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS clave_revision_hash TEXT;
ALTER TABLE estados_pago_obra ADD COLUMN IF NOT EXISTS clave_aprobacion_hash TEXT;
ALTER TABLE estados_pago_obra DROP CONSTRAINT IF EXISTS estados_pago_obra_estado_check;
ALTER TABLE estados_pago_obra ADD CONSTRAINT estados_pago_obra_estado_check CHECK (estado IN ('Borrador', 'En revisión', 'Observado', 'En aprobación', 'Aprobado', 'Enviado', 'Pagado', 'Rechazado'));
