-- Historial para validar retrospectivamente las proyecciones de obra.
-- Aplicado en Supabase como migración historial_validacion_predicciones_obra.
create table if not exists public.predicciones_obra_historial (
  id bigint generated by default as identity primary key,
  empresa text not null,
  obra_id integer not null references public.obras(id) on delete restrict,
  obra_nombre text not null,
  fecha_corte date not null,
  fecha_termino_predicha date not null,
  costo_final_predicho numeric not null default 0 check (costo_final_predicho >= 0),
  spi numeric, cpi numeric,
  confianza_datos numeric not null default 0 check (confianza_datos between 0 and 100),
  modo text not null default 'Simulación' check (modo in ('Simulación','Predictivo')),
  fecha_termino_real date,
  costo_final_real numeric check (costo_final_real is null or costo_final_real >= 0),
  error_plazo_dias integer, error_costo_pct numeric,
  estado_validacion text not null default 'Pendiente' check (estado_validacion in ('Pendiente','Validada')),
  creado_por uuid references auth.users(id) on delete set null,
  validado_por uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(), validada_at timestamptz,
  constraint prediccion_obra_empresa_fecha_unique unique (empresa, obra_id, fecha_corte, fecha_termino_predicha, costo_final_predicho)
);
create index if not exists predicciones_historial_empresa_obra_idx on public.predicciones_obra_historial(empresa, obra_id, created_at desc);
alter table public.predicciones_obra_historial enable row level security;
revoke all on table public.predicciones_obra_historial from anon, authenticated;
grant select, insert, update, delete on table public.predicciones_obra_historial to authenticated;
grant usage, select on sequence public.predicciones_obra_historial_id_seq to authenticated;
create policy predicciones_empresa_select on public.predicciones_obra_historial for select to authenticated using (exists (select 1 from public.usuarios u where u.auth_user_id=(select auth.uid()) and (u.empresa=predicciones_obra_historial.empresa or lower(u.empresa)='obraxis')));
create policy predicciones_empresa_insert on public.predicciones_obra_historial for insert to authenticated with check (creado_por=(select auth.uid()) and exists (select 1 from public.usuarios u where u.auth_user_id=(select auth.uid()) and (u.empresa=predicciones_obra_historial.empresa or lower(u.empresa)='obraxis')));
create policy predicciones_empresa_update on public.predicciones_obra_historial for update to authenticated using (exists (select 1 from public.usuarios u where u.auth_user_id=(select auth.uid()) and (u.empresa=predicciones_obra_historial.empresa or lower(u.empresa)='obraxis'))) with check (exists (select 1 from public.usuarios u where u.auth_user_id=(select auth.uid()) and (u.empresa=predicciones_obra_historial.empresa or lower(u.empresa)='obraxis')));
create policy predicciones_empresa_delete on public.predicciones_obra_historial for delete to authenticated using (exists (select 1 from public.usuarios u where u.auth_user_id=(select auth.uid()) and (u.empresa=predicciones_obra_historial.empresa or lower(u.empresa)='obraxis')));
