CREATE TABLE IF NOT EXISTS public.rrhh_proyecciones_dotacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT NOT NULL,
  obra_nombre TEXT NOT NULL,
  cargo TEXT NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_termino DATE NOT NULL,
  cantidad_requerida INTEGER NOT NULL DEFAULT 1 CHECK (cantidad_requerida > 0),
  costo_mensual_unitario NUMERIC NOT NULL DEFAULT 0 CHECK (costo_mensual_unitario >= 0),
  turno TEXT,
  estado TEXT NOT NULL DEFAULT 'Planificada' CHECK (estado IN ('Planificada','Confirmada','En contratación','Cubierta','Cancelada')),
  observaciones TEXT,
  creado_por TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (fecha_termino >= fecha_inicio)
);

CREATE INDEX IF NOT EXISTS rrhh_proyecciones_empresa_obra_periodo_idx
  ON public.rrhh_proyecciones_dotacion (empresa, obra_nombre, fecha_inicio, fecha_termino);

ALTER TABLE public.rrhh_proyecciones_dotacion ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rrhh_proyecciones_select ON public.rrhh_proyecciones_dotacion;
CREATE POLICY rrhh_proyecciones_select ON public.rrhh_proyecciones_dotacion FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = (SELECT auth.uid()) AND (u.empresa = rrhh_proyecciones_dotacion.empresa OR lower(u.empresa) = 'obraxis')));

DROP POLICY IF EXISTS rrhh_proyecciones_insert ON public.rrhh_proyecciones_dotacion;
CREATE POLICY rrhh_proyecciones_insert ON public.rrhh_proyecciones_dotacion FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = (SELECT auth.uid()) AND (u.empresa = rrhh_proyecciones_dotacion.empresa OR lower(u.empresa) = 'obraxis')));

DROP POLICY IF EXISTS rrhh_proyecciones_update ON public.rrhh_proyecciones_dotacion;
CREATE POLICY rrhh_proyecciones_update ON public.rrhh_proyecciones_dotacion FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = (SELECT auth.uid()) AND (u.empresa = rrhh_proyecciones_dotacion.empresa OR lower(u.empresa) = 'obraxis')))
WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = (SELECT auth.uid()) AND (u.empresa = rrhh_proyecciones_dotacion.empresa OR lower(u.empresa) = 'obraxis')));

DROP POLICY IF EXISTS rrhh_proyecciones_delete ON public.rrhh_proyecciones_dotacion;
CREATE POLICY rrhh_proyecciones_delete ON public.rrhh_proyecciones_dotacion FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = (SELECT auth.uid()) AND (u.empresa = rrhh_proyecciones_dotacion.empresa OR lower(u.empresa) = 'obraxis')));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.rrhh_proyecciones_dotacion TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.rrhh_proyecciones_dotacion_id_seq TO authenticated;
