-- Control de notificaciones Obraxis
create extension if not exists pgcrypto;

create table if not exists public.notificaciones_reglas (
  id uuid primary key default gen_random_uuid(),
  empresa text not null,
  nombre text not null,
  evento_codigo text not null,
  modulo text not null,
  descripcion text,
  obra_nombre text,
  destinatarios_roles jsonb not null default '[]'::jsonb,
  destinatarios_usuarios jsonb not null default '[]'::jsonb,
  correos_adicionales jsonb not null default '[]'::jsonb,
  canal_email boolean not null default true,
  canal_plataforma boolean not null default true,
  frecuencia text not null default 'Inmediata' check (frecuencia in ('Inmediata','Diaria','Semanal','Anticipada')),
  hora_envio time,
  dias_anticipacion integer check (dias_anticipacion is null or dias_anticipacion > 0),
  condiciones jsonb not null default '{}'::jsonb,
  activa boolean not null default true,
  creado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_notificaciones_reglas_empresa_evento on public.notificaciones_reglas (empresa, evento_codigo, activa);
create index if not exists idx_notificaciones_reglas_obra on public.notificaciones_reglas (empresa, obra_nombre) where activa;

create table if not exists public.notificaciones_entregas (
  id bigint generated by default as identity primary key,
  regla_id uuid references public.notificaciones_reglas(id) on delete set null,
  empresa text not null,
  evento_codigo text not null,
  obra_nombre text,
  canal text not null check (canal in ('Correo','Plataforma')),
  destinatario text,
  asunto text,
  estado text not null default 'Pendiente' check (estado in ('Pendiente','Procesando','Enviada','Leída','Error','Omitida')),
  error_detalle text,
  payload jsonb not null default '{}'::jsonb,
  programada_para timestamptz,
  enviada_at timestamptz,
  leida_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_notificaciones_entregas_empresa_fecha on public.notificaciones_entregas (empresa, created_at desc);
create index if not exists idx_notificaciones_entregas_pendientes on public.notificaciones_entregas (estado, programada_para) where estado = 'Pendiente';

comment on table public.notificaciones_reglas is 'Reglas centrales de notificación por empresa, obra, evento, rol y canal.';
comment on table public.notificaciones_entregas is 'Trazabilidad de notificaciones programadas, enviadas, leídas y fallidas.';

alter table public.notificaciones_reglas enable row level security;
alter table public.notificaciones_entregas enable row level security;

drop policy if exists notificaciones_reglas_empresa on public.notificaciones_reglas;
create policy notificaciones_reglas_empresa on public.notificaciones_reglas
for all to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where lower(u.correo) = lower(auth.jwt() ->> 'email')
      and (
        u.empresa = notificaciones_reglas.empresa
        or (u.empresa = 'Obraxis' and lower(coalesce(u.rol_base, u.rol, '')) = 'superusuario')
      )
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where lower(u.correo) = lower(auth.jwt() ->> 'email')
      and (
        u.empresa = notificaciones_reglas.empresa
        or (u.empresa = 'Obraxis' and lower(coalesce(u.rol_base, u.rol, '')) = 'superusuario')
      )
  )
);

drop policy if exists notificaciones_entregas_empresa on public.notificaciones_entregas;
create policy notificaciones_entregas_empresa on public.notificaciones_entregas
for all to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where lower(u.correo) = lower(auth.jwt() ->> 'email')
      and (
        u.empresa = notificaciones_entregas.empresa
        or (u.empresa = 'Obraxis' and lower(coalesce(u.rol_base, u.rol, '')) = 'superusuario')
      )
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where lower(u.correo) = lower(auth.jwt() ->> 'email')
      and (
        u.empresa = notificaciones_entregas.empresa
        or (u.empresa = 'Obraxis' and lower(coalesce(u.rol_base, u.rol, '')) = 'superusuario')
      )
  )
);

revoke all on public.notificaciones_reglas from anon;
revoke all on public.notificaciones_entregas from anon;
grant select, insert, update, delete on public.notificaciones_reglas to authenticated;
grant select, insert, update, delete on public.notificaciones_entregas to authenticated;
grant usage, select on all sequences in schema public to authenticated;
