-- Acceso visible por usuario + empresa, manteniendo correo como identidad interna de Supabase Auth.
create unique index if not exists uq_usuarios_usuario_empresa
  on public.usuarios(lower(btrim(usuario)), lower(btrim(empresa)));

create table if not exists public.auth_login_intentos (
  id bigint generated by default as identity primary key,
  clave_hash text not null,
  exitoso boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_auth_login_intentos_clave_fecha
  on public.auth_login_intentos(clave_hash, created_at desc);
alter table public.auth_login_intentos enable row level security;
revoke all on public.auth_login_intentos from public, anon, authenticated;
