CREATE TABLE IF NOT EXISTS public.rrhh_nominas_mensuales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT NOT NULL,
  periodo TEXT NOT NULL CHECK (periodo ~ '^[0-9]{4}-[0-9]{2}$'),
  estado TEXT NOT NULL DEFAULT 'Borrador' CHECK (estado IN ('Borrador','Cerrada','Pagada','Anulada')),
  parametros JSONB NOT NULL DEFAULT '{}'::jsonb,
  total_haberes NUMERIC NOT NULL DEFAULT 0,
  total_descuentos NUMERIC NOT NULL DEFAULT 0,
  total_liquido NUMERIC NOT NULL DEFAULT 0,
  generado_por TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa, periodo)
);

CREATE TABLE IF NOT EXISTS public.rrhh_nomina_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nomina_id BIGINT NOT NULL REFERENCES public.rrhh_nominas_mensuales(id) ON DELETE CASCADE,
  trabajador_id INTEGER REFERENCES public.maestro_personal(id) ON DELETE SET NULL,
  trabajador_rut TEXT,
  trabajador_nombre TEXT NOT NULL,
  obra_nombre TEXT,
  cargo TEXT,
  novedades JSONB NOT NULL DEFAULT '{}'::jsonb,
  calculo JSONB NOT NULL DEFAULT '{}'::jsonb,
  sueldo_liquido NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS rrhh_nomina_items_nomina_idx ON public.rrhh_nomina_items(nomina_id);
CREATE INDEX IF NOT EXISTS rrhh_nominas_empresa_periodo_idx ON public.rrhh_nominas_mensuales(empresa, periodo DESC);
ALTER TABLE public.rrhh_nominas_mensuales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rrhh_nomina_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rrhh_nominas_empresa ON public.rrhh_nominas_mensuales;
CREATE POLICY rrhh_nominas_empresa ON public.rrhh_nominas_mensuales FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=(SELECT auth.uid()) AND (u.empresa=rrhh_nominas_mensuales.empresa OR lower(u.empresa)='obraxis')))
WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=(SELECT auth.uid()) AND (u.empresa=rrhh_nominas_mensuales.empresa OR lower(u.empresa)='obraxis')));

DROP POLICY IF EXISTS rrhh_nomina_items_empresa ON public.rrhh_nomina_items;
CREATE POLICY rrhh_nomina_items_empresa ON public.rrhh_nomina_items FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.rrhh_nominas_mensuales n JOIN public.usuarios u ON (u.empresa=n.empresa OR lower(u.empresa)='obraxis') WHERE n.id=rrhh_nomina_items.nomina_id AND u.auth_user_id=(SELECT auth.uid())))
WITH CHECK (EXISTS (SELECT 1 FROM public.rrhh_nominas_mensuales n JOIN public.usuarios u ON (u.empresa=n.empresa OR lower(u.empresa)='obraxis') WHERE n.id=rrhh_nomina_items.nomina_id AND u.auth_user_id=(SELECT auth.uid())));

REVOKE ALL ON public.rrhh_nominas_mensuales, public.rrhh_nomina_items FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rrhh_nominas_mensuales, public.rrhh_nomina_items TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.rrhh_nominas_mensuales_id_seq, public.rrhh_nomina_items_id_seq TO authenticated;

NOTIFY pgrst, 'reload schema';
