-- Módulo Calidad de Obras: PAC/ITP, Solicitudes RDI y No Conformidades.
CREATE TABLE IF NOT EXISTS calidad_pac (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT,
  obra_nombre TEXT NOT NULL,
  partida TEXT NOT NULL,
  procedimiento TEXT NOT NULL,
  criterios TEXT NOT NULL,
  puntos_inspeccion TEXT,
  puntos_espera TEXT,
  responsable TEXT,
  estado TEXT NOT NULL DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Suspendido', 'Cerrado')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS calidad_rdi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT,
  obra_nombre TEXT NOT NULL,
  partida TEXT NOT NULL,
  pac_id BIGINT REFERENCES calidad_pac(id) ON DELETE SET NULL,
  codigo TEXT NOT NULL,
  fecha_solicitud DATE NOT NULL DEFAULT CURRENT_DATE,
  sector TEXT NOT NULL,
  cantidad NUMERIC,
  unidad TEXT,
  solicitado_por TEXT NOT NULL,
  inspector TEXT,
  fecha_inspeccion DATE,
  estado TEXT NOT NULL DEFAULT 'Borrador' CHECK (estado IN ('Borrador', 'Enviada', 'Observada', 'Aprobada', 'Rechazada', 'Cerrada')),
  observaciones TEXT,
  evidencia_urls JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE (obra_nombre, codigo)
);

CREATE TABLE IF NOT EXISTS calidad_no_conformidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT,
  obra_nombre TEXT NOT NULL,
  partida TEXT NOT NULL,
  rdi_id BIGINT REFERENCES calidad_rdi(id) ON DELETE SET NULL,
  codigo TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  clasificacion TEXT NOT NULL DEFAULT 'Menor' CHECK (clasificacion IN ('Menor', 'Mayor', 'Crítica')),
  estado TEXT NOT NULL DEFAULT 'Abierta' CHECK (estado IN ('Abierta', 'En corrección', 'Verificada', 'Cerrada')),
  responsable TEXT NOT NULL,
  fecha_compromiso DATE,
  causa_raiz TEXT,
  accion_correctiva TEXT,
  verificado_por TEXT,
  fecha_cierre DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE (obra_nombre, codigo)
);

-- Entrega y recepción formal de partidas terminadas o liberadas para la etapa siguiente.
CREATE TABLE IF NOT EXISTS calidad_recepciones_partidas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT,
  obra_nombre TEXT NOT NULL,
  codigo TEXT NOT NULL,
  partida TEXT NOT NULL,
  rdi_id BIGINT REFERENCES calidad_rdi(id) ON DELETE SET NULL,
  fecha_entrega DATE NOT NULL DEFAULT CURRENT_DATE,
  cantidad NUMERIC,
  unidad TEXT,
  sector TEXT,
  entrega_por TEXT NOT NULL,
  recibe_por TEXT,
  estado TEXT NOT NULL DEFAULT 'Pendiente de recepción' CHECK (estado IN ('Pendiente de recepción', 'Recibida con observaciones', 'Recibida conforme', 'Rechazada')),
  observaciones TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE (obra_nombre, codigo)
);

ALTER TABLE calidad_pac ENABLE ROW LEVEL SECURITY;
ALTER TABLE calidad_rdi ENABLE ROW LEVEL SECURITY;
ALTER TABLE calidad_no_conformidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE calidad_recepciones_partidas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON calidad_pac;
CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON calidad_pac FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON calidad_rdi;
CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON calidad_rdi FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON calidad_no_conformidades;
CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON calidad_no_conformidades FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON calidad_recepciones_partidas;
CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON calidad_recepciones_partidas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

GRANT ALL ON calidad_pac, calidad_rdi, calidad_no_conformidades, calidad_recepciones_partidas TO anon, authenticated;
GRANT ALL ON SEQUENCE calidad_pac_id_seq, calidad_rdi_id_seq, calidad_no_conformidades_id_seq, calidad_recepciones_partidas_id_seq TO anon, authenticated;
