-- Documentación laboral real, privada y revisable con IA opcional por empresa.
create table if not exists public.rrhh_documentos_trabajadores (
  id bigint generated by default as identity primary key,
  empresa text not null,
  trabajador_id bigint not null,
  trabajador_nombre text not null,
  trabajador_rut text,
  tipo_documento text not null,
  archivo_nombre text not null,
  archivo_path text not null,
  mime_type text,
  fecha_emision date,
  fecha_vencimiento date,
  estado_vigencia text not null default 'Sin fecha' check (estado_vigencia in ('Vigente','Por vencer','Vencido','Sin fecha','Requiere revisión')),
  confianza_ia numeric(5,2),
  resultado_ia jsonb,
  confirmado boolean not null default false,
  creado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists rrhh_documentos_empresa_trabajador_idx on public.rrhh_documentos_trabajadores(empresa,trabajador_id,created_at desc);
create index if not exists rrhh_documentos_vencimiento_idx on public.rrhh_documentos_trabajadores(empresa,fecha_vencimiento) where fecha_vencimiento is not null;
alter table public.rrhh_documentos_trabajadores enable row level security;
revoke all on public.rrhh_documentos_trabajadores from anon;
grant select,insert,update,delete on public.rrhh_documentos_trabajadores to authenticated;
grant usage,select on sequence public.rrhh_documentos_trabajadores_id_seq to authenticated;
drop policy if exists rrhh_documentos_empresa_access on public.rrhh_documentos_trabajadores;
create policy rrhh_documentos_empresa_access on public.rrhh_documentos_trabajadores for all to authenticated
using (private.obraxis_actor_can_access_company(empresa))
with check (private.obraxis_actor_can_access_company(empresa));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('rrhh-documentos','rrhh-documentos',false,10485760,array['application/pdf','image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists rrhh_documentos_storage_select on storage.objects;
create policy rrhh_documentos_storage_select on storage.objects for select to authenticated
using (bucket_id='rrhh-documentos' and private.obraxis_actor_can_access_company((storage.foldername(name))[1]));
drop policy if exists rrhh_documentos_storage_insert on storage.objects;
create policy rrhh_documentos_storage_insert on storage.objects for insert to authenticated
with check (bucket_id='rrhh-documentos' and private.obraxis_actor_can_access_company((storage.foldername(name))[1]));
drop policy if exists rrhh_documentos_storage_delete on storage.objects;
create policy rrhh_documentos_storage_delete on storage.objects for delete to authenticated
using (bucket_id='rrhh-documentos' and private.obraxis_actor_can_access_company((storage.foldername(name))[1]));
