-- Libro de Obras Digital: registros formales y trazables por obra.
CREATE TABLE IF NOT EXISTS libro_obra_digital (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT NOT NULL,
  obra_nombre TEXT NOT NULL,
  folio TEXT NOT NULL,
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  tipo TEXT NOT NULL CHECK (tipo IN ('Registro diario', 'Instrucción', 'Observación', 'Acuerdo', 'Incidente')),
  asunto TEXT NOT NULL,
  detalle TEXT NOT NULL,
  emisor TEXT NOT NULL,
  destinatario TEXT,
  partida TEXT,
  estado TEXT NOT NULL DEFAULT 'Abierto' CHECK (estado IN ('Abierto', 'Respondido', 'Cerrado')),
  respuesta TEXT,
  fecha_respuesta DATE,
  fecha_cierre DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (empresa, obra_nombre, folio)
);

CREATE INDEX IF NOT EXISTS libro_obra_digital_obra_fecha_idx ON libro_obra_digital (empresa, obra_nombre, fecha DESC);
ALTER TABLE libro_obra_digital ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON libro_obra_digital;
CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON libro_obra_digital FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
GRANT ALL ON libro_obra_digital TO anon, authenticated;
GRANT ALL ON SEQUENCE libro_obra_digital_id_seq TO anon, authenticated;

-- Flujo documental y registro de acciones verificables desde Obraxis.
ALTER TABLE libro_obra_digital ADD COLUMN IF NOT EXISTS flujo_estado TEXT NOT NULL DEFAULT 'Emitido';
ALTER TABLE libro_obra_digital ADD COLUMN IF NOT EXISTS trazabilidad JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE libro_obra_digital ADD COLUMN IF NOT EXISTS autorizador_nombre TEXT;
ALTER TABLE libro_obra_digital ADD COLUMN IF NOT EXISTS token_cliente TEXT UNIQUE;
ALTER TABLE libro_obra_digital ADD COLUMN IF NOT EXISTS clave_cliente_hash TEXT;
ALTER TABLE libro_obra_digital DROP CONSTRAINT IF EXISTS libro_obra_digital_flujo_estado_check;
ALTER TABLE libro_obra_digital ADD CONSTRAINT libro_obra_digital_flujo_estado_check CHECK (flujo_estado IN ('Emitido', 'Autorizado', 'Enviado al cliente', 'Observado por cliente', 'Aceptado por cliente', 'Aceptado con observaciones', 'Cerrado'));
