-- Historial trazable de asignaciones de trabajadores a obras y centros de gestión.

alter table public.maestro_personal
  add column if not exists fecha_asig date;

create table if not exists public.rrhh_asignaciones_personal (
  id bigint generated by default as identity primary key,
  empresa text not null,
  trabajador_id integer not null references public.maestro_personal(id) on delete cascade,
  trabajador_nombre text not null,
  trabajador_rut text,
  cargo text,
  obra_nombre text,
  centro_gestion_id integer references public.facturacion_centros_gestion(id) on delete set null,
  destino_nombre text not null default 'Sin asignar',
  fecha_inicio date not null,
  fecha_termino date,
  creado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rrhh_asignaciones_fechas_validas
    check (fecha_termino is null or fecha_termino >= fecha_inicio)
);

create index if not exists rrhh_asignaciones_empresa_periodo_idx
  on public.rrhh_asignaciones_personal (empresa, fecha_inicio, fecha_termino);
create index if not exists rrhh_asignaciones_trabajador_idx
  on public.rrhh_asignaciones_personal (trabajador_id, fecha_inicio desc);
create unique index if not exists rrhh_asignaciones_una_activa_idx
  on public.rrhh_asignaciones_personal (trabajador_id)
  where fecha_termino is null;

alter table public.rrhh_asignaciones_personal enable row level security;

drop policy if exists rrhh_asignaciones_empresa_select on public.rrhh_asignaciones_personal;
create policy rrhh_asignaciones_empresa_select
  on public.rrhh_asignaciones_personal for select to authenticated
  using (exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = rrhh_asignaciones_personal.empresa or lower(u.empresa) = 'obraxis')
  ));

drop policy if exists rrhh_asignaciones_empresa_insert on public.rrhh_asignaciones_personal;
create policy rrhh_asignaciones_empresa_insert
  on public.rrhh_asignaciones_personal for insert to authenticated
  with check (exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = rrhh_asignaciones_personal.empresa or lower(u.empresa) = 'obraxis')
  ));

drop policy if exists rrhh_asignaciones_empresa_update on public.rrhh_asignaciones_personal;
create policy rrhh_asignaciones_empresa_update
  on public.rrhh_asignaciones_personal for update to authenticated
  using (exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = rrhh_asignaciones_personal.empresa or lower(u.empresa) = 'obraxis')
  ))
  with check (exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = rrhh_asignaciones_personal.empresa or lower(u.empresa) = 'obraxis')
  ));

grant select, insert, update on public.rrhh_asignaciones_personal to authenticated;
grant usage, select on sequence public.rrhh_asignaciones_personal_id_seq to authenticated;

-- Crea un período inicial para los trabajadores existentes. Los cambios futuros se
-- registran desde la interfaz y conservan tanto el destino anterior como el nuevo.
update public.maestro_personal
set fecha_asig = coalesce(fecha_asig, created_at::date, current_date)
where fecha_asig is null;

insert into public.rrhh_asignaciones_personal (
  empresa, trabajador_id, trabajador_nombre, trabajador_rut, cargo,
  obra_nombre, centro_gestion_id, destino_nombre, fecha_inicio, creado_por
)
select
  coalesce(mp.empresa, 'Obraxis'), mp.id, mp.nombre, mp.rut, mp.cargo,
  nullif(mp.obra_nombre, ''), mp.centro_gestion_id,
  coalesce(cg.codigo || ' · ' || cg.nombre, nullif(mp.obra_nombre, ''), 'Sin asignar'),
  coalesce(mp.fecha_asig, mp.created_at::date, current_date), 'Migración inicial'
from public.maestro_personal mp
left join public.facturacion_centros_gestion cg on cg.id = mp.centro_gestion_id
where not exists (
  select 1 from public.rrhh_asignaciones_personal h where h.trabajador_id = mp.id
);

