-- Last Planner: asociación opcional obra-presupuesto y checklist compartido de recursos/restricciones.
CREATE TABLE IF NOT EXISTS obra_presupuestos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT,
  obra_nombre TEXT NOT NULL,
  presupuesto_id BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE (obra_nombre)
);

CREATE TABLE IF NOT EXISTS last_planner_recursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT,
  obra_nombre TEXT NOT NULL,
  partida TEXT NOT NULL,
  recurso_clave TEXT NOT NULL,
  recurso TEXT NOT NULL,
  tipo TEXT DEFAULT 'Recurso',
  unidad TEXT,
  cantidad_requerida NUMERIC DEFAULT 0,
  origen TEXT NOT NULL DEFAULT 'Manual',
  estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'confirmado', 'no_aplica')),
  responsable TEXT,
  observacion TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE (obra_nombre, partida, recurso_clave)
);

ALTER TABLE obra_presupuestos ENABLE ROW LEVEL SECURITY;
ALTER TABLE last_planner_recursos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON obra_presupuestos;
CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON obra_presupuestos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON last_planner_recursos;
CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON last_planner_recursos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

GRANT ALL ON obra_presupuestos, last_planner_recursos TO anon, authenticated;
GRANT ALL ON SEQUENCE obra_presupuestos_id_seq, last_planner_recursos_id_seq TO anon, authenticated;
