-- Contratos colaborativos entre dos empresas Obraxis.
-- Cada empresa conserva su obra, presupuesto y análisis; solo se comparte el alcance enlazado.

create extension if not exists pgcrypto;

create table if not exists public.contratos_colaborativos (
  id uuid primary key default gen_random_uuid(),
  colaboracion_id bigint not null references public.colaboraciones_obra(id) on delete cascade,
  codigo text not null,
  nombre text not null,
  empresa_contratista text not null,
  rut_contratista text,
  obra_contratista_id integer not null references public.obras(id),
  obra_contratista_nombre text not null,
  empresa_colaboradora text not null,
  rut_colaboradora text,
  obra_colaboradora_id integer references public.obras(id),
  obra_colaboradora_nombre text,
  especialidad text,
  monto_contrato numeric(18,2) not null default 0 check (monto_contrato >= 0),
  fecha_inicio date,
  fecha_termino date,
  estado text not null default 'Configuracion' check (estado in ('Configuracion','Pendiente contraparte','Activo','Suspendido','Terminado','Rechazado')),
  permisos_compartidos jsonb not null default '{"avances":true,"asistencia":true,"estados_pago":true,"calidad":false,"prevencion":false,"libro_obra":false}'::jsonb,
  creado_por text,
  aceptado_por text,
  aceptado_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (colaboracion_id, codigo)
);

create index if not exists contratos_colaborativos_empresas_idx
  on public.contratos_colaborativos (empresa_contratista, empresa_colaboradora, estado);
create index if not exists contratos_colaborativos_obras_idx
  on public.contratos_colaborativos (obra_contratista_id, obra_colaboradora_id);

create table if not exists public.contratos_colaborativos_partidas (
  id uuid primary key default gen_random_uuid(),
  contrato_id uuid not null references public.contratos_colaborativos(id) on delete cascade,
  partida_contratista_id integer not null references public.partidas_obra(id),
  partida_colaboradora_id integer references public.partidas_obra(id),
  codigo_contratista text,
  nombre_contratista text not null,
  codigo_colaboradora text,
  nombre_colaboradora text,
  unidad_contratista text,
  unidad_colaboradora text,
  cantidad_contratada numeric(18,4) not null default 0 check (cantidad_contratada >= 0),
  factor_conversion numeric(18,6) not null default 1 check (factor_conversion > 0),
  ponderacion numeric(9,6) not null default 0 check (ponderacion >= 0),
  estado text not null default 'Pendiente' check (estado in ('Pendiente','Propuesto','Aceptado','Observado','Inactivo')),
  observacion text,
  creado_por text,
  aceptado_por text,
  aceptado_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (contrato_id, partida_contratista_id, partida_colaboradora_id)
);

create index if not exists contratos_colaborativos_partidas_contrato_idx
  on public.contratos_colaborativos_partidas (contrato_id, estado);

create table if not exists public.contratos_colaborativos_eventos (
  id bigint generated by default as identity primary key,
  contrato_id uuid not null references public.contratos_colaborativos(id) on delete cascade,
  empresa text not null,
  accion text not null,
  estado_resultante text,
  detalle text,
  actor_nombre text,
  actor_auth_id uuid default auth.uid(),
  created_at timestamptz not null default now()
);

alter table public.subcontrato_avances add column if not exists contrato_colaborativo_id uuid references public.contratos_colaborativos(id);
alter table public.subcontrato_avances add column if not exists enlace_partida_id uuid references public.contratos_colaborativos_partidas(id);
alter table public.subcontrato_avances add column if not exists empresa_origen text;
alter table public.subcontrato_avances add column if not exists obra_origen_id integer references public.obras(id);
alter table public.subcontrato_avances add column if not exists enviado_por_auth_id uuid;
alter table public.subcontrato_avances add column if not exists revisado_por text;
alter table public.subcontrato_avances add column if not exists revisado_at timestamptz;

alter table public.subcontrato_asistencia add column if not exists contrato_colaborativo_id uuid references public.contratos_colaborativos(id);
alter table public.subcontrato_asistencia add column if not exists empresa_origen text;
alter table public.subcontrato_asistencia add column if not exists obra_origen_id integer references public.obras(id);
alter table public.subcontrato_asistencia add column if not exists enviado_por_auth_id uuid;

alter table public.subcontrato_estados_pago add column if not exists contrato_colaborativo_id uuid references public.contratos_colaborativos(id);
alter table public.subcontrato_estados_pago add column if not exists empresa_origen text;
alter table public.subcontrato_estados_pago add column if not exists obra_origen_id integer references public.obras(id);
alter table public.subcontrato_estados_pago add column if not exists enviado_por_auth_id uuid;

alter table public.contratos_colaborativos enable row level security;
alter table public.contratos_colaborativos_partidas enable row level security;
alter table public.contratos_colaborativos_eventos enable row level security;

grant select, insert, update on public.contratos_colaborativos to authenticated;
grant select, insert, update on public.contratos_colaborativos_partidas to authenticated;
grant select, insert on public.contratos_colaborativos_eventos to authenticated;
grant usage, select on sequence public.contratos_colaborativos_eventos_id_seq to authenticated;

drop policy if exists "miembros ven contratos colaborativos" on public.contratos_colaborativos;
create policy "miembros ven contratos colaborativos" on public.contratos_colaborativos for select to authenticated
using (private.obraxis_actor_can_access_company(empresa_contratista) or private.obraxis_actor_can_access_company(empresa_colaboradora));

drop policy if exists "contratista crea contratos colaborativos" on public.contratos_colaborativos;
create policy "contratista crea contratos colaborativos" on public.contratos_colaborativos for insert to authenticated
with check (private.obraxis_actor_can_access_company(empresa_contratista));

drop policy if exists "miembros actualizan contratos colaborativos" on public.contratos_colaborativos;
create policy "miembros actualizan contratos colaborativos" on public.contratos_colaborativos for update to authenticated
using (private.obraxis_actor_can_access_company(empresa_contratista) or private.obraxis_actor_can_access_company(empresa_colaboradora))
with check (private.obraxis_actor_can_access_company(empresa_contratista) or private.obraxis_actor_can_access_company(empresa_colaboradora));

drop policy if exists "miembros ven partidas colaborativas" on public.contratos_colaborativos_partidas;
create policy "miembros ven partidas colaborativas" on public.contratos_colaborativos_partidas for select to authenticated
using (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));

drop policy if exists "miembros gestionan partidas colaborativas" on public.contratos_colaborativos_partidas;
create policy "miembros gestionan partidas colaborativas" on public.contratos_colaborativos_partidas for insert to authenticated
with check (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));

drop policy if exists "miembros modifican partidas colaborativas" on public.contratos_colaborativos_partidas;
create policy "miembros modifican partidas colaborativas" on public.contratos_colaborativos_partidas for update to authenticated
using (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))))
with check (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));

drop policy if exists "miembros ven eventos colaborativos" on public.contratos_colaborativos_eventos;
create policy "miembros ven eventos colaborativos" on public.contratos_colaborativos_eventos for select to authenticated
using (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));

drop policy if exists "miembros registran eventos colaborativos" on public.contratos_colaborativos_eventos;
create policy "miembros registran eventos colaborativos" on public.contratos_colaborativos_eventos for insert to authenticated
with check (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));

-- Las entregas operativas son visibles y gestionables por las dos empresas del contrato.
grant select, insert, update on public.subcontrato_avances, public.subcontrato_asistencia, public.subcontrato_estados_pago to authenticated;

drop policy if exists "miembros contrato ven avances" on public.subcontrato_avances;
create policy "miembros contrato ven avances" on public.subcontrato_avances for select to authenticated
using (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));
drop policy if exists "colaboradora envia avances" on public.subcontrato_avances;
create policy "colaboradora envia avances" on public.subcontrato_avances for insert to authenticated
with check (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and c.estado = 'Activo' and private.obraxis_actor_can_access_company(c.empresa_colaboradora)));
drop policy if exists "contratista revisa avances" on public.subcontrato_avances;
create policy "contratista revisa avances" on public.subcontrato_avances for update to authenticated
using (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and private.obraxis_actor_can_access_company(c.empresa_contratista)))
with check (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and private.obraxis_actor_can_access_company(c.empresa_contratista)));

drop policy if exists "miembros contrato ven asistencia" on public.subcontrato_asistencia;
create policy "miembros contrato ven asistencia" on public.subcontrato_asistencia for select to authenticated
using (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));
drop policy if exists "colaboradora envia asistencia" on public.subcontrato_asistencia;
create policy "colaboradora envia asistencia" on public.subcontrato_asistencia for insert to authenticated
with check (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and c.estado = 'Activo' and private.obraxis_actor_can_access_company(c.empresa_colaboradora)));

drop policy if exists "miembros contrato ven estados pago" on public.subcontrato_estados_pago;
create policy "miembros contrato ven estados pago" on public.subcontrato_estados_pago for select to authenticated
using (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));
drop policy if exists "colaboradora envia estados pago" on public.subcontrato_estados_pago;
create policy "colaboradora envia estados pago" on public.subcontrato_estados_pago for insert to authenticated
with check (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and c.estado = 'Activo' and private.obraxis_actor_can_access_company(c.empresa_colaboradora)));
drop policy if exists "contratista revisa estados pago" on public.subcontrato_estados_pago;
create policy "contratista revisa estados pago" on public.subcontrato_estados_pago for update to authenticated
using (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and private.obraxis_actor_can_access_company(c.empresa_contratista)))
with check (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and private.obraxis_actor_can_access_company(c.empresa_contratista)));
