CREATE TABLE IF NOT EXISTS public.maquinaria_fallas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipo_id BIGINT NOT NULL REFERENCES public.inventario_maquinaria(id) ON DELETE CASCADE,
  equipo_patente TEXT,
  equipo_tipo TEXT,
  fecha DATE NOT NULL,
  severidad TEXT NOT NULL DEFAULT 'Media' CHECK (severidad IN ('Baja','Media','Alta','Crítica')),
  detuvo_equipo BOOLEAN NOT NULL DEFAULT true,
  horas_fuera_servicio NUMERIC NOT NULL DEFAULT 0 CHECK (horas_fuera_servicio >= 0),
  descripcion TEXT NOT NULL,
  causa TEXT,
  solucion TEXT,
  responsable TEXT,
  registrado_por TEXT,
  empresa TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.maquinaria_mantenciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipo_id BIGINT NOT NULL REFERENCES public.inventario_maquinaria(id) ON DELETE CASCADE,
  equipo_patente TEXT,
  equipo_tipo TEXT,
  fecha DATE NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'Preventiva' CHECK (tipo IN ('Preventiva','Correctiva','Predictiva','Inspección')),
  horometro NUMERIC,
  descripcion TEXT NOT NULL,
  costo NUMERIC NOT NULL DEFAULT 0 CHECK (costo >= 0),
  proveedor TEXT,
  responsable TEXT,
  registrado_por TEXT,
  empresa TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS maquinaria_fallas_empresa_equipo_fecha_idx ON public.maquinaria_fallas(empresa, equipo_id, fecha DESC);
CREATE INDEX IF NOT EXISTS maquinaria_mantenciones_empresa_equipo_fecha_idx ON public.maquinaria_mantenciones(empresa, equipo_id, fecha DESC);

ALTER TABLE public.maquinaria_fallas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maquinaria_mantenciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS maquinaria_fallas_authenticated_select ON public.maquinaria_fallas;
CREATE POLICY maquinaria_fallas_authenticated_select ON public.maquinaria_fallas FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = auth.uid() AND (u.empresa = maquinaria_fallas.empresa OR lower(u.empresa) = 'obraxis')));
DROP POLICY IF EXISTS maquinaria_fallas_authenticated_insert ON public.maquinaria_fallas;
CREATE POLICY maquinaria_fallas_authenticated_insert ON public.maquinaria_fallas FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = auth.uid() AND (u.empresa = maquinaria_fallas.empresa OR lower(u.empresa) = 'obraxis')));
DROP POLICY IF EXISTS maquinaria_mantenciones_authenticated_select ON public.maquinaria_mantenciones;
CREATE POLICY maquinaria_mantenciones_authenticated_select ON public.maquinaria_mantenciones FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = auth.uid() AND (u.empresa = maquinaria_mantenciones.empresa OR lower(u.empresa) = 'obraxis')));
DROP POLICY IF EXISTS maquinaria_mantenciones_authenticated_insert ON public.maquinaria_mantenciones;
CREATE POLICY maquinaria_mantenciones_authenticated_insert ON public.maquinaria_mantenciones FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = auth.uid() AND (u.empresa = maquinaria_mantenciones.empresa OR lower(u.empresa) = 'obraxis')));
