CREATE TABLE IF NOT EXISTS public.subcontrato_avances (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, subcontrato_id BIGINT NOT NULL, subcontrato_nombre TEXT NOT NULL, empresa TEXT NOT NULL, obra_nombre TEXT NOT NULL, fecha DATE NOT NULL, partida_nombre TEXT NOT NULL, cantidad NUMERIC NOT NULL CHECK(cantidad>=0), unidad TEXT, comentario TEXT, estado TEXT NOT NULL DEFAULT 'Reportado', created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.subcontrato_asistencia (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, subcontrato_id BIGINT NOT NULL, subcontrato_nombre TEXT NOT NULL, empresa TEXT NOT NULL, obra_nombre TEXT NOT NULL, fecha DATE NOT NULL, presentes INTEGER NOT NULL CHECK(presentes>=0), ausentes INTEGER DEFAULT 0 CHECK(ausentes>=0), horas_hombre NUMERIC DEFAULT 0 CHECK(horas_hombre>=0), estado TEXT NOT NULL DEFAULT 'Reportado', created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.subcontrato_estados_pago (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, subcontrato_id BIGINT NOT NULL, subcontrato_nombre TEXT NOT NULL, empresa TEXT NOT NULL, obra_nombre TEXT NOT NULL, numero INTEGER NOT NULL, periodo_desde DATE NOT NULL, periodo_hasta DATE NOT NULL, monto_presentado NUMERIC NOT NULL CHECK(monto_presentado>=0), monto_aprobado NUMERIC, factura_folio TEXT, factura_url TEXT, observaciones TEXT, estado TEXT NOT NULL DEFAULT 'Presentado', aprobado_por TEXT, aprobado_at TIMESTAMPTZ, costo_real_id BIGINT, created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(subcontrato_id,obra_nombre,numero));
CREATE TABLE IF NOT EXISTS public.costos_reales_obra (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, obra_nombre TEXT NOT NULL, nombre TEXT NOT NULL, tipo_costo TEXT, asociar_factura BOOLEAN DEFAULT false, num_factura TEXT, monto NUMERIC NOT NULL DEFAULT 0, imputaciones JSONB DEFAULT '[]', empresa TEXT, origen TEXT, origen_id BIGINT UNIQUE, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.subcontrato_avances ENABLE ROW LEVEL SECURITY; ALTER TABLE public.subcontrato_asistencia ENABLE ROW LEVEL SECURITY; ALTER TABLE public.subcontrato_estados_pago ENABLE ROW LEVEL SECURITY; ALTER TABLE public.costos_reales_obra ENABLE ROW LEVEL SECURITY;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['subcontrato_avances','subcontrato_asistencia','subcontrato_estados_pago','costos_reales_obra'] LOOP EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I','empresa_interna_select',t); EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=auth.uid() AND (u.empresa=%I.empresa OR lower(u.empresa)=''obraxis'')))','empresa_interna_select',t,t); END LOOP; END $$;
CREATE OR REPLACE FUNCTION public.aprobar_ep_subcontrato_y_cargar_costo(p_estado_pago_id BIGINT,p_aprobado_por TEXT) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE ep public.subcontrato_estados_pago; cid BIGINT; BEGIN SELECT * INTO ep FROM public.subcontrato_estados_pago WHERE id=p_estado_pago_id FOR UPDATE; IF ep.id IS NULL THEN RAISE EXCEPTION 'Estado de pago no encontrado'; END IF; IF NOT EXISTS(SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=auth.uid() AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis') AND (lower(coalesce(u.rol_base,'')) IN ('administrador','admin','superadmin') OR lower(coalesce(u.rol,'')) LIKE '%admin%' OR coalesce(u.permisos,'{}'::jsonb) ? 'obras.subcontratos.aprobar_pago')) THEN RAISE EXCEPTION 'Tu rol no tiene permiso para aprobar estados de pago de subcontratos'; END IF; IF coalesce(ep.factura_folio,'')='' THEN RAISE EXCEPTION 'Debe existir una factura asociada'; END IF; INSERT INTO public.costos_reales_obra(obra_nombre,nombre,tipo_costo,asociar_factura,num_factura,monto,empresa,origen,origen_id) VALUES(ep.obra_nombre,'Estado de pago subcontrato · '||ep.subcontrato_nombre,'Subcontrato',true,ep.factura_folio,coalesce(ep.monto_aprobado,ep.monto_presentado),ep.empresa,'Estado de pago subcontrato',ep.id) ON CONFLICT(origen_id) DO UPDATE SET monto=excluded.monto,num_factura=excluded.num_factura RETURNING id INTO cid; UPDATE public.subcontrato_estados_pago SET estado='Aprobado',monto_aprobado=coalesce(monto_aprobado,monto_presentado),aprobado_por=p_aprobado_por,aprobado_at=now(),costo_real_id=cid WHERE id=ep.id; RETURN cid; END $$;
REVOKE ALL ON FUNCTION public.aprobar_ep_subcontrato_y_cargar_costo(BIGINT,TEXT) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.aprobar_ep_subcontrato_y_cargar_costo(BIGINT,TEXT) TO authenticated;

-- Expediente documental de estados de pago de subcontratos.
CREATE TABLE IF NOT EXISTS public.subcontrato_ep_requisitos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT NOT NULL,
  obra_nombre TEXT,
  codigo TEXT NOT NULL,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  categoria TEXT NOT NULL DEFAULT 'Contractual' CHECK (categoria IN ('Legal','Laboral y previsional','Tributario','Contractual','Operacional')),
  fundamento TEXT,
  obligatorio BOOLEAN NOT NULL DEFAULT TRUE,
  requiere_vigencia BOOLEAN NOT NULL DEFAULT FALSE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  orden INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa, obra_nombre, codigo)
);

CREATE TABLE IF NOT EXISTS public.subcontrato_ep_documentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado_pago_id BIGINT NOT NULL REFERENCES public.subcontrato_estados_pago(id) ON DELETE CASCADE,
  requisito_id BIGINT NOT NULL REFERENCES public.subcontrato_ep_requisitos(id),
  archivo_nombre TEXT NOT NULL,
  archivo_path TEXT NOT NULL,
  mime_type TEXT,
  tamano_bytes BIGINT CHECK (tamano_bytes IS NULL OR tamano_bytes >= 0),
  periodo_desde DATE,
  periodo_hasta DATE,
  version INTEGER NOT NULL DEFAULT 1,
  estado TEXT NOT NULL DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente','Aprobado','Observado','Rechazado')),
  observacion_revision TEXT,
  cargado_por TEXT,
  revisado_por TEXT,
  revisado_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (estado_pago_id, requisito_id)
);

CREATE TABLE IF NOT EXISTS public.subcontrato_ep_historial (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado_pago_id BIGINT NOT NULL REFERENCES public.subcontrato_estados_pago(id) ON DELETE CASCADE,
  documento_id BIGINT REFERENCES public.subcontrato_ep_documentos(id) ON DELETE SET NULL,
  accion TEXT NOT NULL,
  estado_origen TEXT,
  estado_destino TEXT,
  detalle TEXT,
  actor_nombre TEXT,
  actor_rut TEXT,
  actor_cargo TEXT,
  actor_empresa TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.subcontrato_ep_requisitos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subcontrato_ep_documentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subcontrato_ep_historial ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ep_requisitos_empresa ON public.subcontrato_ep_requisitos;
CREATE POLICY ep_requisitos_empresa ON public.subcontrato_ep_requisitos FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=(SELECT auth.uid()) AND (u.empresa=subcontrato_ep_requisitos.empresa OR lower(u.empresa)='obraxis')))
WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=(SELECT auth.uid()) AND (u.empresa=subcontrato_ep_requisitos.empresa OR lower(u.empresa)='obraxis')));

DROP POLICY IF EXISTS ep_documentos_empresa ON public.subcontrato_ep_documentos;
CREATE POLICY ep_documentos_empresa ON public.subcontrato_ep_documentos FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.subcontrato_estados_pago ep JOIN public.usuarios u ON u.auth_user_id=(SELECT auth.uid()) WHERE ep.id=subcontrato_ep_documentos.estado_pago_id AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis')))
WITH CHECK (EXISTS (SELECT 1 FROM public.subcontrato_estados_pago ep JOIN public.usuarios u ON u.auth_user_id=(SELECT auth.uid()) WHERE ep.id=subcontrato_ep_documentos.estado_pago_id AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis')));

DROP POLICY IF EXISTS ep_historial_empresa ON public.subcontrato_ep_historial;
CREATE POLICY ep_historial_empresa ON public.subcontrato_ep_historial FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.subcontrato_estados_pago ep JOIN public.usuarios u ON u.auth_user_id=(SELECT auth.uid()) WHERE ep.id=subcontrato_ep_historial.estado_pago_id AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis')))
WITH CHECK (EXISTS (SELECT 1 FROM public.subcontrato_estados_pago ep JOIN public.usuarios u ON u.auth_user_id=(SELECT auth.uid()) WHERE ep.id=subcontrato_ep_historial.estado_pago_id AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis')));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.subcontrato_ep_requisitos, public.subcontrato_ep_documentos, public.subcontrato_ep_historial TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

INSERT INTO storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
VALUES ('subcontratos-estados-pago','subcontratos-estados-pago',false,15728640,ARRAY['application/pdf','image/jpeg','image/png','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'])
ON CONFLICT (id) DO UPDATE SET public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

DROP POLICY IF EXISTS ep_archivos_insert ON storage.objects;
CREATE POLICY ep_archivos_insert ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id='subcontratos-estados-pago' AND owner_id=(SELECT auth.uid())::text);
DROP POLICY IF EXISTS ep_archivos_select ON storage.objects;
CREATE POLICY ep_archivos_select ON storage.objects FOR SELECT TO authenticated
USING (bucket_id='subcontratos-estados-pago' AND EXISTS (
  SELECT 1 FROM public.subcontrato_ep_documentos d
  JOIN public.subcontrato_estados_pago ep ON ep.id=d.estado_pago_id
  JOIN public.usuarios u ON u.auth_user_id=(SELECT auth.uid())
  WHERE d.archivo_path=storage.objects.name AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis')
));
DROP POLICY IF EXISTS ep_archivos_update ON storage.objects;
CREATE POLICY ep_archivos_update ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id='subcontratos-estados-pago' AND owner_id=(SELECT auth.uid())::text)
WITH CHECK (bucket_id='subcontratos-estados-pago' AND owner_id=(SELECT auth.uid())::text);

INSERT INTO public.subcontrato_ep_requisitos (empresa,codigo,nombre,descripcion,categoria,fundamento,obligatorio,requiere_vigencia,orden)
SELECT DISTINCT e.empresa, d.codigo,d.nombre,d.descripcion,d.categoria,d.fundamento,d.obligatorio,d.requiere_vigencia,d.orden
FROM public.subcontrato_estados_pago e
CROSS JOIN (VALUES
 ('F30-1','Certificado F30-1','Certificado de cumplimiento de obligaciones laborales y previsionales del período.','Legal','Artículo 183-C del Código del Trabajo',true,true,10),
 ('LIQ-REM','Liquidaciones de remuneraciones','Liquidaciones del personal afecto al contrato durante el período.','Laboral y previsional','Derecho de información de la empresa principal',true,false,20),
 ('COT-PREV','Cotizaciones previsionales','Planilla y comprobante de pago de cotizaciones previsionales.','Laboral y previsional','Respaldo del cumplimiento previsional',true,false,30),
 ('NOM-PER','Nómina de personal','Nómina de trabajadores asociados a la obra y al período.','Contractual','Control del alcance certificado',true,false,40),
 ('ASIS','Control de asistencia','Registro de asistencia del período.','Operacional','Respaldo contractual y de dotación',false,false,50),
 ('PAGO-REM','Comprobantes de pago de remuneraciones','Comprobantes de transferencia o respaldo equivalente.','Contractual','Antecedente complementario configurable',false,false,60),
 ('FACTURA','Factura asociada','Factura tributaria asociada al estado de pago.','Tributario','Documento tributario asociado al pago',true,false,70),
 ('RESP-AV','Respaldo de avance y recepción','Valorización, recepción u otro respaldo contractual del avance.','Operacional','Antecedente contractual configurable',false,false,80)
) AS d(codigo,nombre,descripcion,categoria,fundamento,obligatorio,requiere_vigencia,orden)
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION public.aprobar_ep_subcontrato_y_cargar_costo(p_estado_pago_id BIGINT,p_aprobado_por TEXT) RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE ep public.subcontrato_estados_pago; cid BIGINT; faltantes INTEGER;
BEGIN
 SELECT * INTO ep FROM public.subcontrato_estados_pago WHERE id=p_estado_pago_id FOR UPDATE;
 IF ep.id IS NULL THEN RAISE EXCEPTION 'Estado de pago no encontrado'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=auth.uid() AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis') AND (lower(coalesce(u.rol_base,'')) IN ('administrador','admin','superadmin') OR lower(coalesce(u.rol,'')) LIKE '%admin%' OR coalesce(u.permisos,'{}'::jsonb) ? 'obras.subcontratos.aprobar')) THEN RAISE EXCEPTION 'Tu rol no tiene permiso para aprobar estados de pago de subcontratos'; END IF;
 SELECT count(*) INTO faltantes FROM public.subcontrato_ep_requisitos r
 WHERE r.empresa=ep.empresa AND r.activo AND r.obligatorio AND (r.obra_nombre IS NULL OR r.obra_nombre=ep.obra_nombre)
 AND NOT EXISTS (SELECT 1 FROM public.subcontrato_ep_documentos d WHERE d.estado_pago_id=ep.id AND d.requisito_id=r.id AND d.estado='Aprobado');
 IF faltantes>0 THEN RAISE EXCEPTION 'El expediente documental tiene % requisito(s) obligatorio(s) pendiente(s) de aprobación',faltantes; END IF;
 IF coalesce(ep.factura_folio,'')='' THEN RAISE EXCEPTION 'Debe existir una factura asociada'; END IF;
 INSERT INTO public.costos_reales_obra(obra_nombre,nombre,tipo_costo,asociar_factura,num_factura,monto,empresa,origen,origen_id) VALUES(ep.obra_nombre,'Estado de pago subcontrato · '||ep.subcontrato_nombre,'Subcontrato',true,ep.factura_folio,coalesce(ep.monto_aprobado,ep.monto_presentado),ep.empresa,'Estado de pago subcontrato',ep.id) ON CONFLICT(origen_id) DO UPDATE SET monto=excluded.monto,num_factura=excluded.num_factura RETURNING id INTO cid;
 UPDATE public.subcontrato_estados_pago SET estado='Aprobado',monto_aprobado=coalesce(monto_aprobado,monto_presentado),aprobado_por=p_aprobado_por,aprobado_at=now(),costo_real_id=cid WHERE id=ep.id;
 INSERT INTO public.subcontrato_ep_historial(estado_pago_id,accion,estado_origen,estado_destino,actor_nombre,actor_empresa) VALUES(ep.id,'Estado de pago aprobado',ep.estado,'Aprobado',p_aprobado_por,ep.empresa);
 RETURN cid;
END $$;
REVOKE ALL ON FUNCTION public.aprobar_ep_subcontrato_y_cargar_costo(BIGINT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.aprobar_ep_subcontrato_y_cargar_costo(BIGINT,TEXT) TO authenticated;

-- Endurecimiento final: el historial queda inmutable para el cliente y cada
-- mutación documental exige el permiso granular correspondiente.
DROP POLICY IF EXISTS ep_requisitos_empresa ON public.subcontrato_ep_requisitos;
DROP POLICY IF EXISTS ep_documentos_empresa ON public.subcontrato_ep_documentos;
DROP POLICY IF EXISTS ep_historial_empresa ON public.subcontrato_ep_historial;
DROP POLICY IF EXISTS ep_archivos_update ON storage.objects;
REVOKE ALL ON public.subcontrato_ep_requisitos, public.subcontrato_ep_documentos, public.subcontrato_ep_historial FROM authenticated;

CREATE POLICY ep_req_select ON public.subcontrato_ep_requisitos FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=(SELECT auth.uid()) AND (u.empresa=subcontrato_ep_requisitos.empresa OR lower(u.empresa)='obraxis')));
CREATE POLICY ep_req_insert ON public.subcontrato_ep_requisitos FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=(SELECT auth.uid()) AND (u.empresa=subcontrato_ep_requisitos.empresa OR lower(u.empresa)='obraxis') AND (lower(coalesce(u.rol_base,'')) IN ('administrador','admin','superadmin','superusuario') OR coalesce(u.permisos,'{}'::jsonb) ? 'obras.subcontratos.configurar')));
CREATE POLICY ep_req_update ON public.subcontrato_ep_requisitos FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=(SELECT auth.uid()) AND (u.empresa=subcontrato_ep_requisitos.empresa OR lower(u.empresa)='obraxis') AND (lower(coalesce(u.rol_base,'')) IN ('administrador','admin','superadmin','superusuario') OR coalesce(u.permisos,'{}'::jsonb) ? 'obras.subcontratos.configurar'))) WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=(SELECT auth.uid()) AND (u.empresa=subcontrato_ep_requisitos.empresa OR lower(u.empresa)='obraxis')));
CREATE POLICY ep_req_delete ON public.subcontrato_ep_requisitos FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id=(SELECT auth.uid()) AND (u.empresa=subcontrato_ep_requisitos.empresa OR lower(u.empresa)='obraxis') AND (lower(coalesce(u.rol_base,'')) IN ('administrador','admin','superadmin','superusuario') OR coalesce(u.permisos,'{}'::jsonb) ? 'obras.subcontratos.configurar')));

CREATE POLICY ep_doc_select ON public.subcontrato_ep_documentos FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.subcontrato_estados_pago ep JOIN public.usuarios u ON u.auth_user_id=(SELECT auth.uid()) WHERE ep.id=subcontrato_ep_documentos.estado_pago_id AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis')));
CREATE POLICY ep_doc_insert ON public.subcontrato_ep_documentos FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.subcontrato_estados_pago ep JOIN public.usuarios u ON u.auth_user_id=(SELECT auth.uid()) WHERE ep.id=subcontrato_ep_documentos.estado_pago_id AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis') AND (lower(coalesce(u.rol_base,'')) IN ('administrador','admin','superadmin','superusuario') OR coalesce(u.permisos,'{}'::jsonb) ?| ARRAY['obras.subcontratos.crear','obras.subcontratos.editar'])));
CREATE POLICY ep_doc_update ON public.subcontrato_ep_documentos FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.subcontrato_estados_pago ep JOIN public.usuarios u ON u.auth_user_id=(SELECT auth.uid()) WHERE ep.id=subcontrato_ep_documentos.estado_pago_id AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis') AND (lower(coalesce(u.rol_base,'')) IN ('administrador','admin','superadmin','superusuario') OR coalesce(u.permisos,'{}'::jsonb) ?| ARRAY['obras.subcontratos.editar','obras.subcontratos.revisar']))) WITH CHECK (EXISTS (SELECT 1 FROM public.subcontrato_estados_pago ep JOIN public.usuarios u ON u.auth_user_id=(SELECT auth.uid()) WHERE ep.id=subcontrato_ep_documentos.estado_pago_id AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis')));
CREATE POLICY ep_hist_select ON public.subcontrato_ep_historial FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.subcontrato_estados_pago ep JOIN public.usuarios u ON u.auth_user_id=(SELECT auth.uid()) WHERE ep.id=subcontrato_ep_historial.estado_pago_id AND (u.empresa=ep.empresa OR lower(u.empresa)='obraxis')));

GRANT SELECT,INSERT,UPDATE,DELETE ON public.subcontrato_ep_requisitos TO authenticated;
GRANT SELECT,INSERT,UPDATE ON public.subcontrato_ep_documentos TO authenticated;
GRANT SELECT ON public.subcontrato_ep_historial TO authenticated;

CREATE OR REPLACE FUNCTION public.revisar_documento_ep_subcontrato(p_documento_id BIGINT,p_estado TEXT,p_observacion TEXT DEFAULT NULL) RETURNS TEXT LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE d public.subcontrato_ep_documentos; ep public.subcontrato_estados_pago; u public.usuarios; faltantes INTEGER; nuevo_estado TEXT;
BEGIN
 IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Sesión no autenticada'; END IF;
 IF p_estado NOT IN ('Aprobado','Observado','Rechazado') THEN RAISE EXCEPTION 'Estado de revisión no válido'; END IF;
 SELECT * INTO d FROM public.subcontrato_ep_documentos WHERE id=p_documento_id FOR UPDATE;
 SELECT * INTO ep FROM public.subcontrato_estados_pago WHERE id=d.estado_pago_id;
 SELECT * INTO u FROM public.usuarios WHERE auth_user_id=auth.uid() AND (empresa=ep.empresa OR lower(empresa)='obraxis') LIMIT 1;
 IF u.id IS NULL OR NOT (lower(coalesce(u.rol_base,'')) IN ('administrador','admin','superadmin','superusuario') OR coalesce(u.permisos,'{}'::jsonb) ? 'obras.subcontratos.revisar') THEN RAISE EXCEPTION 'Tu rol no tiene permiso para revisar documentos'; END IF;
 IF p_estado IN ('Observado','Rechazado') AND nullif(trim(coalesce(p_observacion,'')),'') IS NULL THEN RAISE EXCEPTION 'La observación es obligatoria'; END IF;
 UPDATE public.subcontrato_ep_documentos SET estado=p_estado,observacion_revision=nullif(trim(coalesce(p_observacion,'')),''),revisado_por=coalesce(u.nombre,u.usuario,u.correo),revisado_at=now(),updated_at=now() WHERE id=d.id;
 INSERT INTO public.subcontrato_ep_historial(estado_pago_id,documento_id,accion,estado_origen,estado_destino,detalle,actor_nombre,actor_rut,actor_cargo,actor_empresa) VALUES(ep.id,d.id,'Documento '||lower(p_estado),d.estado,p_estado,p_observacion,coalesce(u.nombre,u.usuario,u.correo),u.trabajador_rut,u.cargo,u.empresa);
 SELECT count(*) INTO faltantes FROM public.subcontrato_ep_requisitos r WHERE r.empresa=ep.empresa AND r.activo AND r.obligatorio AND (r.obra_nombre IS NULL OR r.obra_nombre=ep.obra_nombre) AND NOT EXISTS(SELECT 1 FROM public.subcontrato_ep_documentos x WHERE x.estado_pago_id=ep.id AND x.requisito_id=r.id AND x.estado='Aprobado');
 nuevo_estado:=CASE WHEN faltantes=0 THEN 'Expediente aprobado' WHEN p_estado IN ('Observado','Rechazado') THEN 'Documentación observada' ELSE 'Documentación en revisión' END;
 UPDATE public.subcontrato_estados_pago SET estado=nuevo_estado WHERE id=ep.id AND estado<>'Aprobado'; RETURN nuevo_estado;
END $$;
REVOKE ALL ON FUNCTION public.revisar_documento_ep_subcontrato(BIGINT,TEXT,TEXT) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.revisar_documento_ep_subcontrato(BIGINT,TEXT,TEXT) TO authenticated;
REVOKE ALL ON FUNCTION public.aprobar_ep_subcontrato_y_cargar_costo(BIGINT,TEXT) FROM PUBLIC,anon;

CREATE INDEX IF NOT EXISTS idx_sub_ep_docs_ep ON public.subcontrato_ep_documentos(estado_pago_id);
CREATE INDEX IF NOT EXISTS idx_sub_ep_docs_req ON public.subcontrato_ep_documentos(requisito_id);
CREATE INDEX IF NOT EXISTS idx_sub_ep_hist_ep ON public.subcontrato_ep_historial(estado_pago_id);
CREATE INDEX IF NOT EXISTS idx_sub_ep_hist_doc ON public.subcontrato_ep_historial(documento_id);
