-- Eventos inmutables que alimentan la línea de tiempo de la Bitácora de cada obra.
CREATE TABLE IF NOT EXISTS bitacora_eventos_obra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT NOT NULL,
  obra_nombre TEXT NOT NULL,
  categoria TEXT NOT NULL CHECK (categoria IN ('Estados de Pago', 'Calidad', 'Prevención')),
  accion TEXT NOT NULL,
  detalle TEXT,
  actor TEXT NOT NULL DEFAULT 'Sistema',
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS bitacora_eventos_obra_fecha_idx ON bitacora_eventos_obra (empresa, obra_nombre, fecha, created_at);
ALTER TABLE bitacora_eventos_obra ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow_All_Operations_Anon_Authenticated" ON bitacora_eventos_obra;
CREATE POLICY "Allow_All_Operations_Anon_Authenticated" ON bitacora_eventos_obra FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
GRANT ALL ON bitacora_eventos_obra TO anon, authenticated;
GRANT ALL ON SEQUENCE bitacora_eventos_obra_id_seq TO anon, authenticated;
