import React,{useEffect,useState}from'react';
import{AlertTriangle,Bot,CheckCircle2,ChevronDown,ChevronUp,Loader2,ShieldAlert}from'lucide-react';
import{supabase}from'../supabaseClient';

const tone={Conforme:'border-emerald-200 bg-emerald-50 text-emerald-900',Observado:'border-amber-200 bg-amber-50 text-amber-950','Requiere revisión':'border-rose-200 bg-rose-50 text-rose-950'};
const cleanBase64=value=>String(value||'').includes(',')?String(value).split(',')[1]:String(value||'');
const mimeFrom=file=>file?.type||String(file?.base64||'').match(/^data:([^;]+);/)?.[1]||'application/pdf';

export default function AccreditationAIReview({file,empresa,obra,subcontratista,categoria='empresa',entidad,documentKey,documentName,canDecide=false,user}){
 const[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[result,setResult]=useState(null),[error,setError]=useState('');
 useEffect(()=>{setResult(null);setError('');setOpen(false)},[file?.base64,documentKey,entidad]);
 const run=async()=>{setBusy(true);setError('');try{const{data,error:invokeError}=await supabase.functions.invoke('revisar-acreditacion-ia',{body:{file_base64:cleanBase64(file?.base64),mime_type:mimeFrom(file),file_name:file?.fileName||file?.name||documentName,empresa,obra_nombre:obra,subcontratista_nombre:subcontratista?.empresa_nombre,subcontratista_rut:subcontratista?.rut_empresa,categoria,entidad_nombre:entidad,documento_clave:documentKey,documento_nombre:documentName}});if(invokeError)throw invokeError;if(data?.error)throw new Error(data.error);setResult(data.data);setOpen(true)}catch(e){setError(e.message||'No fue posible ejecutar la revisión.')}finally{setBusy(false)}};
 const decide=async decision=>{const comment=decision==='Aprobado'?'Revisión humana conforme':window.prompt(`Comentario para ${decision.toLowerCase()}:`);if(comment===null)return;const actor=user?.nombre||user?.usuario||user?.correo||'Revisor autorizado';const{data,error:updateError}=await supabase.from('acreditaciones_revisiones_ia').update({decision_humana:decision,decision_comentario:comment,decision_por:actor,decision_en:new Date().toISOString()}).eq('id',result.id).select().single();if(updateError)return setError(updateError.message);setResult(data)};
 return <div className="space-y-2"><button type="button" onClick={run} disabled={busy||!file?.base64} className="flex w-full items-center justify-center gap-1.5 rounded-lg border border-violet-200 bg-violet-50 px-2 py-1.5 text-[10px] font-black text-violet-800 hover:bg-violet-100 disabled:opacity-40">{busy?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Bot className="h-3.5 w-3.5"/>}{busy?'Revisando…':result?'Revisar nuevamente con IA':'Revisión documental IA'}</button>{error&&<p className="rounded-lg bg-rose-50 p-2 text-[9px] font-bold text-rose-800">{error}</p>}{result&&<div className={`rounded-xl border p-2.5 text-[10px] ${tone[result.resultado]||tone['Requiere revisión']}`}><button type="button" onClick={()=>setOpen(!open)} className="flex w-full items-center justify-between gap-2 text-left"><span className="flex items-center gap-1.5 font-black">{result.resultado==='Conforme'?<CheckCircle2 className="h-3.5 w-3.5"/>:<ShieldAlert className="h-3.5 w-3.5"/>}{result.resultado} · {Number(result.confianza||0).toFixed(0)}%</span>{open?<ChevronUp className="h-3.5 w-3.5"/>:<ChevronDown className="h-3.5 w-3.5"/>}</button>{open&&<div className="mt-2 space-y-2 border-t border-current/15 pt-2"><p>{result.resumen}</p>{(result.hallazgos||[]).map((h,i)=><div key={i} className="rounded-lg bg-white/70 p-2"><p className="font-black">{h.severidad} · {h.categoria}</p><p>{h.detalle}</p>{h.evidencia&&<p className="mt-1 opacity-75">Evidencia: {h.evidencia}</p>}<p className="mt-1 font-bold">Acción: {h.recomendacion}</p></div>)}{Boolean(result.campos_faltantes?.length)&&<p><AlertTriangle className="mr-1 inline h-3 w-3"/><b>Falta comprobar:</b> {result.campos_faltantes.join(' · ')}</p>}<p className="font-bold">{result.recomendacion}</p>{result.decision_humana?<p className="rounded-lg bg-white p-2 font-black">Decisión humana: {result.decision_humana} · {result.decision_por}</p>:canDecide&&<div className="grid grid-cols-3 gap-1"><button onClick={()=>decide('Aprobado')} className="rounded bg-emerald-700 py-1 text-white">Aprobar</button><button onClick={()=>decide('Observado')} className="rounded bg-amber-600 py-1 text-white">Observar</button><button onClick={()=>decide('Rechazado')} className="rounded bg-rose-700 py-1 text-white">Rechazar</button></div>}<p className="border-t border-current/15 pt-2 opacity-75">La IA no acredita ni aprueba. La decisión permanece en el revisor autorizado.</p></div>}</div>}</div>;
}
