import React,{useCallback,useEffect,useMemo,useState}from'react';
import{AlertTriangle,Bot,Building2,CheckCircle2,CircleDollarSign,Database,Loader2,LockKeyhole,RefreshCw,Save,ShieldCheck,Users,Workflow}from'lucide-react';
import{supabase}from'../supabaseClient';

const DEFAULT_FEATURES={lectura_documental:true,maquinaria:false,rrhh:false,informes:false,copiloto:false,revision_legal:false,asistencia_planificacion:false,asistencia_calidad:false,asistencia_prevencion:false,asistencia_maquinaria:false,asistencia_rrhh:false};
const FEATURES=[
 ['lectura_documental','Lectura documental','Boletas, facturas, guías y acreditaciones.'],
 ['maquinaria','IA para maquinaria','Lectura de medidores, anomalías y apoyo de mantenimiento.'],
 ['rrhh','IA para Recursos Humanos','Lectura documental y alertas de dotación, vigencias y asistencia.'],
 ['informes','Informes asistidos','Interpretación ejecutiva de indicadores reales.'],
 ['copiloto','OX por obra','Asistente contextual con consultas trazables sobre información autorizada.'],
 ['revision_legal','Revisión legal asistida','Contraste documental con reglas y normativa versionada.'],
 ['asistencia_planificacion','Asistencia de planificación','Interpreta restricciones y recursos de Last Planner; nunca libera compromisos.'],
 ['asistencia_calidad','Asistencia de calidad','Resume recurrencias y propone borradores de causa y acción para revisión profesional.'],
 ['asistencia_prevencion','Asistencia de prevención','Sugiere controles y análisis preventivos sin clasificar ni cerrar eventos automáticamente.'],
 ['asistencia_maquinaria','Asistencia de maquinaria','Sintetiza fallas y propone redistribución sin alterar equipos ni mantenciones.'],
 ['asistencia_rrhh','Asistencia de Recursos Humanos','Explica brechas usando dotación agregada, sin enviar RUT ni datos personales.']
];
const usd=value=>`US$ ${Number(value||0).toFixed(2)}`;
const numberOrBlank=value=>value===''?'':Number(value);

export default function AIControlCenter({user}){
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[message,setMessage]=useState(''),[companies,setCompanies]=useState([]),[configs,setConfigs]=useState([]),[usage,setUsage]=useState([]),[roles,setRoles]=useState([]),[users,setUsers]=useState([]),[selected,setSelected]=useState('');
 const load=useCallback(async()=>{
  setLoading(true);setMessage('');const start=new Date();start.setUTCDate(1);start.setUTCHours(0,0,0,0);
  const[cfg,cfgs,uses,roleRows,userRows]=await Promise.all([
   supabase.from('config_empresa').select('empresa').order('empresa'),
   supabase.from('ia_config_empresas').select('*').order('empresa'),
   supabase.from('ia_consumos').select('empresa,funcion,modelo,estado,tokens_total,costo_usd,usuario,auth_user_id,duracion_ms,created_at').gte('created_at',start.toISOString()).order('created_at',{ascending:false}).limit(1000),
   supabase.from('roles').select('id,nombre,empresa,archivado').eq('archivado',false).order('nombre'),
   supabase.from('usuarios').select('id,auth_user_id,usuario,nombre,correo,rol,rol_base,empresa').order('nombre')
  ]);
  const error=cfg.error||cfgs.error||uses.error||roleRows.error||userRows.error;
  if(error)setMessage(`No fue posible cargar el Centro de IA: ${error.message}`);else{
   const names=Array.from(new Set((cfg.data||[]).map(x=>x.empresa).filter(Boolean)));
   setCompanies(names);setConfigs(cfgs.data||[]);setUsage(uses.data||[]);setRoles(roleRows.data||[]);setUsers(userRows.data||[]);setSelected(current=>current||names[0]||user?.empresa||'');
  }setLoading(false);
 },[]);
 useEffect(()=>{load()},[load]);
 const current=useMemo(()=>configs.find(x=>x.empresa===selected)||{empresa:selected,habilitada:false,presupuesto_mensual_usd:10,bloquear_al_limite:true,alerta_porcentaje:80,modelo:'gpt-4.1-mini',funciones:DEFAULT_FEATURES,limites_funcion:{},limites_usuario:{}},[configs,selected]);
 const companyUsage=usage.filter(x=>x.empresa===selected&&['Reservado','Completado'].includes(x.estado));
 const companyRoles=roles.filter(x=>x.empresa===selected);
 const companyUsers=users.filter(x=>x.empresa===selected&&x.auth_user_id);
 const spent=companyUsage.reduce((sum,x)=>sum+Number(x.costo_usd||0),0),tokens=companyUsage.reduce((sum,x)=>sum+Number(x.tokens_total||0),0);
 const percent=current.presupuesto_mensual_usd>0?Math.min(100,(spent/Number(current.presupuesto_mensual_usd))*100):0;
 const patch=values=>setConfigs(list=>list.some(x=>x.empresa===selected)?list.map(x=>x.empresa===selected?{...x,...values}:x):[...list,{...current,...values}]);
 const patchFeatureLimit=(key,values)=>patch({limites_funcion:{...(current.limites_funcion||{}),[key]:{...(current.limites_funcion?.[key]||{}),...values}}});
 const patchUserLimit=(authId,values)=>patch({limites_usuario:{...(current.limites_usuario||{}),[authId]:{habilitado:true,...(current.limites_usuario?.[authId]||{}),...values}}});
 const save=async()=>{if(!selected)return;setSaving(selected);setMessage('');const payload={...current,empresa:selected,funciones:{...DEFAULT_FEATURES,...current.funciones},limites_funcion:current.limites_funcion||{},limites_usuario:current.limites_usuario||{},actualizado_por:user?.usuario||user?.correo||'Obraxis',updated_at:new Date().toISOString()};delete payload.created_at;const{error}=await supabase.from('ia_config_empresas').upsert(payload,{onConflict:'empresa'});setMessage(error?`No fue posible guardar: ${error.message}`:'Gobierno de IA guardado y aplicado para la empresa.');if(!error)await load();setSaving('')};
 if(loading)return <div className="flex min-h-56 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-violet-700"/></div>;
 return <div className="space-y-5">
  <div className="rounded-2xl border border-violet-200 bg-gradient-to-r from-violet-950 to-indigo-900 p-5 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-xl bg-white/10 p-3"><Bot className="h-6 w-6 text-violet-200"/></span><div><h4 className="text-base font-black">Centro de IA</h4><p className="mt-1 text-xs text-violet-100">Gobierno, presupuesto, permisos y consumo auditable por empresa.</p></div></div><button type="button" onClick={load} className="flex items-center gap-2 rounded-xl border border-white/20 px-3 py-2 text-xs font-bold hover:bg-white/10"><RefreshCw className="h-4 w-4"/>Actualizar consumo</button></div></div>
  {message&&<p className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs font-bold text-blue-900">{message}</p>}
  <div className="grid gap-4 xl:grid-cols-[260px_minmax(0,1fr)]">
   <aside className="h-fit rounded-2xl border bg-white p-2">{companies.map(name=><button key={name} type="button" onClick={()=>setSelected(name)} className={`mb-1 flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-xs font-bold ${selected===name?'bg-violet-700 text-white':'text-slate-600 hover:bg-slate-50'}`}><Building2 className="h-4 w-4"/><span className="truncate">{name}</span></button>)}</aside>
   <section className="space-y-4">
    <div className="grid gap-3 sm:grid-cols-3"><Stat icon={CircleDollarSign} label="Consumo del mes" value={usd(spent)}/><Stat icon={ShieldCheck} label="Presupuesto" value={usd(current.presupuesto_mensual_usd)}/><Stat icon={Workflow} label="Tokens procesados" value={tokens.toLocaleString('es-CL')}/></div>
    <div className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><div><h5 className="font-black text-slate-900">{selected}</h5><p className="text-xs text-slate-500">{companyUsage.length} operaciones registradas este mes</p></div><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={Boolean(current.habilitada)} onChange={e=>patch({habilitada:e.target.checked})} className="h-5 w-5 accent-violet-700"/>IA habilitada</label></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`${percent>=100?'bg-rose-600':percent>=current.alerta_porcentaje?'bg-amber-500':'bg-emerald-600'} h-full rounded-full transition-all`} style={{width:`${percent}%`}}/></div><p className="mt-1 text-right text-[10px] font-bold text-slate-500">{percent.toFixed(1)}% utilizado</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Field label="Presupuesto mensual (USD)" type="number" value={current.presupuesto_mensual_usd} onChange={v=>patch({presupuesto_mensual_usd:Number(v)})}/><Field label="Alerta al (%)" type="number" value={current.alerta_porcentaje} onChange={v=>patch({alerta_porcentaje:Number(v)})}/><Field label="Modelo autorizado" value={current.modelo} onChange={v=>patch({modelo:v})}/></div><label className="mt-4 flex items-center gap-2 rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-900"><input type="checkbox" checked={Boolean(current.bloquear_al_limite)} onChange={e=>patch({bloquear_al_limite:e.target.checked})} className="h-4 w-4 accent-rose-700"/>Bloquear nuevas operaciones al alcanzar el presupuesto</label></div>
    <div className="rounded-2xl border bg-white p-5"><h5 className="font-black">Funciones, límites y roles autorizados</h5><p className="mt-1 text-xs text-slate-500">Un valor vacío significa que solo aplica el presupuesto general. Sin roles seleccionados, pueden usarla todos los roles con acceso al módulo.</p><div className="mt-4 space-y-3">{FEATURES.map(([key,label,description])=>{const limit=current.limites_funcion?.[key]||{},allowed=limit.roles_autorizados||[];return <div key={key} className="rounded-2xl border p-4"><label className="flex cursor-pointer items-start gap-3"><input type="checkbox" checked={Boolean(current.funciones?.[key])} onChange={e=>patch({funciones:{...DEFAULT_FEATURES,...current.funciones,[key]:e.target.checked}})} className="mt-0.5 h-4 w-4 accent-violet-700"/><span><b className="block text-xs">{label}</b><span className="mt-1 block text-[10px] text-slate-500">{description}</span></span></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Presupuesto función / mes (USD)" type="number" value={limit.presupuesto_mensual_usd??''} onChange={v=>patchFeatureLimit(key,{presupuesto_mensual_usd:numberOrBlank(v)})}/><Field label="Máx. ejecuciones por usuario / mes" type="number" value={limit.max_ejecuciones_usuario_mes??''} onChange={v=>patchFeatureLimit(key,{max_ejecuciones_usuario_mes:numberOrBlank(v)})}/></div><div className="mt-3"><p className="text-[10px] font-black uppercase text-slate-500">Roles autorizados</p><div className="mt-2 flex flex-wrap gap-2">{companyRoles.length?companyRoles.map(role=><label key={role.id} className={`cursor-pointer rounded-full border px-3 py-1.5 text-[10px] font-bold ${allowed.includes(role.nombre)?'border-violet-300 bg-violet-50 text-violet-800':'text-slate-500'}`}><input type="checkbox" className="sr-only" checked={allowed.includes(role.nombre)} onChange={e=>patchFeatureLimit(key,{roles_autorizados:e.target.checked?[...allowed,role.nombre]:allowed.filter(x=>x!==role.nombre)})}/>{role.nombre}</label>):<span className="text-[10px] text-slate-400">No hay roles configurados para esta empresa.</span>}</div></div></div>})}</div></div>
    <div className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-violet-700"/><h5 className="font-black">Excepciones y límites por usuario</h5></div><p className="mt-1 text-xs text-slate-500">Solo aparecen usuarios vinculados a Supabase Auth. El control se valida nuevamente en el servidor antes de cada ejecución.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="border-b text-[10px] uppercase text-slate-500"><tr><th className="p-2">Usuario</th><th className="p-2">Rol</th><th className="p-2">Habilitado</th><th className="p-2">Presupuesto / mes</th><th className="p-2">Máx. ejecuciones</th></tr></thead><tbody>{companyUsers.map(item=>{const limit=current.limites_usuario?.[item.auth_user_id]||{};return <tr key={item.auth_user_id} className="border-b last:border-0"><td className="p-2"><b>{item.nombre||item.usuario}</b><span className="block text-[10px] text-slate-400">{item.usuario||item.correo}</span></td><td className="p-2">{item.rol||item.rol_base||'Sin rol'}</td><td className="p-2"><input type="checkbox" checked={limit.habilitado!==false} onChange={e=>patchUserLimit(item.auth_user_id,{habilitado:e.target.checked})} className="h-4 w-4 accent-violet-700"/></td><td className="p-2"><MiniNumber value={limit.presupuesto_mensual_usd??''} onChange={v=>patchUserLimit(item.auth_user_id,{presupuesto_mensual_usd:numberOrBlank(v)})}/></td><td className="p-2"><MiniNumber value={limit.max_ejecuciones_mes??''} onChange={v=>patchUserLimit(item.auth_user_id,{max_ejecuciones_mes:numberOrBlank(v)})}/></td></tr>})}</tbody></table>{!companyUsers.length&&<p className="p-4 text-center text-xs text-slate-400">No hay usuarios autenticados configurables.</p>}</div></div>
    <AIReadinessPanel company={selected}/>
    <div className="rounded-2xl border bg-white p-5"><h5 className="font-black">Últimas ejecuciones auditadas</h5><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="border-b text-[10px] uppercase text-slate-500"><tr><th className="p-2">Fecha</th><th className="p-2">Solicitante</th><th className="p-2">Función</th><th className="p-2">Resultado</th><th className="p-2">Tokens</th><th className="p-2">Costo</th></tr></thead><tbody>{usage.filter(x=>x.empresa===selected).slice(0,12).map((row,index)=><tr key={`${row.created_at}-${index}`} className="border-b last:border-0"><td className="p-2">{new Date(row.created_at).toLocaleString('es-CL')}</td><td className="p-2">{row.usuario||'No informado'}</td><td className="p-2">{row.funcion}</td><td className="p-2">{row.estado}</td><td className="p-2">{Number(row.tokens_total||0).toLocaleString('es-CL')}</td><td className="p-2">{usd(row.costo_usd)}</td></tr>)}</tbody></table></div></div>
    <div className="flex justify-end"><button type="button" onClick={save} disabled={Boolean(saving)} className="flex items-center gap-2 rounded-xl bg-violet-700 px-5 py-3 text-xs font-black text-white disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Guardar gobierno de IA</button></div>
   </section>
  </div>
 </div>;
}
function Stat({icon:Icon,label,value}){return <div className="rounded-2xl border bg-white p-4"><Icon className="h-4 w-4 text-violet-700"/><p className="mt-3 text-[10px] font-black uppercase text-slate-500">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div>}
function Field({label,value,onChange,type='text'}){return <label><span className="mb-1 block text-[10px] font-black uppercase text-slate-500">{label}</span><input type={type} min={type==='number'?0:undefined} value={value??''} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-xl border border-slate-200 px-3 text-xs font-bold outline-none focus:border-violet-600"/></label>}
function MiniNumber({value,onChange}){return <input type="number" min="0" value={value} onChange={e=>onChange(e.target.value)} placeholder="Sin límite" className="h-9 w-32 rounded-lg border border-slate-200 px-2 text-xs outline-none focus:border-violet-600"/>}
function AIReadinessPanel({company}){
 const[loading,setLoading]=useState(false),[domains,setDomains]=useState([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;const run=async()=>{if(!company)return;setLoading(true);setError('');
  const works=await supabase.from('obras').select('nombre,estado').eq('empresa',company);if(works.error){if(active){setError(works.error.message);setLoading(false)}return}
  const names=(works.data||[]).map(x=>x.nombre).filter(Boolean),completed=(works.data||[]).filter(x=>['terminada','finalizada','cerrada','inactiva'].includes(String(x.estado||'').toLowerCase())).length;
  const safeIn=(table,column,dateColumn,companyColumn=true)=>{let query=supabase.from(table).select(dateColumn);if(companyColumn)query=query.eq('empresa',company);else if(names.length)query=query.in(column,names);else return Promise.resolve({data:[],error:null});return query.order(dateColumn,{ascending:true}).limit(2000)};
  const[adv,cost,quality,failures,use,validations]=await Promise.all([safeIn('avances_produccion_partidas','obra_nombre','created_at'),safeIn('costos_reales_obra','obra_nombre','created_at'),safeIn('calidad_no_conformidades','obra_nombre','created_at'),safeIn('maquinaria_fallas','obra_nombre','fecha'),safeIn('maquinaria_uso_diario','obra_nombre','fecha'),supabase.from('predicciones_obra_historial').select('error_plazo_dias,error_costo_pct,estado_validacion').eq('empresa',company).eq('estado_validacion','Validada')]);
  const span=rows=>{const dates=(rows||[]).map(x=>new Date(x.created_at||x.fecha)).filter(x=>!Number.isNaN(x.getTime())).sort((a,b)=>a-b);return dates.length>1?Math.round((dates.at(-1)-dates[0])/86400000):0};
  const validated=validations.data||[],mean=value=>validated.length?validated.reduce((sum,row)=>sum+Math.abs(Number(row[value]||0)),0)/validated.length:0;
  const result=[
   {name:'Plazo y término',count:adv.data?.length||0,days:span(adv.data),ready:!adv.error&&(adv.data?.length||0)>=24&&span(adv.data)>=84,need:'24 reportes y 12 semanas de continuidad',sourceError:adv.error?.message},
   {name:'Costo final y sobrecosto',count:cost.data?.length||0,days:span(cost.data),ready:!cost.error&&(cost.data?.length||0)>=24&&span(cost.data)>=84,need:'24 movimientos y 12 semanas de historia',sourceError:cost.error?.message},
   {name:'Calidad y no conformidades',count:quality.data?.length||0,days:span(quality.data),ready:!quality.error&&(quality.data?.length||0)>=20&&span(quality.data)>=90,need:'20 registros y 90 días de seguimiento',sourceError:quality.error?.message},
   {name:'Utilización y fallas de equipos',count:(failures.data?.length||0)+(use.data?.length||0),days:Math.max(span(failures.data),span(use.data)),ready:!failures.error&&!use.error&&((failures.data?.length||0)+(use.data?.length||0))>=30&&Math.max(span(failures.data),span(use.data))>=90,need:'30 lecturas/eventos y 90 días de continuidad',sourceError:failures.error?.message||use.error?.message},
   {name:'Comparación entre obras',count:works.data?.length||0,days:0,ready:completed>=3,need:'3 obras terminadas con datos comparables',detail:`${completed} obra(s) terminada(s)`},
   {name:'Validación retrospectiva',count:validated.length,days:0,ready:!validations.error&&validated.length>=3,need:'3 predicciones cerradas y comparadas con resultados reales',sourceError:validations.error?.message,detail:validated.length?`${validated.length} validadas · error medio ${mean('error_plazo_dias').toFixed(1)} días · ${mean('error_costo_pct').toFixed(1)}% costo`:'Sin predicciones validadas'}
  ];if(active){setDomains(result);setLoading(false)}};run();return()=>{active=false}},[company]);
 const ready=domains.filter(x=>x.ready).length,score=domains.length?Math.round(ready/domains.length*100):0;
 return <div className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="rounded-xl bg-indigo-50 p-2.5"><Database className="h-5 w-5 text-indigo-700"/></span><div><h5 className="font-black">Preparación para predicción</h5><p className="mt-1 text-xs text-slate-500">Diagnóstico determinístico de continuidad y volumen histórico. No utiliza IA ni consume tokens.</p></div></div><span className={`rounded-full px-3 py-1.5 text-xs font-black ${score===100?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-900'}`}>{score}% preparado</span></div>
  {loading?<div className="flex min-h-32 items-center justify-center"><Loader2 className="h-5 w-5 animate-spin text-indigo-700"/></div>:error?<p className="mt-4 rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-800">No fue posible evaluar la historia: {error}</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{domains.map(item=><div key={item.name} className={`rounded-xl border p-3 ${item.ready?'border-emerald-200 bg-emerald-50/60':item.sourceError?'border-rose-200 bg-rose-50/60':'border-slate-200 bg-slate-50'}`}><div className="flex items-center justify-between gap-2"><b className="text-xs">{item.name}</b>{item.ready?<CheckCircle2 className="h-4 w-4 text-emerald-700"/>:<AlertTriangle className={`h-4 w-4 ${item.sourceError?'text-rose-600':'text-amber-600'}`}/>}</div><p className="mt-2 text-[11px] text-slate-600">{item.sourceError?'Fuente no disponible para este usuario.':item.detail||`${item.count} registros · ${item.days} días de historia`}</p><p className="mt-1 text-[10px] font-bold text-slate-500">{item.sourceError?'Verificar acceso al módulo y sus políticas de lectura.':`Criterio: ${item.need}`}</p></div>)}</div>}
  <div className="mt-4 flex items-start gap-2 rounded-xl bg-slate-950 p-3 text-[11px] text-slate-200"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0 text-amber-300"/><p>Las predicciones permanecen bloqueadas hasta cumplir los criterios y aprobar una validación de calidad de datos. Alcanzar el umbral no activa funciones automáticamente.</p></div>
 </div>
}
