import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Mail, MessageSquareText, RefreshCw, Search } from 'lucide-react';
import { supabase } from '../supabaseClient';
import useUserPermissions from '../utils/useUserPermissions';
import { can, isSuperUser } from '../utils/permissionsCatalog';

const states = [['nuevo','Nuevo'],['contactado','Contactado'],['cotizacion_enviada','Cotización enviada'],['cerrado','Cerrado'],['descartado','Descartado']];
const colors = { nuevo:'bg-blue-50 text-blue-700', contactado:'bg-amber-50 text-amber-700', cotizacion_enviada:'bg-violet-50 text-violet-700', cerrado:'bg-emerald-50 text-emerald-700', descartado:'bg-slate-100 text-slate-600' };
const formatDate = value => value ? new Intl.DateTimeFormat('es-CL',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)) : '—';

export default function ContactInbox({ user }) {
  const { permissions, loading: permissionsLoading } = useUserPermissions(user);
  const allowed = user?.empresa === 'Obraxis' && (isSuperUser(user) || can(user, permissions, 'admin.contactos.ver'));
  const [rows,setRows] = useState([]), [loading,setLoading] = useState(true), [error,setError] = useState('');
  const [search,setSearch] = useState(''), [filter,setFilter] = useState('abiertos'), [selected,setSelected] = useState(null), [saving,setSaving] = useState(false);
  const load = useCallback(async () => { if(!allowed)return; setLoading(true); setError(''); const {data,error:e}=await supabase.from('contactos_publicos').select('*').order('created_at',{ascending:false}).limit(500); if(e)setError(e.message);else setRows(data||[]); setLoading(false); }, [allowed]);
  useEffect(()=>{ if(!permissionsLoading)load(); },[permissionsLoading,load]);
  const visible=useMemo(()=>rows.filter(row=>{if(filter==='abiertos'&&['cerrado','descartado'].includes(row.estado))return false;if(!['todos','abiertos'].includes(filter)&&row.estado!==filter)return false;const q=search.trim().toLowerCase();return !q||[row.nombre,row.empresa_interesada,row.correo,row.telefono,row.mensaje].some(v=>String(v||'').toLowerCase().includes(q));}),[rows,search,filter]);
  const save=async()=>{setSaving(true);setError('');const payload={estado:selected.estado,responsable_auth_user_id:selected.responsable_auth_user_id||user?.auth_user_id||null,responsable_nombre:selected.responsable_nombre||user?.nombre||user?.usuario||'',notas_internas:selected.notas_internas||''};const {data,error:e}=await supabase.from('contactos_publicos').update(payload).eq('id',selected.id).select().single();if(e)setError(e.message);else{setRows(old=>old.map(x=>x.id===data.id?data:x));setSelected(data);}setSaving(false);};
  if(permissionsLoading)return <div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">Cargando autorización…</div>;
  if(!allowed)return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm font-bold text-amber-900">Bandeja disponible sólo para usuarios autorizados de Obraxis.</div>;
  const pending=rows.filter(x=>!['cerrado','descartado'].includes(x.estado)).length;
  return <div className="space-y-4">
    <section className="rounded-3xl bg-slate-950 p-6 text-white"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-4"><span className="rounded-2xl bg-white/10 p-3"><MessageSquareText className="h-6 w-6"/></span><div><h2 className="text-xl font-black">Contactos y cotizaciones</h2><p className="mt-1 text-xs text-slate-300">Solicitudes recibidas desde obraxis.cl.</p></div></div><div className="text-right"><p className="text-2xl font-black">{pending}</p><p className="text-[10px] font-black uppercase text-slate-400">pendientes</p></div></div></section>
    <section className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar contacto, empresa o mensaje…" className="h-10 w-full rounded-xl border pl-9 pr-3 text-xs font-semibold"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} className="h-10 rounded-xl border px-3 text-xs font-bold"><option value="abiertos">Pendientes</option><option value="todos">Todos</option>{states.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button onClick={load} className="flex items-center gap-2 rounded-xl border px-3 text-xs font-bold"><RefreshCw className="h-4 w-4"/>Actualizar</button></section>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">{error}</div>}
    <section className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-slate-50 text-[10px] font-black uppercase text-slate-500"><tr><th className="px-4 py-3">Recibido</th><th className="px-4 py-3">Contacto</th><th className="px-4 py-3">Empresa</th><th className="px-4 py-3">Solicitud</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Responsable</th></tr></thead><tbody className="divide-y">{loading?<tr><td colSpan="6" className="p-10 text-center text-xs text-slate-500">Cargando…</td></tr>:visible.length===0?<tr><td colSpan="6" className="p-10 text-center text-xs text-slate-500">No hay solicitudes.</td></tr>:visible.map(row=><tr key={row.id} onClick={()=>setSelected(row)} className="cursor-pointer hover:bg-slate-50"><td className="px-4 py-3 text-xs text-slate-600">{formatDate(row.created_at)}</td><td className="px-4 py-3"><p className="text-xs font-black">{row.nombre}</p><p className="text-[10px] text-slate-500">{row.correo}</p></td><td className="px-4 py-3 text-xs font-semibold">{row.empresa_interesada||'No indicada'}</td><td className="max-w-md px-4 py-3"><p className="truncate text-xs text-slate-600">{row.mensaje}</p></td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[9px] font-black uppercase ${colors[row.estado]}`}>{states.find(x=>x[0]===row.estado)?.[1]}</span></td><td className="px-4 py-3 text-xs">{row.responsable_nombre||'Sin asignar'}</td></tr>)}</tbody></table></div></section>
    {selected&&<div className="fixed inset-0 z-[100] flex justify-end bg-slate-950/45" onClick={()=>setSelected(null)}><aside className="h-full w-full max-w-xl overflow-y-auto bg-white p-6" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase text-primary">Solicitud #{selected.id}</p><h3 className="text-xl font-black">{selected.nombre}</h3><p className="text-xs text-slate-500">{selected.empresa_interesada||'Empresa no indicada'} · {formatDate(selected.created_at)}</p></div><button onClick={()=>setSelected(null)} className="rounded-xl bg-slate-100 px-3 text-xs font-black">Cerrar</button></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="whitespace-pre-wrap text-sm text-slate-700">{selected.mensaje}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-black uppercase text-slate-500">Estado<select value={selected.estado} onChange={e=>setSelected(v=>({...v,estado:e.target.value}))} className="mt-1 h-10 w-full rounded-xl border px-3 text-xs font-bold">{states.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-[10px] font-black uppercase text-slate-500">Responsable<input value={selected.responsable_nombre||''} onChange={e=>setSelected(v=>({...v,responsable_nombre:e.target.value}))} className="mt-1 h-10 w-full rounded-xl border px-3 text-xs"/></label></div><label className="mt-4 block text-[10px] font-black uppercase text-slate-500">Notas internas<textarea rows="5" value={selected.notas_internas||''} onChange={e=>setSelected(v=>({...v,notas_internas:e.target.value}))} className="mt-1 w-full rounded-xl border p-3 text-xs"/></label><div className="mt-5 flex gap-2"><a href={`mailto:${selected.correo}?subject=${encodeURIComponent('Contacto Obraxis')}`} className="flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-black"><Mail className="h-4 w-4"/>Responder</a><button onClick={save} disabled={saving} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-black text-white"><CheckCircle2 className="h-4 w-4"/>{saving?'Guardando…':'Guardar'}</button></div></aside></div>}
  </div>;
}
