import React,{useEffect,useState}from'react';
import{Bot,Calculator,ExternalLink,History,Lightbulb,Loader2,Send,ShieldCheck,Sparkles}from'lucide-react';
import{supabase}from'../supabaseClient';

const STARTERS=['¿Cuáles son las partidas con menor avance?','¿Qué desviaciones de costo requieren atención?','Resume los principales riesgos de esta obra.','¿Cuál es el estado de calidad y prevención?'];

export default function CopilotoObra({user,obra,onNavigate}){
 const[pregunta,setPregunta]=useState(''),[answer,setAnswer]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState([]);
 const loadHistory=async()=>{if(!obra?.nombre)return;const{data}=await supabase.from('copiloto_obra_consultas').select('id,pregunta,respuesta,created_at').eq('empresa',user?.empresa).eq('obra_nombre',obra.nombre).order('created_at',{ascending:false}).limit(8);setHistory(data||[])};
 useEffect(()=>{setAnswer(null);setPregunta('');loadHistory()},[obra?.nombre]);
 const ask=async(text=pregunta)=>{const clean=String(text||'').trim();if(clean.length<4)return;setLoading(true);setError('');const{data,error:invokeError}=await supabase.functions.invoke('copiloto-obra',{body:{empresa:user?.empresa,obra_nombre:obra?.nombre,pregunta:clean}});if(invokeError||data?.error)setError(data?.error||invokeError?.message||'No fue posible consultar el Copiloto.');else{setAnswer(data.data);setPregunta('');await loadHistory()}setLoading(false)};
 return <div className="space-y-5 animate-in fade-in duration-200">
  <div className="rounded-2xl border border-violet-200 bg-gradient-to-r from-violet-950 to-indigo-900 p-5 text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="rounded-xl bg-white/10 p-3"><Bot className="h-6 w-6 text-violet-200"/></span><div><h3 className="text-base font-black">Copiloto contextual de obra</h3><p className="mt-1 max-w-2xl text-xs text-violet-100">Consulta indicadores autorizados de {obra?.nombre}. Responde con hechos trazables, cálculos visibles y sugerencias separadas.</p></div></div><span className="flex items-center gap-1.5 rounded-full border border-emerald-300/30 bg-emerald-400/10 px-3 py-1.5 text-[10px] font-black uppercase"><ShieldCheck className="h-3.5 w-3.5"/>Solo lectura</span></div></div>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]">
   <section className="space-y-4"><div className="rounded-2xl border bg-white p-5"><label className="text-xs font-black text-slate-900">¿Qué necesitas analizar?</label><div className="mt-3 flex gap-2"><textarea value={pregunta} onChange={e=>setPregunta(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}}} maxLength={1000} rows={3} placeholder="Ej.: ¿Cuáles son las partidas con mayor riesgo de atraso?" className="min-h-24 flex-1 resize-none rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-violet-600"/><button type="button" onClick={()=>ask()} disabled={loading||pregunta.trim().length<4} className="self-end rounded-xl bg-violet-700 p-3 text-white disabled:opacity-40">{loading?<Loader2 className="h-5 w-5 animate-spin"/>:<Send className="h-5 w-5"/>}</button></div><div className="mt-3 flex flex-wrap gap-2">{STARTERS.map(item=><button key={item} type="button" onClick={()=>ask(item)} disabled={loading} className="rounded-full border border-violet-200 bg-violet-50 px-3 py-1.5 text-[10px] font-bold text-violet-800 hover:bg-violet-100">{item}</button>)}</div></div>
   {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-xs font-bold text-rose-800">{error}</div>}
   {loading&&<div className="flex min-h-48 items-center justify-center rounded-2xl border bg-white"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-violet-700"/><p className="mt-2 text-xs font-bold text-slate-500">Analizando datos autorizados de la obra…</p></div></div>}
   {!loading&&answer&&<Answer data={answer} onNavigate={onNavigate}/>} {!loading&&!answer&&!error&&<div className="rounded-2xl border border-dashed bg-white p-10 text-center"><Sparkles className="mx-auto h-8 w-8 text-violet-300"/><p className="mt-3 text-sm font-black text-slate-700">El Copiloto está listo</p><p className="mt-1 text-xs text-slate-500">Las consultas rápidas se calculan sin tokens. Las preguntas abiertas usan IA solo si la empresa la tiene habilitada.</p></div>}
   </section>
   <aside className="h-fit rounded-2xl border bg-white p-4"><div className="flex items-center gap-2"><History className="h-4 w-4 text-violet-700"/><h4 className="text-xs font-black">Consultas recientes</h4></div><div className="mt-3 space-y-2">{history.map(item=><button key={item.id} type="button" onClick={()=>setAnswer(item.respuesta)} className="w-full rounded-xl border p-3 text-left hover:border-violet-300"><p className="line-clamp-2 text-xs font-bold text-slate-700">{item.pregunta}</p><p className="mt-1 text-[9px] text-slate-400">{new Date(item.created_at).toLocaleString('es-CL')}</p></button>)}{!history.length&&<p className="rounded-xl bg-slate-50 p-3 text-xs text-slate-400">Aún no hay consultas en esta obra.</p>}</div></aside>
  </div>
 </div>;
}

function Answer({data,onNavigate}){return <div className="space-y-4"><div className="rounded-2xl border border-violet-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-[10px] font-black uppercase tracking-wider text-violet-700">Respuesta breve</p><span className={`rounded-full px-2 py-1 text-[9px] font-black ${data.meta?.generado_con_ia?'bg-violet-100 text-violet-800':'bg-emerald-100 text-emerald-800'}`}>{data.meta?.generado_con_ia?'Generado con IA':'Cálculo sin IA · 0 tokens'}</span></div><p className="mt-2 text-sm font-bold leading-relaxed text-slate-800">{data.respuesta_breve}</p></div><Section icon={ExternalLink} title="Hechos trazables" tone="blue">{(data.hechos||[]).map((item,index)=><div key={index} className="rounded-xl border bg-white p-3"><p className="text-xs text-slate-700">{item.texto}</p><div className="mt-2 flex flex-wrap items-center justify-between gap-2"><p className="text-[9px] font-black uppercase text-blue-700">{item.modulo} · {item.referencia}</p>{item.destino&&<button type="button" onClick={()=>onNavigate?.(item.destino,item)} className="rounded-lg border border-blue-200 bg-blue-50 px-2 py-1 text-[9px] font-black text-blue-800 hover:bg-blue-100">Abrir registro</button>}</div></div>)}</Section><Section icon={Calculator} title="Cálculos" tone="emerald">{(data.calculos||[]).map((item,index)=><div key={index} className="rounded-xl border bg-white p-3"><div className="flex justify-between gap-3"><b className="text-xs">{item.nombre}</b><span className="text-xs font-black text-emerald-700">{item.valor}</span></div><p className="mt-1 text-[10px] text-slate-500">Base: {item.base}</p></div>)}</Section><Section icon={Lightbulb} title="Sugerencias profesionales" tone="amber">{(data.sugerencias||[]).map((item,index)=><div key={index} className="rounded-xl border bg-white p-3"><div className="flex items-start justify-between gap-2"><b className="text-xs">{item.accion}</b><span className="rounded-full bg-amber-100 px-2 py-1 text-[9px] font-black text-amber-800">{item.prioridad}</span></div><p className="mt-1 text-[10px] text-slate-500">{item.motivo}</p></div>)}</Section>{Boolean(data.limitaciones?.length)&&<div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-[10px] font-black uppercase text-slate-500">Datos no disponibles o limitaciones</p><ul className="mt-2 list-disc space-y-1 pl-4 text-xs text-slate-600">{data.limitaciones.map((item,index)=><li key={index}>{item}</li>)}</ul></div>}</div>}
function Section({icon:Icon,title,tone,children}){const styles={blue:'border-blue-200 bg-blue-50/60 text-blue-800',emerald:'border-emerald-200 bg-emerald-50/60 text-emerald-800',amber:'border-amber-200 bg-amber-50/60 text-amber-800'};return <div className={`rounded-2xl border p-4 ${styles[tone]}`}><div className="mb-3 flex items-center gap-2"><Icon className="h-4 w-4"/><h4 className="text-xs font-black">{title}</h4></div><div className="space-y-2">{children}</div></div>}
