import React,{useCallback,useEffect,useState}from'react';
import{Bot,Calculator,ExternalLink,History,Lightbulb,Loader2,Send,ShieldCheck,Sparkles}from'lucide-react';
import{supabase}from'../supabaseClient';

const EXTRA_MODULE_STARTERS={obras:['Resume el estado general de las obras.','¿Qué obras requieren atención?'],mandante:['Resume contratos, entregas y obligaciones del mandante.','¿Qué contratos requieren atención?']};

const STARTERS=['¿Cuáles son las partidas con menor avance?','¿Qué restricciones Last Planner están pendientes?','¿Cuál es el estado de la maquinaria y sus fallas?','¿Cuántas personas están asignadas a esta obra?','¿Qué desviaciones de costo requieren atención?','¿Cuál es el estado de calidad y prevención?'];
const ASSISTED_STARTERS=['Analiza las restricciones recurrentes y propone un plan de recuperación.','Analiza las no conformidades recurrentes y sugiere causas y acciones.','Analiza los eventos preventivos y sugiere controles para revisión.','Analiza las fallas recurrentes y recomienda redistribución de equipos.','Explica las brechas de dotación y propone escenarios por cargo.'];
const MODULE_STARTERS={dashboard:['Resume el estado general de los módulos que puedo consultar.','¿Qué aspectos requieren mi atención?'],admin:['Resume la configuración de usuarios y roles.','¿Qué aspectos de gobierno requieren revisión?'],rrhh:['Resume la dotación y asignaciones.','¿Qué brechas de personal requieren atención?'],maquinaria:['Resume disponibilidad, uso, mantenciones y fallas.','¿Qué equipos requieren atención?'],bodega:['Resume stock y movimientos de bodega.','¿Qué productos presentan riesgo de quiebre?'],prevencion:['Resume registros, incidentes y procedimientos.','¿Qué riesgos requieren seguimiento?'],formularios:['Resume formularios y respuestas registradas.','¿Qué formularios tienen menor actividad?'],acreditaciones:['Resume el estado de las acreditaciones.','¿Qué documentos requieren revisión?'],calidad:['Resume RDI, recepciones y no conformidades.','¿Qué asuntos de calidad requieren seguimiento?'],presupuestos:['Resume presupuestos y planificación disponible.','¿Qué desviaciones requieren revisión?'],clientes:['Resume portales y obras habilitadas para clientes.','¿Qué accesos requieren seguimiento?'],facturacion:['Resume documentos tributarios y sus estados.','¿Qué documentos requieren revisión?'],gastos:['Resume rendiciones y montos por estado.','¿Qué rendiciones requieren atención?']};

export default function CopilotoObra({user,obra,moduleContext,onNavigate,compact=false}){
 const[pregunta,setPregunta]=useState(''),[answer,setAnswer]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState([]);
 const isWorksite=Boolean(obra?.nombre),moduleId=moduleContext?.id||'obras';
 const starters=isWorksite?STARTERS:(EXTRA_MODULE_STARTERS[moduleId]||MODULE_STARTERS[moduleId]||MODULE_STARTERS.dashboard);
 const loadHistory=useCallback(async()=>{if(isWorksite){const{data}=await supabase.from('copiloto_obra_consultas').select('id,pregunta,respuesta,created_at').eq('empresa',user?.empresa).eq('obra_nombre',obra.nombre).order('created_at',{ascending:false}).limit(8);setHistory(data||[]);return}const{data}=await supabase.from('ox_consultas_modulo').select('id,pregunta,respuesta,created_at').eq('empresa',user?.empresa).eq('modulo',moduleId).order('created_at',{ascending:false}).limit(8);setHistory(data||[])},[isWorksite,moduleId,obra?.nombre,user?.empresa]);
 useEffect(()=>{setAnswer(null);setPregunta('');loadHistory()},[loadHistory]);
 const ask=async(text=pregunta)=>{const clean=String(text||'').trim();if(clean.length<4)return;setLoading(true);setError('');const endpoint=isWorksite?'copiloto-obra':'ox-modulos';const body=isWorksite?{empresa:user?.empresa,obra_nombre:obra?.nombre,pregunta:clean}:{empresa:user?.empresa,modulo:moduleId,pregunta:clean};const{data,error:invokeError}=await supabase.functions.invoke(endpoint,{body});let serverMessage=data?.error||'';if(invokeError?.context&&typeof invokeError.context.json==='function'){try{const payload=await invokeError.context.json();serverMessage=payload?.error||serverMessage}catch{}}if(invokeError||data?.error)setError(serverMessage||invokeError?.message||'No fue posible consultar OX.');else{setAnswer(data.data);setPregunta('');await loadHistory()}setLoading(false)};
 return <div className="space-y-5 animate-in fade-in duration-200">
  {!compact&&<div className="rounded-2xl border border-violet-200 bg-gradient-to-r from-violet-950 to-indigo-900 p-5 text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="rounded-xl bg-white/10 p-3"><Bot className="h-6 w-6 text-violet-200"/></span><div><h3 className="text-base font-black">OX · Asistente contextual</h3><p className="mt-1 max-w-2xl text-xs text-violet-100">Consulta indicadores autorizados de {obra?.nombre}. Responde con hechos trazables, cálculos visibles y sugerencias separadas.</p></div></div><span className="flex items-center gap-1.5 rounded-full border border-emerald-300/30 bg-emerald-400/10 px-3 py-1.5 text-[10px] font-black uppercase"><ShieldCheck className="h-3.5 w-3.5"/>Solo lectura</span></div></div>}
  <div className={`grid gap-5 ${compact?'grid-cols-1':'xl:grid-cols-[minmax(0,1fr)_300px]'}`}>
   <section className="space-y-4"><div className="rounded-2xl border bg-white p-5"><label className="text-xs font-black text-slate-900">¿Qué necesitas analizar?</label><div className="mt-3 flex gap-2"><textarea value={pregunta} onChange={e=>setPregunta(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}}} maxLength={1000} rows={3} placeholder={isWorksite?'Ej.: ¿Cuáles son las partidas con mayor riesgo de atraso?':`Consulta sobre ${moduleContext?.label||'este módulo'}…`} className="min-h-24 flex-1 resize-none rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-violet-600"/><button type="button" onClick={()=>ask()} disabled={loading||pregunta.trim().length<4} className="self-end rounded-xl bg-violet-700 p-3 text-white disabled:opacity-40">{loading?<Loader2 className="h-5 w-5 animate-spin"/>:<Send className="h-5 w-5"/>}</button></div><div className="mt-3 flex flex-wrap gap-2">{starters.map(item=><button key={item} type="button" onClick={()=>ask(item)} disabled={loading} className="rounded-full border border-violet-200 bg-violet-50 px-3 py-1.5 text-[10px] font-bold text-violet-800 hover:bg-violet-100">{item}</button>)}</div>{isWorksite&&<div className="mt-4 border-t border-slate-100 pt-3"><p className="flex items-center gap-1.5 text-[9px] font-black uppercase tracking-wider text-amber-700"><Sparkles className="h-3.5 w-3.5"/>Análisis asistido</p><div className="mt-2 flex flex-wrap gap-2">{ASSISTED_STARTERS.map(item=><button key={item} type="button" onClick={()=>ask(item)} disabled={loading} className="rounded-full border border-amber-200 bg-amber-50 px-3 py-1.5 text-[10px] font-bold text-amber-900 hover:bg-amber-100">{item}</button>)}</div></div>}</div>
   {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-xs font-bold text-rose-800">{error}</div>}
   {loading&&<div className="flex min-h-48 items-center justify-center rounded-2xl border bg-white"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-violet-700"/><p className="mt-2 text-xs font-bold text-slate-500">Analizando datos autorizados de la obra…</p></div></div>}
   {!loading&&answer&&<Answer data={answer} onNavigate={onNavigate}/>} {!loading&&!answer&&!error&&<div className="rounded-2xl border border-dashed bg-white p-10 text-center"><Sparkles className="mx-auto h-8 w-8 text-violet-300"/><p className="mt-3 text-sm font-black text-slate-700">OX está listo</p><p className="mt-1 text-xs text-slate-500">Selecciona una consulta o escribe lo que necesitas analizar.</p></div>}
   </section>
   <aside className="h-fit rounded-2xl border bg-white p-4"><div className="flex items-center gap-2"><History className="h-4 w-4 text-violet-700"/><h4 className="text-xs font-black">Consultas recientes</h4></div><div className={`mt-3 ${compact?'flex gap-2 overflow-x-auto pb-1':'space-y-2'}`}>{history.map(item=><button key={item.id} type="button" onClick={()=>setAnswer(item.respuesta)} className={`${compact?'min-w-48':'w-full'} rounded-xl border p-3 text-left hover:border-violet-300`}><p className="line-clamp-2 text-xs font-bold text-slate-700">{item.pregunta}</p><p className="mt-1 text-[9px] text-slate-400">{new Date(item.created_at).toLocaleString('es-CL')}</p></button>)}{!history.length&&<p className="rounded-xl bg-slate-50 p-3 text-xs text-slate-400">Aún no hay consultas en esta obra.</p>}</div></aside>
  </div>
 </div>;
}

function Answer({data,onNavigate}){return <div className="space-y-4"><div className="rounded-2xl border border-violet-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-[10px] font-black uppercase tracking-wider text-violet-700">Respuesta breve</p>{data.meta?.generado_con_ia&&<span className="rounded-full bg-violet-100 px-2 py-1 text-[9px] font-black text-violet-800">Generado con IA</span>}</div><p className="mt-2 text-sm font-bold leading-relaxed text-slate-800">{data.respuesta_breve}</p></div><Section icon={ExternalLink} title="Hechos trazables" tone="blue">{(data.hechos||[]).map((item,index)=><div key={index} className="rounded-xl border bg-white p-3"><p className="text-xs text-slate-700">{item.texto}</p><div className="mt-2 flex flex-wrap items-center justify-between gap-2"><p className="text-[9px] font-black uppercase text-blue-700">{item.modulo} · {item.referencia}</p>{item.destino&&<button type="button" onClick={()=>onNavigate?.(item.destino,item)} className="rounded-lg border border-blue-200 bg-blue-50 px-2 py-1 text-[9px] font-black text-blue-800 hover:bg-blue-100">Abrir registro</button>}</div></div>)}</Section><Section icon={Calculator} title="Cálculos" tone="emerald">{(data.calculos||[]).map((item,index)=><div key={index} className="rounded-xl border bg-white p-3"><div className="flex justify-between gap-3"><b className="text-xs">{item.nombre}</b><span className="text-xs font-black text-emerald-700">{item.valor}</span></div><p className="mt-1 text-[10px] text-slate-500">Base: {item.base}</p></div>)}</Section><Section icon={Lightbulb} title="Sugerencias profesionales" tone="amber">{(data.sugerencias||[]).map((item,index)=><div key={index} className="rounded-xl border bg-white p-3"><div className="flex items-start justify-between gap-2"><b className="text-xs">{item.accion}</b><span className="rounded-full bg-amber-100 px-2 py-1 text-[9px] font-black text-amber-800">{item.prioridad}</span></div><p className="mt-1 text-[10px] text-slate-500">{item.motivo}</p></div>)}</Section>{Boolean(data.limitaciones?.length)&&<div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-[10px] font-black uppercase text-slate-500">Datos no disponibles o limitaciones</p><ul className="mt-2 list-disc space-y-1 pl-4 text-xs text-slate-600">{data.limitaciones.map((item,index)=><li key={index}>{item}</li>)}</ul></div>}</div>}
function Section({icon:Icon,title,tone,children}){const styles={blue:'border-blue-200 bg-blue-50/60 text-blue-800',emerald:'border-emerald-200 bg-emerald-50/60 text-emerald-800',amber:'border-amber-200 bg-amber-50/60 text-amber-800'};return <div className={`rounded-2xl border p-4 ${styles[tone]}`}><div className="mb-3 flex items-center gap-2"><Icon className="h-4 w-4"/><h4 className="text-xs font-black">{title}</h4></div><div className="space-y-2">{children}</div></div>}
