import React, { useEffect, useMemo, useState } from 'react';
import { BadgeCheck, Building2, Check, ClipboardList, FileCheck2, Handshake, History, Link2, Loader2, Plus, Save, ShieldCheck } from 'lucide-react';
import { supabase } from '../supabaseClient';
import { formatRut } from '../utils/rutUtils';
import ModuleHeader from './ModuleHeader';

const input = 'mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-primary';
const PACKAGES = [['avance','Avance físico'],['programacion','Programación'],['hitos','Hitos contractuales'],['estados_pago','Estados de pago'],['rdi','RDI'],['libro_obra','Libro de obra'],['calidad','Calidad'],['prevencion','Prevención'],['documentos','Documentos'],['acreditaciones','Acreditaciones']];
const emptyProject = { codigo:'', nombre:'', descripcion:'', ubicacion:'', administrador_contrato:'', ito_responsable:'', presupuesto_contractual:'', fecha_inicio:'', fecha_termino:'' };
const emptyContract = { proyecto_id:'', codigo:'', nombre:'', rut_contratista:'', empresa_contratista:'', modalidad:'Portal externo', empresa_obraxis_vinculada:'', obra_contratista_id:'', obra_contratista_nombre:'', administrador_contrato:'', ito_responsable:'', contacto_nombre:'', contacto_email:'', presupuesto_contractual:'', fecha_inicio:'', fecha_termino:'', paquetes:Object.fromEntries(PACKAGES.map(([id])=>[id,true])), periodicidad:{ avance:'Semanal', prevencion:'Mensual', calidad:'Por evento' }, exige_acreditacion:true, alcance_acreditacion:{ empresa:true, personal:true, equipos:true } };
const money = value => `$${Number(value || 0).toLocaleString('es-CL')}`;

export default function GestionMandante({ user, onBack }) {
  const company = user?.empresa;
  const [tab,setTab]=useState('proyectos'), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false);
  const [projects,setProjects]=useState([]), [contracts,setContracts]=useState([]), [events,setEvents]=useState([]), [companies,setCompanies]=useState([]), [works,setWorks]=useState([]);
  const [projectForm,setProjectForm]=useState(emptyProject), [contractForm,setContractForm]=useState(emptyContract), [message,setMessage]=useState(''), [error,setError]=useState('');
  const who = user?.nombre || user?.name || user?.usuario || user?.correo || 'Usuario Obraxis';
  const load = async () => {
    if(!company) return; setLoading(true); setError('');
    const [p,c,e,co,w]=await Promise.all([
      supabase.from('mandante_proyectos').select('*').eq('empresa_mandante',company).order('created_at',{ascending:false}),
      supabase.from('mandante_contratos').select('*').eq('empresa_mandante',company).order('created_at',{ascending:false}),
      supabase.from('mandante_eventos').select('*').eq('empresa_mandante',company).order('created_at',{ascending:false}).limit(150),
      supabase.from('config_empresa').select('empresa,razon_social,rut').not('rut','is',null).order('empresa'),
      supabase.from('obras').select('id,nombre,empresa,estado').order('nombre'),
    ]);
    const failed=[p,c,e,co,w].find(x=>x.error)?.error; if(failed) setError(failed.message);
    setProjects(p.data||[]);setContracts(c.data||[]);setEvents(e.data||[]);setCompanies(co.data||[]);setWorks(w.data||[]);setLoading(false);
  };
  useEffect(()=>{load();},[company]);
  const projectById=useMemo(()=>Object.fromEntries(projects.map(x=>[x.id,x])),[projects]);
  const linkedCompany=useMemo(()=>companies.find(x=>formatRut(x.rut)===formatRut(contractForm.rut_contratista)),[companies,contractForm.rut_contratista]);
  const linkedWorks=works.filter(x=>x.empresa===(linkedCompany?.empresa||contractForm.empresa_obraxis_vinculada));
  useEffect(()=>{ if(linkedCompany) setContractForm(v=>({...v,modalidad:'Empresa Obraxis',empresa_obraxis_vinculada:linkedCompany.empresa,empresa_contratista:v.empresa_contratista||linkedCompany.razon_social||linkedCompany.empresa})); },[linkedCompany?.empresa]);
  const event = async (payload) => supabase.from('mandante_eventos').insert({empresa_mandante:company,actor_nombre:who,actor_empresa:company,...payload});
  const saveProject=async e=>{e.preventDefault();setSaving(true);setError('');const payload={...projectForm,empresa_mandante:company,presupuesto_contractual:Number(projectForm.presupuesto_contractual||0),creado_por:who};const {data,error:saveError}=await supabase.from('mandante_proyectos').insert(payload).select().single();if(saveError)setError(saveError.message);else{await event({proyecto_id:data.id,accion:'Proyecto del mandante creado',estado_resultante:'Activo',detalle:data.nombre});setProjectForm(emptyProject);setMessage('Proyecto contractual creado.');setTab('proyectos');await load();}setSaving(false);};
  const saveContract=async e=>{e.preventDefault();setSaving(true);setError('');const selectedWork=works.find(x=>String(x.id)===String(contractForm.obra_contratista_id));const payload={...contractForm,empresa_mandante:company,presupuesto_contractual:Number(contractForm.presupuesto_contractual||0),obra_contratista_id:contractForm.modalidad==='Empresa Obraxis'&&contractForm.obra_contratista_id?Number(contractForm.obra_contratista_id):null,obra_contratista_nombre:selectedWork?.nombre||null,empresa_obraxis_vinculada:contractForm.modalidad==='Empresa Obraxis'?contractForm.empresa_obraxis_vinculada:null,estado:contractForm.modalidad==='Empresa Obraxis'?'Vinculado':'Configuracion',creado_por:who};const {data,error:saveError}=await supabase.from('mandante_contratos').insert(payload).select().single();if(saveError)setError(saveError.message);else{await event({proyecto_id:data.proyecto_id,contrato_id:data.id,accion:data.modalidad==='Empresa Obraxis'?'Contrato vinculado por RUT':'Portal externo configurado',estado_resultante:data.estado,detalle:`${data.codigo} · ${data.empresa_contratista}${data.exige_acreditacion?' · Acreditación exigida':''}`});setContractForm(emptyContract);setMessage('Contrato creado con sus reglas de información y acreditación.');setTab('contratos');await load();}setSaving(false);};
  const projectFields=[['codigo','Código contractual'],['nombre','Nombre del proyecto'],['ubicacion','Ubicación'],['administrador_contrato','Administrador de contrato'],['ito_responsable','ITO responsable'],['presupuesto_contractual','Presupuesto contractual','number'],['fecha_inicio','Fecha de inicio','date'],['fecha_termino','Fecha de término','date']];
  if(loading)return <div className="flex min-h-72 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-primary"/></div>;
  return <div className="space-y-5"><ModuleHeader title="Gestión del Mandante" subtitle="Control contractual independiente para mandantes y propietarios, conectado por RUT con empresas Obraxis o mediante portal externo." Icon={Building2} onBack={onBack} actions={<button onClick={()=>setTab('nuevo-proyecto')} className="flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-xs font-black text-white"><Plus className="h-4 w-4"/>Nuevo proyecto</button>}/>
  <div className="grid gap-3 md:grid-cols-4">{[[projects.length,'Proyectos','Del mandante'],[contracts.length,'Contratos','Contratistas'],[contracts.filter(x=>x.modalidad==='Empresa Obraxis').length,'Conectados','Por RUT'],[contracts.filter(x=>x.exige_acreditacion).length,'Con acreditación','Empresa, personal o equipos']].map(([value,label,detail])=><div key={label} className="rounded-2xl border bg-white p-4"><p className="text-2xl font-black text-slate-900">{value}</p><p className="text-xs font-black text-slate-700">{label}</p><p className="text-[10px] text-slate-500">{detail}</p></div>)}</div>
  <nav className="flex flex-wrap gap-2 rounded-2xl border bg-white p-2">{[['proyectos','Proyectos'],['contratos','Contratos'],['nuevo-contrato','Configurar contrato'],['acreditaciones','Acreditaciones'],['actividad','Trazabilidad']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-4 py-2 text-xs font-black ${tab===id?'bg-primary text-white':'text-slate-600 hover:bg-slate-100'}`}>{label}</button>)}</nav>
  {message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{message}</div>}{error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-800">{error}</div>}
  {tab==='proyectos'&&<div className="grid gap-4 xl:grid-cols-2">{projects.map(p=><article key={p.id} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-primary">{p.codigo}</p><h3 className="text-lg font-black">{p.nombre}</h3><p className="text-xs text-slate-500">{p.ubicacion||'Ubicación no informada'}</p></div><span className="h-fit rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black text-emerald-700">{p.estado}</span></div><div className="mt-4 grid grid-cols-2 gap-2 rounded-2xl bg-slate-50 p-4 text-xs"><span>Presupuesto<br/><b>{money(p.presupuesto_contractual)}</b></span><span>Contratos<br/><b>{contracts.filter(x=>x.proyecto_id===p.id).length}</b></span><span>Administrador<br/><b>{p.administrador_contrato||'N/I'}</b></span><span>ITO<br/><b>{p.ito_responsable||'N/I'}</b></span></div><button onClick={()=>{setContractForm({...emptyContract,proyecto_id:p.id});setTab('nuevo-contrato');}} className="mt-3 w-full rounded-xl bg-slate-950 py-2.5 text-xs font-black text-white">Agregar contrato</button></article>)}{!projects.length&&<Empty text="Aún no existen proyectos del mandante."/>}</div>}
  {tab==='nuevo-proyecto'&&<form onSubmit={saveProject} className="rounded-3xl border bg-white p-5"><h3 className="font-black">Nuevo proyecto contractual</h3><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{projectFields.map(([key,label,type='text'])=><label key={key} className="text-xs font-black text-slate-600">{label}<input required={['codigo','nombre'].includes(key)} type={type} value={projectForm[key]} onChange={e=>setProjectForm(v=>({...v,[key]:e.target.value}))} className={input}/></label>)}</div><label className="mt-3 block text-xs font-black text-slate-600">Descripción<textarea value={projectForm.descripcion} onChange={e=>setProjectForm(v=>({...v,descripcion:e.target.value}))} className={input}/></label><button disabled={saving} className="mt-5 flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 text-xs font-black text-white"><Save className="h-4 w-4"/>Crear proyecto</button></form>}
  {tab==='contratos'&&<div className="space-y-3">{contracts.map(c=><article key={c.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black text-primary">{projectById[c.proyecto_id]?.nombre} · {c.codigo}</p><h3 className="font-black">{c.nombre}</h3><p className="text-xs text-slate-500">{c.empresa_contratista} · RUT {c.rut_contratista}</p></div><div className="flex gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-black text-blue-700">{c.modalidad}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black">{c.estado}</span></div></div><div className="mt-3 flex flex-wrap gap-1">{Object.entries(c.paquetes||{}).filter(([,on])=>on).map(([id])=><span key={id} className="rounded-lg border px-2 py-1 text-[9px] font-bold text-slate-600">{PACKAGES.find(x=>x[0]===id)?.[1]||id}</span>)}</div>{c.exige_acreditacion&&<p className="mt-3 flex items-center gap-2 text-xs font-bold text-emerald-700"><BadgeCheck className="h-4 w-4"/>Acreditación contractual exigida: {Object.entries(c.alcance_acreditacion||{}).filter(([,on])=>on).map(([id])=>id).join(', ')}</p>}</article>)}{!contracts.length&&<Empty text="Aún no existen contratos asociados."/>}</div>}
  {tab==='nuevo-contrato'&&<form onSubmit={saveContract} className="rounded-3xl border bg-white p-5"><h3 className="font-black">Configurar contrato e intercambio de información</h3><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Select label="Proyecto" required value={contractForm.proyecto_id} onChange={v=>setContractForm(x=>({...x,proyecto_id:v}))} options={projects.map(x=>[x.id,`${x.codigo} · ${x.nombre}`])}/>{[['codigo','Código de contrato'],['nombre','Nombre del contrato'],['rut_contratista','RUT contratista'],['empresa_contratista','Razón social contratista'],['contacto_nombre','Contacto'],['contacto_email','Correo'],['administrador_contrato','Administrador de contrato'],['ito_responsable','ITO responsable'],['presupuesto_contractual','Presupuesto','number'],['fecha_inicio','Inicio','date'],['fecha_termino','Término','date']].map(([key,label,type='text'])=><label key={key} className="text-xs font-black text-slate-600">{label}<input required={['codigo','nombre','rut_contratista','empresa_contratista'].includes(key)} type={type} value={contractForm[key]} onChange={e=>setContractForm(v=>({...v,[key]:key==='rut_contratista'?formatRut(e.target.value):e.target.value}))} className={input}/></label>)}</div>
  <div className={`mt-4 rounded-2xl border p-4 ${linkedCompany?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><p className="flex items-center gap-2 text-xs font-black"><Link2 className="h-4 w-4"/>{linkedCompany?`Empresa Obraxis encontrada: ${linkedCompany.empresa}`:'No se encontró una empresa Obraxis con ese RUT: se utilizará portal externo.'}</p>{linkedCompany&&<Select label="Obra de la contratista que se vinculará" value={contractForm.obra_contratista_id} onChange={v=>setContractForm(x=>({...x,obra_contratista_id:v}))} options={linkedWorks.map(x=>[x.id,x.nombre])}/>}</div>
  <h4 className="mt-5 text-sm font-black">Paquete contractual de información</h4><div className="mt-2 grid gap-2 md:grid-cols-3 xl:grid-cols-5">{PACKAGES.map(([id,label])=><Toggle key={id} label={label} checked={contractForm.paquetes[id]} onChange={on=>setContractForm(v=>({...v,paquetes:{...v.paquetes,[id]:on}}))}/>)}</div>
  <div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><Toggle label="Exigir acreditación para este contrato" checked={contractForm.exige_acreditacion} onChange={on=>setContractForm(v=>({...v,exige_acreditacion:on}))}/>{contractForm.exige_acreditacion&&<div className="mt-3 flex flex-wrap gap-2">{[['empresa','Documentación de empresa'],['personal','Personal'],['equipos','Equipos y vehículos']].map(([id,label])=><Toggle key={id} label={label} checked={contractForm.alcance_acreditacion[id]} onChange={on=>setContractForm(v=>({...v,alcance_acreditacion:{...v.alcance_acreditacion,[id]:on}}))}/>)}</div>}</div>
  <button disabled={saving} className="mt-5 flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 text-xs font-black text-white"><Save className="h-4 w-4"/>Crear contrato</button></form>}
  {tab==='acreditaciones'&&<div className="space-y-3">{contracts.filter(x=>x.exige_acreditacion).map(c=><article key={c.id} className="grid items-center gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_auto_auto]"><div><p className="text-[10px] font-black text-primary">{c.codigo} · {projectById[c.proyecto_id]?.nombre}</p><h3 className="font-black">{c.empresa_contratista}</h3><p className="text-xs text-slate-500">RUT {c.rut_contratista}</p></div><div className="flex gap-2">{Object.entries(c.alcance_acreditacion||{}).filter(([,on])=>on).map(([id])=><span key={id} className="rounded-lg bg-emerald-50 px-2 py-1 text-[10px] font-black text-emerald-700">{id}</span>)}</div><span className="flex items-center gap-2 text-xs font-black text-amber-700"><ShieldCheck className="h-4 w-4"/>Pendiente de expediente</span></article>)}{!contracts.some(x=>x.exige_acreditacion)&&<Empty text="No hay contratos con acreditación exigida."/>}</div>}
  {tab==='actividad'&&<div className="overflow-hidden rounded-3xl border bg-white">{events.map(e=><div key={e.id} className="grid gap-1 border-b p-4 md:grid-cols-[170px_1fr_220px]"><span className="text-xs text-slate-500">{new Date(e.created_at).toLocaleString('es-CL')}</span><div><p className="text-sm font-black">{e.accion}</p><p className="text-xs text-slate-500">{e.detalle}</p></div><span className="text-xs font-bold text-slate-600">{e.actor_nombre} · {e.actor_empresa}</span></div>)}</div>}
  </div>;
}

function Toggle({label,checked,onChange}){return <label className="flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700"><input type="checkbox" checked={Boolean(checked)} onChange={e=>onChange(e.target.checked)} className="h-4 w-4 accent-primary"/>{label}{checked&&<Check className="ml-auto h-3.5 w-3.5 text-emerald-600"/>}</label>}
function Select({label,value,onChange,options,required}){return <label className="block text-xs font-black text-slate-600">{label}<select required={required} value={value} onChange={e=>onChange(e.target.value)} className={input}><option value="">Seleccionar</option>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}
function Empty({text}){return <div className="rounded-3xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">{text}</div>}
