import React, { useEffect, useMemo, useState } from 'react';
import { BarChart3, Clock3, Download, Loader2, Mail, Plus, Send, Trash2 } from 'lucide-react';
import { supabase } from '../supabaseClient';
import { sendSystemEmail } from '../utils/emailService';

const field='rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-bold outline-none focus:border-primary';

export default function MandanteReports({contracts,projects,company,who}){
  const [configs,setConfigs]=useState([]),[history,setHistory]=useState([]),[drafts,setDrafts]=useState({}),[email,setEmail]=useState({}),[working,setWorking]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
  const projectById=useMemo(()=>Object.fromEntries(projects.map(x=>[x.id,x])),[projects]);
  const owned=contracts.filter(x=>x.empresa_mandante===company);
  const load=async()=>{const ids=owned.map(x=>x.id);if(!ids.length){setConfigs([]);setHistory([]);return;}const[c,h]=await Promise.all([supabase.from('mandante_informes_config').select('*').in('contrato_id',ids),supabase.from('mandante_informes_historial').select('id,contrato_id,periodo,resumen,destinatarios,estado,error,generado_por,generado_at,enviado_at').in('contrato_id',ids).order('generado_at',{ascending:false}).limit(100)]);if(c.error||h.error)setError(c.error?.message||h.error?.message);setConfigs(c.data||[]);setHistory(h.data||[]);setDrafts(Object.fromEntries(owned.map(contract=>{const cfg=(c.data||[]).find(x=>x.contrato_id===contract.id);return[contract.id,cfg||{contrato_id:contract.id,empresa_mandante:company,activo:false,frecuencia:'Semanal',dia_semana:1,dia_mes:1,hora:'08:00',destinatarios:[]}];})));};
  useEffect(()=>{load();},[company,contracts.map(x=>x.id).join('|')]);
  const update=(id,changes)=>setDrafts(v=>({...v,[id]:{...v[id],...changes}}));
  const addEmail=id=>{const value=(email[id]||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return setError('Ingresa un correo válido.');update(id,{destinatarios:[...new Set([...(drafts[id]?.destinatarios||[]),value])]});setEmail(v=>({...v,[id]:''}));setError('');};
  const save=async contract=>{setWorking(`save-${contract.id}`);setError('');const payload={...drafts[contract.id],contrato_id:contract.id,empresa_mandante:company,creado_por:who,updated_at:new Date().toISOString(),proxima_ejecucion_at:drafts[contract.id]?.activo?(drafts[contract.id]?.proxima_ejecucion_at||new Date().toISOString()):null};const{error:e}=await supabase.from('mandante_informes_config').upsert(payload,{onConflict:'contrato_id'});setWorking('');if(e)return setError(e.message);setMessage('Configuración guardada. El envío manual ya está disponible; la automatización requiere autorización de distribución contractual.');await load();};
  const generate=async(contract,send=false)=>{setWorking(`${send?'send':'preview'}-${contract.id}`);setError('');const cfg=drafts[contract.id];const recipients=cfg?.destinatarios||[];if(send&&!recipients.length){setWorking('');return setError('Configura al menos un destinatario.');}const{data,error:e}=await supabase.functions.invoke('informes-mandante',{body:{contrato_id:contract.id,destinatarios:recipients}});if(e||data?.error){setWorking('');return setError(data?.error||e.message);}if(send){const project=projectById[contract.proyecto_id];const result=await sendSystemEmail({to:recipients,subject:`Informe contractual · ${contract.codigo} · ${project?.nombre||contract.nombre}`,htmlContent:data.html});if(!result.success){setWorking('');return setError(result.error||'No fue posible enviar el informe.');}await supabase.functions.invoke('informes-mandante',{body:{confirmar_envio:true,historial_id:data.id}});setMessage(`Informe enviado a ${recipients.length} destinatario(s).`);}else{const win=window.open('','_blank','noopener,noreferrer');if(!win){setWorking('');return setError('El navegador bloqueó la vista previa. Habilita ventanas emergentes.');}win.document.open();win.document.write(data.html);win.document.close();}setWorking('');await load();};
  return <section className="space-y-4">
    <div className="rounded-3xl border bg-white p-5"><div className="flex items-center gap-3"><div className="rounded-2xl bg-blue-50 p-3 text-blue-700"><BarChart3 className="h-6 w-6"/></div><div><p className="text-[10px] font-black uppercase tracking-widest text-primary">Lectura contractual</p><h3 className="font-black">Informes ejecutivos y distribución</h3><p className="text-xs text-slate-500">Generación determinística desde entregas, obligaciones, acreditaciones, plazo y avance financiero.</p></div></div></div>
    {message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-800">{message}</div>}{error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-800">{error}</div>}
    {owned.map(contract=>{const d=drafts[contract.id]||{};const rows=history.filter(x=>x.contrato_id===contract.id);return <article key={contract.id} className="rounded-3xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase text-primary">{contract.codigo} · {projectById[contract.proyecto_id]?.nombre}</p><h3 className="font-black">{contract.empresa_contratista}</h3><p className="text-xs text-slate-500">Informe contractual por contrato, con historial inalterable.</p></div><div className="flex flex-wrap gap-2"><button disabled={working} onClick={()=>generate(contract,false)} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-black"><Download className="h-4 w-4"/>Vista previa / PDF</button><button disabled={working} onClick={()=>generate(contract,true)} className="flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-xs font-black text-white">{working===`send-${contract.id}`?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}Enviar ahora</button></div></div>
      <div className="mt-4 grid gap-3 rounded-2xl border bg-slate-50 p-4 md:grid-cols-2 xl:grid-cols-5"><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={Boolean(d.activo)} onChange={e=>update(contract.id,{activo:e.target.checked})}/>Envío automático</label><select className={field} value={d.frecuencia||'Semanal'} onChange={e=>update(contract.id,{frecuencia:e.target.value})}><option>Semanal</option><option>Mensual</option></select>{d.frecuencia==='Mensual'?<label className="text-[10px] font-black text-slate-500">Día del mes<input className={`${field} mt-1 w-full`} type="number" min="1" max="28" value={d.dia_mes||1} onChange={e=>update(contract.id,{dia_mes:Number(e.target.value)})}/></label>:<label className="text-[10px] font-black text-slate-500">Día semanal<select className={`${field} mt-1 w-full`} value={d.dia_semana||1} onChange={e=>update(contract.id,{dia_semana:Number(e.target.value)})}>{[['1','Lunes'],['2','Martes'],['3','Miércoles'],['4','Jueves'],['5','Viernes']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}<label className="text-[10px] font-black text-slate-500">Hora<input className={`${field} mt-1 w-full`} type="time" value={String(d.hora||'08:00').slice(0,5)} onChange={e=>update(contract.id,{hora:e.target.value})}/></label><button disabled={working===`save-${contract.id}`} onClick={()=>save(contract)} className="self-end rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white">Guardar programación</button></div>
      <div className="mt-3 rounded-2xl border p-4"><p className="flex items-center gap-2 text-xs font-black"><Mail className="h-4 w-4"/>Destinatarios</p><div className="mt-2 flex max-w-xl gap-2"><input className={`${field} min-w-0 flex-1`} placeholder="correo@empresa.cl" value={email[contract.id]||''} onChange={e=>setEmail(v=>({...v,[contract.id]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addEmail(contract.id);}}}/><button onClick={()=>addEmail(contract.id)} className="rounded-xl bg-blue-700 px-3 text-white"><Plus className="h-4 w-4"/></button></div><div className="mt-2 flex flex-wrap gap-2">{(d.destinatarios||[]).map(address=><span key={address} className="flex items-center gap-2 rounded-lg bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-800">{address}<button onClick={()=>update(contract.id,{destinatarios:d.destinatarios.filter(x=>x!==address)})}><Trash2 className="h-3 w-3"/></button></span>)}</div></div>
      <div className="mt-4"><p className="flex items-center gap-2 text-xs font-black"><Clock3 className="h-4 w-4"/>Últimos informes</p><div className="mt-2 divide-y rounded-2xl border">{rows.slice(0,5).map(row=><div key={row.id} className="grid gap-1 p-3 text-[10px] md:grid-cols-[150px_1fr_130px]"><span>{new Date(row.generado_at).toLocaleString('es-CL')}</span><span><b>{row.estado}</b> · Salud {row.resumen?.score??'—'}% · Avance financiero {Number(row.resumen?.financial_pct||0).toFixed(1)}%</span><span className={row.estado==='Error'?'font-bold text-rose-700':'font-bold text-emerald-700'}>{row.enviado_at?'Correo enviado':'Solo generado'}</span></div>)}{!rows.length&&<p className="p-4 text-xs text-slate-400">Aún no se han generado informes.</p>}</div></div>
    </article>})}{!owned.length&&<div className="rounded-3xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">Solo la empresa mandante puede configurar informes de sus contratos.</div>}
  </section>;
}
