import React,{useState} from 'react';
import { FileCheck2, KeyRound, Loader2, Paperclip, Send, ShieldCheck } from 'lucide-react';
import { supabase } from '../supabaseClient';
import PublicObraxisHeader from './PublicObraxisHeader';
const input='w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-primary';
const date=value=>value?new Date(value).toLocaleDateString('es-CL'):'—';

export default function PublicMandantePortal({token}){
 const[clave,setClave]=useState(''),[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[file,setFile]=useState(null);
 const[form,setForm]=useState({tipo:'Avance',titulo:'',periodo_desde:'',periodo_hasta:'',monto:'',detalle:''});
 const invoke=async body=>{const{data:response,error:functionError}=await supabase.functions.invoke('portal-mandante',{body:{token,clave:clave.trim().toUpperCase(),...body}});if(functionError)throw new Error(response?.error||functionError.message);if(response?.error)throw new Error(response.error);return response;};
 const login=async e=>{e.preventDefault();setLoading(true);setError('');try{setData(await invoke({action:'load'}));}catch(err){setError(err.message)}finally{setLoading(false)}};
 const submit=async e=>{e.preventDefault();setLoading(true);setError('');try{let adjunto_ids=[];if(file){const upload=await invoke({action:'create-upload',file:{name:file.name,type:file.type,size:file.size}});const {error:uploadError}=await supabase.storage.from('mandante-contractual').uploadToSignedUrl(upload.path,upload.token,file,{contentType:file.type});if(uploadError)throw uploadError;adjunto_ids=[upload.attachment.id];}await invoke({action:'submit',entrega:{...form,adjunto_ids}});setNotice('Entrega enviada y registrada correctamente.');setForm({tipo:'Avance',titulo:'',periodo_desde:'',periodo_hasta:'',monto:'',detalle:''});setFile(null);setData(await invoke({action:'load'}));}catch(err){setError(err.message)}finally{setLoading(false)}};
 if(!data)return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><div className="mx-auto max-w-4xl"><PublicObraxisHeader/><section className="mx-auto max-w-lg rounded-3xl border bg-white p-7 shadow-lg"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-950 text-white"><KeyRound className="h-7 w-7"/></div><h1 className="mt-5 text-center text-2xl font-black">Portal contractual</h1><p className="mt-2 text-center text-sm text-slate-500">Entrega información y revisa observaciones del mandante.</p><form onSubmit={login} className="mt-6 space-y-3"><input autoFocus value={clave} onChange={e=>setClave(e.target.value.toUpperCase())} placeholder="CLAVE DE ACCESO" className={`${input} text-center font-black tracking-[.2em]`}/>{error&&<p className="rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}<button disabled={loading||!clave} className="flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 py-3 text-sm font-black text-white">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<ShieldCheck className="h-4 w-4"/>}Ingresar</button></form></section></div></main>;
 const c=data.contract,enabled=Object.entries(c.paquetes||{}).filter(([,on])=>on).map(([id])=>id);
 return <main className="min-h-screen bg-slate-100 p-3 sm:p-6"><div className="mx-auto max-w-6xl"><PublicObraxisHeader/><header className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-[10px] font-black uppercase tracking-widest text-primary">Portal contractual del mandante</p><div className="mt-2 flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-black">{c.codigo} · {c.nombre}</h1><p className="text-sm text-slate-500">{c.empresa_contratista} → {c.empresa_mandante}</p></div><span className="h-fit rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">{c.estado}</span></div><div className="mt-4 flex flex-wrap gap-2">{enabled.map(id=><span key={id} className="rounded-lg border px-2 py-1 text-[10px] font-bold text-slate-600">{id.replaceAll('_',' ')}</span>)}</div></header>
 {error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}{notice&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-700">{notice}</p>}
 <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><section className="rounded-3xl border bg-white p-5"><h2 className="flex items-center gap-2 font-black"><Send className="h-5 w-5"/>Nueva entrega</h2><form onSubmit={submit} className="mt-4 space-y-3"><select className={input} value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}>{['Avance','Programacion','Hito','Estado de pago','RDI','Libro de obra','Calidad','Prevencion','Documento','Acreditacion'].map(x=><option key={x}>{x}</option>)}</select><input required className={input} placeholder="Título de la entrega" value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input type="date" className={input} value={form.periodo_desde} onChange={e=>setForm({...form,periodo_desde:e.target.value})}/><input type="date" className={input} value={form.periodo_hasta} onChange={e=>setForm({...form,periodo_hasta:e.target.value})}/></div><input type="number" min="0" className={input} placeholder="Monto, si corresponde" value={form.monto} onChange={e=>setForm({...form,monto:e.target.value})}/><textarea rows={4} className={input} placeholder="Detalle y antecedentes" value={form.detalle} onChange={e=>setForm({...form,detalle:e.target.value})}/><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3 text-xs font-bold text-slate-600"><Paperclip className="h-4 w-4"/><span className="min-w-0 flex-1 truncate">{file?file.name:'Adjuntar PDF, imagen, Excel o Word (máx. 20 MB)'}</span><input type="file" className="hidden" accept=".pdf,.jpg,.jpeg,.png,.xls,.xlsx,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 py-3 text-xs font-black text-white"><Send className="h-4 w-4"/>Enviar al mandante</button></form></section>
 <section className="space-y-4"><div className="rounded-3xl border bg-white p-5"><h2 className="flex items-center gap-2 font-black"><FileCheck2 className="h-5 w-5"/>Acreditaciones</h2><div className="mt-3 grid gap-2 sm:grid-cols-3">{data.accreditations.map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-3"><b className="text-xs">{x.categoria}</b><p className="text-[10px] font-bold text-amber-700">{x.estado}</p><p className="mt-1 text-[10px] text-slate-500">{x.total_aprobados}/{x.total_requeridos} aprobados</p></div>)}</div></div><div className="rounded-3xl border bg-white p-5"><h2 className="font-black">Últimas entregas</h2><div className="mt-3 divide-y">{data.deliveries.map(x=>{const files=(data.attachments||[]).filter(a=>a.entrega_id===x.id);return <div key={x.id} className="py-3"><div className="flex justify-between gap-2"><b className="text-xs">{x.tipo} · {x.titulo}</b><span className="text-[9px] font-black">{x.estado}</span></div><p className="text-[10px] text-slate-500">{date(x.enviado_at)}</p>{x.observacion_mandante&&<p className="mt-1 text-xs font-bold text-amber-700">Observación: {x.observacion_mandante}</p>}{files.map(a=><a key={a.id} href={a.url} target="_blank" rel="noreferrer" className="mt-2 flex items-center gap-2 text-xs font-bold text-primary"><Paperclip className="h-3.5 w-3.5"/>{a.nombre_archivo}</a>)}</div>})}</div></div></section></div></div></main>;
}
