import React, { useEffect, useState } from 'react';
import { CheckCircle2, FileText, XCircle } from 'lucide-react';
import { supabase } from '../supabaseClient';

const money = value => new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(Number(value || 0));
export default function PublicEstadoPago({ token, role }) {
  const [item, setItem] = useState(null); const [note, setNote] = useState(''); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  const load = async () => { const column = role === 'aprobacion' ? 'token_aprobacion' : 'token_revision'; const { data, error } = await supabase.from('estados_pago_obra').select('*').eq(column, token).maybeSingle(); if (error || !data) setMessage('El enlace no es válido o ya no está disponible.'); else setItem(data); setLoading(false); };
  useEffect(() => { load(); }, [token, role]);
  const resolve = async (approved) => { const estado = approved ? (role === 'aprobacion' ? 'Aprobado' : 'En aprobación') : 'Observado'; const field = role === 'aprobacion' ? 'observacion_aprobacion' : 'observacion_revision'; const { error } = await supabase.from('estados_pago_obra').update({ estado, [field]: note || null }).eq('id', item.id); if (error) setMessage(`No fue posible registrar la decisión: ${error.message}`); else { setMessage(approved ? 'Decisión registrada correctamente.' : 'El Estado de Pago fue devuelto con observaciones.'); await load(); } };
  if (loading) return <div className="min-h-screen grid place-items-center text-slate-500">Cargando Estado de Pago…</div>;
  if (!item) return <div className="min-h-screen grid place-items-center p-6 text-center text-rose-700">{message}</div>;
  const canAct = !['Aprobado','Pagado','Rechazado'].includes(item.estado);
  return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><section className="mx-auto max-w-3xl rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-center gap-2 border-b pb-4"><FileText className="text-emerald-700"/><div><h1 className="text-xl font-black text-slate-900">Estado de Pago N° {item.numero}</h1><p className="text-xs text-slate-500">{item.obra_nombre} · Corte {item.fecha_corte}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div><p className="text-[10px] font-bold uppercase text-slate-500">Bruto</p><b>{money(item.monto_bruto)}</b></div><div><p className="text-[10px] font-bold uppercase text-slate-500">Retención</p><b>{money(item.retencion_monto)}</b></div><div><p className="text-[10px] font-bold uppercase text-slate-500">Neto</p><b className="text-emerald-700">{money(item.monto_neto)}</b></div></div><div className="mt-5 overflow-x-auto"><table className="min-w-full text-xs"><thead className="border-b text-left text-slate-500"><tr><th className="p-2">Partida</th><th className="p-2 text-right">Avance EP</th><th className="p-2 text-right">Monto</th></tr></thead><tbody>{(item.items || []).map((line,i)=><tr key={i} className="border-b border-slate-100"><td className="p-2">{line.partida}</td><td className="p-2 text-right">{line.executed} {line.unidad}</td><td className="p-2 text-right font-bold">{money(line.amount)}</td></tr>)}</tbody></table></div>{canAct && <div className="mt-6 rounded-xl bg-slate-50 p-4"><p className="text-sm font-black">{role === 'aprobacion' ? 'Aprobación contractual' : 'Revisión técnica'}</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Comentario u observación" rows={3} className="mt-3 w-full rounded-lg border p-2 text-sm"/><div className="mt-3 flex gap-2"><button onClick={()=>resolve(true)} className="flex items-center gap-1 rounded-lg bg-emerald-700 px-4 py-2 text-xs font-black text-white"><CheckCircle2 className="h-4 w-4"/>{role === 'aprobacion' ? 'Aprobar' : 'Conforme, enviar a aprobación'}</button><button onClick={()=>resolve(false)} className="flex items-center gap-1 rounded-lg bg-rose-700 px-4 py-2 text-xs font-black text-white"><XCircle className="h-4 w-4"/>Devolver con observaciones</button></div></div>}{message && <p className="mt-4 text-sm font-bold text-slate-700">{message}</p>}</section></main>;
}
