import React, { useState } from 'react';
import { CheckCircle2, LockKeyhole, Send, XCircle } from 'lucide-react';
import { supabase } from '../supabaseClient';
import { appendAudit, auditActor } from '../utils/documentAudit';

const hashAccessCode = async value => { const hash = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(String(value || '').trim().toUpperCase())); return Array.from(new Uint8Array(hash)).map(byte => byte.toString(16).padStart(2, '0')).join(''); };
export default function PublicLibroObra({ token }) {
  const [item, setItem] = useState(null); const [code, setCode] = useState(''); const [identity, setIdentity] = useState({ nombre: '', rut: '', cargo: '', empresa: '' }); const [comment, setComment] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const enter = async event => { event.preventDefault(); setLoading(true); try { const { data, error } = await supabase.from('libro_obra_digital').select('*').eq('token_cliente', token).eq('clave_cliente_hash', await hashAccessCode(code)).maybeSingle(); if (error) throw error; if (!data) { setMessage('La clave o el enlace no son válidos.'); return; } setItem(data); setMessage(''); } catch (error) { setMessage(`No fue posible abrir el folio: ${error.message}`); } finally { setLoading(false); } };
  const decide = async accepted => { if (!identity.nombre || !identity.rut || !identity.cargo || !identity.empresa) { setMessage('Completa nombre, RUT, cargo y empresa para dejar constancia de tu respuesta.'); return; } if (!accepted && !comment.trim()) { setMessage('Indica el comentario u observación para devolver el folio.'); return; } setLoading(true); try { const state = accepted ? 'Aceptado por cliente' : 'Observado por cliente'; const audit = appendAudit(item.trazabilidad, auditActor({}, accepted ? 'Aceptado por cliente' : 'Observado por cliente', state, comment, identity)); const { error } = await supabase.from('libro_obra_digital').update({ flujo_estado: state, estado: accepted ? 'Respondido' : 'Abierto', respuesta: comment.trim() || 'Aceptado sin observaciones.', fecha_respuesta: new Date().toISOString().slice(0, 10), trazabilidad: audit }).eq('id', item.id); if (error) throw error; setItem({ ...item, flujo_estado: state, respuesta: comment.trim() || 'Aceptado sin observaciones.', trazabilidad: audit }); setMessage(accepted ? 'Aceptación registrada correctamente.' : 'Observaciones enviadas para su corrección.'); } catch (error) { setMessage(`No fue posible registrar tu respuesta: ${error.message}`); } finally { setLoading(false); } };
  if (!item) return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><section className="mx-auto mt-12 max-w-md rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-100 p-2 text-blue-800"><LockKeyhole className="h-5 w-5" /></div><div><h1 className="font-black text-slate-900">Libro de Obras</h1><p className="text-xs text-slate-500">Acceso protegido Obraxis</p></div></div><form onSubmit={enter} className="mt-5 space-y-3"><input autoFocus value={code} onChange={event => setCode(event.target.value.toUpperCase())} maxLength={8} placeholder="Clave de 8 caracteres" className="w-full rounded-xl border border-slate-300 px-4 py-3 text-center font-mono text-lg font-black tracking-[0.2em] uppercase" /><button disabled={loading} className="w-full rounded-xl bg-blue-800 py-3 text-sm font-black text-white">{loading ? 'Validando…' : 'Abrir folio'}</button></form>{message && <p className="mt-4 text-xs font-semibold text-rose-700">{message}</p>}</section></main>;
  const ended = ['Aceptado por cliente', 'Aceptado con observaciones', 'Cerrado'].includes(item.flujo_estado); return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><section className="mx-auto max-w-3xl rounded-2xl bg-white p-6 shadow-sm"><p className="font-mono text-xs font-black text-blue-900">{item.folio}</p><h1 className="mt-2 text-xl font-black text-slate-900">{item.asunto}</h1><p className="mt-1 text-xs text-slate-500">{item.obra_nombre} · {item.fecha} · {item.tipo}</p><p className="mt-5 whitespace-pre-line text-sm leading-relaxed text-slate-700">{item.detalle}</p><div className="mt-5 rounded-xl bg-slate-50 p-4 text-xs text-slate-700">Emite: <b>{item.emisor}</b>{item.destinatario ? ` · Dirigido a: ${item.destinatario}` : ''}</div>{!ended && <div className="mt-6 space-y-3 rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="font-black text-blue-950">Respuesta del cliente</p><div className="grid gap-2 sm:grid-cols-2"><input placeholder="Nombre completo *" value={identity.nombre} onChange={e => setIdentity({ ...identity, nombre: e.target.value })} className="rounded-lg border p-2 text-sm" /><input placeholder="RUT *" value={identity.rut} onChange={e => setIdentity({ ...identity, rut: e.target.value })} className="rounded-lg border p-2 text-sm" /><input placeholder="Cargo *" value={identity.cargo} onChange={e => setIdentity({ ...identity, cargo: e.target.value })} className="rounded-lg border p-2 text-sm" /><input placeholder="Empresa *" value={identity.empresa} onChange={e => setIdentity({ ...identity, empresa: e.target.value })} className="rounded-lg border p-2 text-sm" /></div><textarea rows={4} placeholder="Comentario u observación (obligatorio si devuelve el folio)" value={comment} onChange={e => setComment(e.target.value)} className="w-full rounded-lg border p-2 text-sm" /><div className="flex flex-wrap gap-2"><button disabled={loading} onClick={() => decide(true)} className="flex items-center gap-1 rounded-lg bg-emerald-700 px-4 py-2 text-xs font-black text-white"><CheckCircle2 className="h-4 w-4" />Aceptar</button><button disabled={loading} onClick={() => decide(false)} className="flex items-center gap-1 rounded-lg bg-amber-700 px-4 py-2 text-xs font-black text-white"><XCircle className="h-4 w-4" />Comentar / devolver</button></div></div>}{message && <p className="mt-4 text-sm font-bold text-slate-700">{message}</p>}</section></main>;
}
