import { Ionicons } from '@expo/vector-icons';
import { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, shadow } from '@/lib/theme';

export function Screen({ children, refreshing=false, onRefresh }: PropsWithChildren<{refreshing?:boolean;onRefresh?:()=>void}>) {
  return <SafeAreaView style={s.screen} edges={['top']}><ScrollView style={s.screen} contentContainerStyle={s.content} refreshControl={onRefresh?<RefreshControl refreshing={refreshing} onRefresh={onRefresh}/>:undefined}>{children}</ScrollView></SafeAreaView>;
}
export function Header({ title, subtitle, icon, action }: {title:string;subtitle?:string;icon:keyof typeof Ionicons.glyphMap;action?:ReactNode}) {
  return <View style={s.header}><View style={s.iconBox}><Ionicons name={icon} size={24} color={colors.orange}/></View><View style={{flex:1}}><Text style={s.title}>{title}</Text>{subtitle?<Text style={s.subtitle}>{subtitle}</Text>:null}</View>{action}</View>;
}
export function Card({ children, onPress }: PropsWithChildren<{onPress?:()=>void}>) { const body=<View style={s.card}>{children}</View>; return onPress?<Pressable onPress={onPress}>{body}</Pressable>:body; }
export function Badge({ children, tone='blue' }: PropsWithChildren<{tone?:'blue'|'green'|'amber'|'red'}>) { const map={blue:'#EAF0FF',green:'#E9F8F0',amber:'#FFF4DB',red:'#FDECEF'}; return <View style={[s.badge,{backgroundColor:map[tone]}]}><Text style={s.badgeText}>{children}</Text></View>; }
export function Empty({ text }: {text:string}) { return <View style={s.empty}><Ionicons name="file-tray-outline" size={28} color={colors.muted}/><Text style={s.emptyText}>{text}</Text></View>; }
export function Loading() { return <View style={s.empty}><ActivityIndicator color={colors.orange}/><Text style={s.emptyText}>Cargando información…</Text></View>; }
export function ErrorBox({ text }: {text:string}) { return text?<View style={s.error}><Ionicons name="alert-circle-outline" size={18} color={colors.red}/><Text style={s.errorText}>{text}</Text></View>:null; }
export function Progress({ value, color=colors.green }: {value:number;color?:string}) { const safe=Math.max(0,Math.min(100,value||0)); return <View><View style={s.track}><View style={[s.fill,{width:`${safe}%`,backgroundColor:color}]}/></View><Text style={s.progressText}>{safe.toFixed(1)}%</Text></View>; }
export function Segments({ value, options, onChange }: {value:string;options:{key:string;label:string}[];onChange:(v:string)=>void}) { return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.segments}>{options.map(o=><Pressable key={o.key} onPress={()=>onChange(o.key)} style={[s.segment,value===o.key&&s.segmentActive]}><Text style={[s.segmentText,value===o.key&&s.segmentTextActive]}>{o.label}</Text></Pressable>)}</ScrollView>; }
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.soft},content:{padding:16,paddingBottom:40,gap:12},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:4},iconBox:{width:46,height:46,borderRadius:15,backgroundColor:colors.navy,alignItems:'center',justifyContent:'center'},title:{fontSize:22,fontWeight:'900',color:colors.ink},subtitle:{fontSize:12,color:colors.muted,marginTop:2,lineHeight:17},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:16,gap:8,...shadow},badge:{alignSelf:'flex-start',borderRadius:99,paddingHorizontal:10,paddingVertical:5},badgeText:{fontSize:10,fontWeight:'800',color:colors.blue,textTransform:'uppercase'},empty:{alignItems:'center',justifyContent:'center',padding:32,gap:8},emptyText:{fontSize:13,color:colors.muted,textAlign:'center'},error:{backgroundColor:'#FFF1F2',padding:12,borderRadius:12,flexDirection:'row',gap:8},errorText:{color:colors.red,flex:1,fontSize:12},track:{height:8,borderRadius:99,backgroundColor:'#E8EDF4',overflow:'hidden'},fill:{height:'100%',borderRadius:99},progressText:{fontSize:11,fontWeight:'800',color:colors.ink,textAlign:'right',marginTop:4},segments:{gap:8,paddingVertical:4},segment:{paddingHorizontal:14,paddingVertical:10,borderRadius:12,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line},segmentActive:{backgroundColor:colors.navy,borderColor:colors.navy},segmentText:{fontSize:12,fontWeight:'800',color:colors.muted},segmentTextActive:{color:colors.white}});
export const ui = s;
