import { Ionicons } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { supabase } from '@/lib/supabase';
import { colors } from '@/lib/theme';
import type { Profile } from '@/lib/types';
type Row=Record<string,any>;
const today=()=>new Date().toISOString().slice(0,10);

export function WorkEntryActions({mode,profile,workId,workName,parts=[],onSaved}:{mode:'progress'|'attendance';profile:Profile;workId:number;workName:string;parts?:Row[];onSaved:()=>void}){
  const insets=useSafeAreaInsets();const[open,setOpen]=useState(false);const[selected,setSelected]=useState<Row|null>(null);const[workers,setWorkers]=useState<Row[]>([]);const[date,setDate]=useState(today());const[quantity,setQuantity]=useState('');const[note,setNote]=useState('');const[saving,setSaving]=useState(false);
  useEffect(()=>{if(mode==='attendance'&&open)supabase.from('maestro_personal').select('id,nombre,rut,cargo').eq('empresa',profile.empresa).eq('obra_nombre',workName).order('nombre').then(({data})=>setWorkers(data||[]))},[mode,open,profile.empresa,workName]);
  const options=mode==='progress'?parts.filter(part=>!part.es_titulo):workers;
  const save=async()=>{if(!selected)return Alert.alert('Falta información','Selecciona un elemento.');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return Alert.alert('Fecha inválida','Utiliza el formato AAAA-MM-DD.');setSaving(true);
    const result=mode==='progress'?await supabase.from('avances_produccion_partidas').insert({empresa:profile.empresa,obra_id:workId,obra_nombre:workName,supervisor:profile.nombre||profile.usuario,partida:selected.partida,unidad:selected.unidad,cantidad:Number(quantity),observaciones:note,created_at:new Date(`${date}T12:00:00Z`).toISOString()}):await supabase.from('asistencia_personal').insert({empresa:profile.empresa,obra_id:workId,obra_nombre:workName,supervisor:profile.nombre||profile.usuario,trabajador:selected.nombre,rut:selected.rut,asistencia:'Presente',fecha_marcacion:date});
    setSaving(false);if(result.error)return Alert.alert('No fue posible guardar',result.error.message);setOpen(false);setSelected(null);setQuantity('');setNote('');onSaved();Alert.alert('Registro guardado','La información quedó sincronizada con Obraxis.');
  };
  return <><Pressable onPress={()=>setOpen(true)} style={s.open}><Ionicons name="add-circle" size={20} color="white"/><Text style={s.openText}>{mode==='progress'?'Registrar avance':'Registrar asistencia'}</Text></Pressable><Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={s.overlay}><View style={[s.sheet,{paddingBottom:Math.max(20,insets.bottom)}]}><View style={s.top}><Text style={s.title}>{mode==='progress'?'Nuevo avance':'Marcar presente'}</Text><Pressable onPress={()=>setOpen(false)}><Ionicons name="close" size={26} color={colors.ink}/></Pressable></View><Text style={s.label}>Fecha</Text><TextInput value={date} onChangeText={setDate} placeholder="AAAA-MM-DD" style={s.input}/><Text style={s.label}>{mode==='progress'?'Selecciona la partida':'Selecciona el trabajador'}</Text><ScrollView style={s.options}>{options.map(item=><Pressable key={item.id} onPress={()=>setSelected(item)} style={[s.option,selected?.id===item.id&&s.optionActive]}><Text style={[s.optionText,selected?.id===item.id&&s.optionTextActive]}>{mode==='progress'?item.partida:`${item.nombre} · ${item.cargo||'Personal'}`}</Text></Pressable>)}</ScrollView>{!options.length?<Text style={s.empty}>No hay elementos disponibles para esta obra.</Text>:null}{mode==='progress'?<><Text style={s.label}>Cantidad ejecutada {selected?.unidad?`(${selected.unidad})`:''}</Text><TextInput keyboardType="decimal-pad" value={quantity} onChangeText={setQuantity} placeholder="0" style={s.input}/><Text style={s.label}>Observación</Text><TextInput value={note} onChangeText={setNote} placeholder="Opcional" multiline style={[s.input,s.textarea]}/></>:null}<Pressable disabled={saving||!selected||(mode==='progress'&&!Number(quantity))} onPress={save} style={[s.save,(saving||!selected||(mode==='progress'&&!Number(quantity)))&&s.disabled]}><Text style={s.saveText}>{saving?'Guardando…':'Guardar registro'}</Text></Pressable></View></View></Modal></>;
}
const s=StyleSheet.create({open:{height:48,borderRadius:14,backgroundColor:colors.orange,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center'},openText:{fontSize:13,fontWeight:'900',color:'white'},overlay:{flex:1,backgroundColor:'rgba(10,18,36,.55)',justifyContent:'flex-end'},sheet:{maxHeight:'88%',backgroundColor:'white',borderTopLeftRadius:26,borderTopRightRadius:26,padding:20,gap:10},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:21,fontWeight:'900',color:colors.ink},label:{fontSize:11,fontWeight:'900',textTransform:'uppercase',color:colors.muted,marginTop:5},options:{maxHeight:230},option:{padding:13,borderRadius:12,backgroundColor:colors.soft,marginBottom:7},optionActive:{backgroundColor:colors.blue},optionText:{fontSize:12,fontWeight:'800',color:colors.ink},optionTextActive:{color:'white'},input:{borderWidth:1,borderColor:colors.line,borderRadius:13,padding:13,fontSize:15,color:colors.ink},textarea:{height:75,textAlignVertical:'top'},save:{height:52,borderRadius:14,backgroundColor:colors.green,alignItems:'center',justifyContent:'center',marginTop:4},saveText:{color:'white',fontWeight:'900'},empty:{fontSize:12,color:colors.muted,textAlign:'center',padding:15},disabled:{opacity:.45}});
