import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { Card, Header, Screen } from '@/components/ui';
import { colors } from '@/lib/theme';
import { canUse } from '@/lib/types';
const modules=[['Obras','Avances, asistencia y gestión de terreno.','business','/obras','obra'],['Maquinaria','Equipos, registros, reservas y desempeño.','construct','/maquinaria','maquinaria'],['Recursos Humanos','Personal y asignaciones vigentes.','people','/personal','rrhh'],['Formularios','Biblioteca y registros operacionales.','clipboard','/formularios','formulario']] as const;
export default function Home(){const{profile,signOut}=useAuth();return <Screen><Header title={`Hola, ${profile?.nombre||profile?.usuario}`} subtitle={`${profile?.empresa} · ${profile?.cargo||profile?.rol||'Usuario'}`} icon="grid-outline" action={<Pressable onPress={signOut} style={s.logout}><Ionicons name="log-out-outline" size={20} color={colors.red}/></Pressable>}/><View style={s.hero}><Text style={s.kicker}>OPERACIÓN EN TERRENO</Text><Text style={s.heroTitle}>Todo lo esencial de la obra, en tu bolsillo.</Text><Text style={s.heroText}>Consulta datos reales y registra información con trazabilidad Obraxis.</Text></View>{modules.filter(m=>canUse(profile,m[4])||(m[4]==='formulario'&&canUse(profile,'prevencion'))).map(m=><Card key={m[0]} onPress={()=>router.push(m[3] as never)}><View style={s.row}><View style={s.moduleIcon}><Ionicons name={m[2]} size={23} color={colors.orange}/></View><View style={{flex:1}}><Text style={s.moduleTitle}>{m[0]}</Text><Text style={s.moduleText}>{m[1]}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></View></Card>)}</Screen>}
const s=StyleSheet.create({logout:{width:42,height:42,borderRadius:13,backgroundColor:'#FFF1F2',alignItems:'center',justifyContent:'center'},hero:{backgroundColor:colors.navy,borderRadius:22,padding:22,marginVertical:5},kicker:{fontSize:10,color:'#FFB368',letterSpacing:2,fontWeight:'900'},heroTitle:{fontSize:24,lineHeight:30,fontWeight:'900',color:'white',marginTop:8},heroText:{fontSize:13,lineHeight:19,color:'#BCC6D9',marginTop:8},row:{flexDirection:'row',alignItems:'center',gap:13},moduleIcon:{width:46,height:46,borderRadius:14,backgroundColor:'#FFF4E8',alignItems:'center',justifyContent:'center'},moduleTitle:{fontSize:15,fontWeight:'900',color:colors.ink},moduleText:{fontSize:11,color:colors.muted,marginTop:3,lineHeight:16}});
