import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const schema={type:"object",additionalProperties:false,properties:{resultado:{type:"string",enum:["Conforme","Observado","Requiere revisión"]},confianza:{type:"number"},resumen:{type:"string"},datos_extraidos:{type:"array",items:{type:"object",additionalProperties:false,properties:{campo:{type:"string"},valor:{type:"string"},evidencia:{type:"string"}},required:["campo","valor","evidencia"]}},hallazgos:{type:"array",items:{type:"object",additionalProperties:false,properties:{severidad:{type:"string",enum:["Alta","Media","Baja","Informativa"]},categoria:{type:"string"},detalle:{type:"string"},evidencia:{type:"string"},recomendacion:{type:"string"}},required:["severidad","categoria","detalle","evidencia","recomendacion"]}},campos_faltantes:{type:"array",items:{type:"string"}},recomendacion:{type:"string"}},required:["resultado","confianza","resumen","datos_extraidos","hallazgos","campos_faltantes","recomendacion"]};

Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 const started=Date.now();let reservationId:string|undefined;let db:any;
 try{
  const serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),openAIKey=Deno.env.get("OPENAI_API_KEY");
  if(!serviceKey||!openAIKey)return json({error:"La revisión inteligente no está configurada en el servidor."},503);
  db=createClient(Deno.env.get("SUPABASE_URL")!,serviceKey,{auth:{persistSession:false}});
  const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");
  const{data:authData,error:authError}=await db.auth.getUser(token);if(authError||!authData?.user)return json({error:"Debes iniciar sesión para revisar documentos."},401);
  const body=await req.json();const{file_base64,mime_type,file_name,empresa:requestedCompany,obra_nombre,subcontratista_nombre,subcontratista_rut,categoria,entidad_nombre,documento_clave,documento_nombre}=body||{};
  if(!file_base64||!mime_type||!documento_clave||!documento_nombre)return json({error:"Faltan el archivo o los datos del documento."},400);
  const allowed=["application/pdf","image/jpeg","image/png","image/webp","text/plain"];if(!allowed.includes(mime_type))return json({error:"Usa PDF, JPG, PNG, WEBP o TXT para la revisión inteligente."},400);
  let profileQuery=db.from("usuarios").select("usuario,nombre,correo,empresa").eq("auth_user_id",authData.user.id);if(requestedCompany)profileQuery=profileQuery.eq("empresa",requestedCompany);
  const{data:profiles,error:profileError}=await profileQuery.limit(2);if(profileError)throw profileError;if(!profiles?.length)return json({error:"La cuenta no está autorizada para esta empresa."},403);const profile=profiles[0];
  const[{data:globalConfig},{data:companyConfig}]=await Promise.all([db.from("config_global_obraxis").select("ia_habilitada,ia_proveedor,ia_modelo,ia_archivo_max_mb").eq("id",1).maybeSingle(),db.from("ia_config_empresas").select("*").eq("empresa",profile.empresa).maybeSingle()]);
  if(globalConfig?.ia_habilitada===false)return json({error:"Las funciones de IA están deshabilitadas globalmente."},503);
  if(globalConfig?.ia_proveedor&&String(globalConfig.ia_proveedor).toLowerCase()!=="openai")return json({error:"El proveedor configurado aún no admite revisión documental."},503);
  const bytes=Math.ceil(String(file_base64).length*.75),maxMb=Number(globalConfig?.ia_archivo_max_mb||10);if(bytes>maxMb*1024*1024)return json({error:`El documento supera el máximo de ${maxMb} MB.`},413);
  const model=companyConfig?.modelo||globalConfig?.ia_modelo||"gpt-4.1-mini";
  const{data:reserved,error:reserveError}=await db.rpc("ia_reservar_consumo",{p_empresa:profile.empresa,p_obra_nombre:obra_nombre||"",p_auth_user_id:authData.user.id,p_usuario:profile.nombre||profile.usuario||profile.correo,p_funcion:"revision_legal",p_modelo:model,p_reserva_usd:.06});if(reserveError)return json({error:reserveError.message},429);reservationId=reserved;
  const prompt=`Revisa el documento visible como apoyo al proceso de acreditación de faena en Chile. Documento esperado: ${documento_nombre}. Categoría: ${categoria||"empresa"}. Entidad: ${entidad_nombre||subcontratista_nombre||"no informada"}. Comprueba identidad y correspondencia, legibilidad, fechas, vigencia visible, firmas o timbres cuando correspondan, datos esenciales, coherencia interna y concordancia con el tipo solicitado. No inventes información ni declares cumplimiento legal definitivo. Si una exigencia normativa no puede comprobarse solo con el documento, indícala como Requiere revisión y explica la evidencia faltante. Cita la evidencia usando texto breve visible o página/sección. La decisión final pertenece al revisor autorizado.`;
  const filePart=mime_type.startsWith("image/")?{type:"input_image",image_url:`data:${mime_type};base64,${file_base64}`}:{type:"input_file",filename:file_name||`documento.${mime_type==="application/pdf"?"pdf":"txt"}`,file_data:`data:${mime_type};base64,${file_base64}`};
  const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${openAIKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:[{role:"user",content:[{type:"input_text",text:prompt},filePart]}],text:{format:{type:"json_schema",name:"revision_acreditacion",strict:true,schema}}})});
  const apiData=await response.json();if(!response.ok)throw new Error(apiData?.error?.message||"No fue posible revisar el documento.");const raw=apiData.output_text||apiData.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==="output_text")?.text;if(!raw)throw new Error("La IA no devolvió un análisis utilizable.");const result=JSON.parse(raw);
  const inputTokens=Number(apiData.usage?.input_tokens||0),outputTokens=Number(apiData.usage?.output_tokens||0),cost=(inputTokens*.40+outputTokens*1.60)/1_000_000;
  await db.rpc("ia_finalizar_consumo",{p_id:reservationId,p_estado:"Completado",p_tokens_entrada:inputTokens,p_tokens_salida:outputTokens,p_costo_usd:cost,p_confianza:Number(result.confianza||0),p_duracion_ms:Date.now()-started,p_error_detalle:"",p_metadatos:{mime_type,bytes,documento_clave}});
  const{data:review,error:insertError}=await db.from("acreditaciones_revisiones_ia").insert({empresa:profile.empresa,obra_nombre,subcontratista_nombre,subcontratista_rut,categoria:categoria||"empresa",entidad_nombre,documento_clave,documento_nombre,archivo_nombre:file_name,resultado:result.resultado,confianza:result.confianza,resumen:result.resumen,datos_extraidos:result.datos_extraidos,hallazgos:result.hallazgos,campos_faltantes:result.campos_faltantes,recomendacion:result.recomendacion,modelo:model,tokens_total:inputTokens+outputTokens,costo_usd:cost,ia_consumo_id:reservationId,auth_user_id:authData.user.id,revisado_por:profile.nombre||profile.usuario||profile.correo}).select().single();if(insertError)throw insertError;
  return json({data:review,usage:{tokens_total:inputTokens+outputTokens,costo_usd:cost}});
 }catch(error){if(reservationId&&db)await db.rpc("ia_finalizar_consumo",{p_id:reservationId,p_estado:"Error",p_tokens_entrada:0,p_tokens_salida:0,p_costo_usd:0,p_confianza:null,p_duracion_ms:Date.now()-started,p_error_detalle:error instanceof Error?error.message:String(error),p_metadatos:{}});return json({error:error instanceof Error?error.message:String(error)},400)}
});
