import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const origins=new Set(["https://obraxis.cl","https://www.obraxis.cl"]),cors=(o:string|null)=>({"Access-Control-Allow-Origin":o&&origins.has(o)?o:"https://www.obraxis.cl","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"});
const reply=(b:unknown,s=200,o:string|null=null)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(o),"Content-Type":"application/json"}}),clean=(v:unknown,m=300)=>String(v??"").trim().slice(0,m);
const digest=async(v:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)))).map(x=>x.toString(16).padStart(2,"0")).join("");
const rutKey=(v:unknown)=>clean(v,20).replace(/[^0-9kK]/g,"").toUpperCase();
const distance=(a:number,b:number,c:number,d:number)=>{const r=6371000,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,z=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return Math.round(r*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z)));};
Deno.serve(async(req:Request)=>{const origin=req.headers.get("Origin");if(req.method==="OPTIONS")return new Response("ok",{headers:cors(origin)});if(req.method!=="POST")return reply({error:"Método no permitido"},405,origin);const key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!key)return reply({error:"Servicio no configurado"},503,origin);const db=createClient(Deno.env.get("SUPABASE_URL")!,key,{auth:{persistSession:false}});
 try{const body=await req.json(),action=clean(body?.accion,30),token=clean(body?.token,160);if(token.length<32)return reply({error:"Código QR inválido"},404,origin);const ip=clean(req.headers.get("x-forwarded-for")?.split(",")[0]||"unknown",80),[th,ih]=await Promise.all([digest(token),digest(ip)]),since=new Date(Date.now()-15*60*1000).toISOString();const{count}=await db.from("formulario_publico_intentos").select("id",{count:"exact",head:true}).eq("token_hash",th).eq("ip_hash",ih).eq("accion",`asis_${action}`).gte("created_at",since);if((count||0)>=(action==="marcar"?10:60))return reply({error:"Demasiados intentos. Intenta más tarde."},429,origin);const log=(ok:boolean)=>db.from("formulario_publico_intentos").insert({token_hash:th,ip_hash:ih,accion:`asis_${action}`,exitoso:ok});
 const{data:work}=await db.from("obras").select("id,nombre,tipo,empresa,latitud,longitud,radio_cobertura_m").eq("asistencia_token",token).maybeSingle();if(!work){await log(false);return reply({error:"La obra no está disponible"},404,origin);}if(action==="cargar"){await log(true);return reply({obra:{id:work.id,nombre:work.nombre,tipo:work.tipo,latitud:work.latitud,longitud:work.longitud,radio_cobertura_m:work.radio_cobertura_m||200}},200,origin);}
 const rut=rutKey(body?.rut);if(rut.length<8)return reply({error:"RUT inválido"},400,origin);const{data:workers}=await db.from("maestro_personal").select("nombre,rut,cargo").eq("empresa",work.empresa).eq("obra_nombre",work.nombre);const worker=(workers||[]).find((x:any)=>rutKey(x.rut)===rut);if(!worker){await log(false);return reply({error:"El trabajador no está asignado a esta obra"},404,origin);}if(action==="validar_persona"){await log(true);return reply({trabajador:{nombre:worker.nombre,cargo:worker.cargo||""}},200,origin);}if(action!=="marcar")return reply({error:"Acción inválida"},400,origin);
 const lat=Number(body?.latitud),lng=Number(body?.longitud);let dist:null|number=null;if(work.latitud!=null&&work.longitud!=null){if(!Number.isFinite(lat)||!Number.isFinite(lng))return reply({error:"Debes habilitar tu ubicación"},400,origin);dist=distance(lat,lng,Number(work.latitud),Number(work.longitud));if(dist>Number(work.radio_cobertura_m||200))return reply({error:`Marcación fuera del radio autorizado (${dist} m)`},403,origin);}
 const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),part=(t:string)=>parts.find(x=>x.type===t)?.value||"";const localDate=`${part("year")}-${part("month")}-${part("day")}`;const{data:existing}=await db.from("asistencia_personal").select("id,ingreso,salida").eq("empresa",work.empresa).eq("obra_nombre",work.nombre).eq("rut_normalizado",rut).eq("fecha_marcacion",localDate).order("created_at",{ascending:false}).limit(1).maybeSingle();const now=new Intl.DateTimeFormat("es-CL",{timeZone:"America/Santiago",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date());let type="INGRESO";
 if(existing?.ingreso&&!existing?.salida){type="SALIDA";const{error}=await db.from("asistencia_personal").update({salida:now,latitud:lat||null,longitud:lng||null,distancia_obra_m:dist,verificado_qr:true}).eq("id",existing.id);if(error)throw error;}else{const signature=clean(body?.firma_base64,4*1024*1024)||null;const{error}=await db.from("asistencia_personal").insert({empresa:work.empresa,obra_id:work.id,obra_nombre:work.nombre,fecha_marcacion:localDate,supervisor:"Autogestión QR Móvil",trabajador:worker.nombre,rut:clean(body?.rut,20),rut_normalizado:rut,asistencia:"PRESENTE",ingreso:now,salida:null,colacion:"SI",horas_ordinarias:9,firma_base64:signature,latitud:lat||null,longitud:lng||null,distancia_obra_m:dist,verificado_qr:true});if(error)throw error;}
 await log(true);return reply({ok:true,tipo:type,trabajador:worker.nombre,obra:work.nombre,hora:now},200,origin);
 }catch(error){console.error(error);return reply({error:error instanceof Error?error.message:"Error inesperado"},500,origin);}});
