/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { MachineryActions } from '@/components/MachineryActions';
import { Badge, Card, Empty, ErrorBox, Header, Loading, Progress, Screen, Segments } from '@/components/ui';
import { WorkEntryActions } from '@/components/WorkEntryActions';
import { SimpleBars } from '@/components/SimpleBars';
import { supabase } from '@/lib/supabase';
import { colors } from '@/lib/theme';
type Row=Record<string,any>;
const tabs=[{key:'avance',label:'Avance'},{key:'equipos',label:'Maquinaria'},{key:'asistencia',label:'Asistencia'},{key:'subcontratos',label:'Subcontratos'},{key:'estadisticas',label:'Estadísticas'}];
const day=(value:any)=>String(value||'').slice(0,10);

export default function WorkDetail(){
  const{id,nombre}=useLocalSearchParams<{id:string;nombre:string}>();const{profile}=useAuth();const[tab,setTab]=useState('avance');const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[data,setData]=useState<Row>({parts:[],adv:[],equip:[],attendance:[],workers:[],sub:[],subAdv:[],subAttendance:[],subPayments:[],maintenance:[]});
  const load=async()=>{setLoading(true);setError('');try{const[p,a,e,att,w,sub,sa,sat,sep,m]=await Promise.all([
    supabase.from('partidas_obra').select('id,partida,unidad,cantidad_presupuestada,es_titulo').eq('empresa',profile!.empresa).eq('obra_id',Number(id)).order('orden'),
    supabase.from('avances_produccion_partidas').select('partida,cantidad,created_at').eq('empresa',profile!.empresa).eq('obra_id',Number(id)),
    supabase.from('inventario_maquinaria').select('*').eq('empresa',profile!.empresa).eq('obra_nombre',nombre),
    supabase.from('asistencia_personal').select('*').eq('empresa',profile!.empresa).eq('obra_nombre',nombre).order('created_at',{ascending:false}).limit(400),
    supabase.from('maestro_personal').select('id,nombre,rut,cargo').eq('empresa',profile!.empresa).eq('obra_nombre',nombre),
    supabase.from('acreditaciones_subcontratos').select('*').eq('empresa',profile!.empresa).eq('obra_asociada',nombre),
    supabase.from('subcontrato_avances').select('*').eq('empresa',profile!.empresa).eq('obra_nombre',nombre).order('fecha',{ascending:false}).limit(100),
    supabase.from('subcontrato_asistencia').select('*').eq('empresa',profile!.empresa).eq('obra_nombre',nombre).order('fecha',{ascending:false}).limit(100),
    supabase.from('subcontrato_estados_pago').select('*').eq('empresa',profile!.empresa).eq('obra_nombre',nombre).order('created_at',{ascending:false}).limit(100),
    supabase.from('maquinaria_mantenciones').select('*').eq('empresa',profile!.empresa).order('fecha',{ascending:false})
  ]);const failure=[p,a,e,att,w,sub,sa,sat,sep,m].find(result=>result.error);if(failure?.error)throw failure.error;const equipment=e.data||[];const ids=new Set(equipment.map(item=>item.id));setData({parts:p.data||[],adv:a.data||[],equip:equipment,attendance:att.data||[],workers:w.data||[],sub:sub.data||[],subAdv:sa.data||[],subAttendance:sat.data||[],subPayments:sep.data||[],maintenance:(m.data||[]).filter(item=>ids.has(item.equipo_id))})}catch(x){setError(x instanceof Error?x.message:'No fue posible cargar la obra.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[id,profile,nombre]);
  const metrics=useMemo(()=>{const real=data.parts.filter((item:Row)=>!item.es_titulo);const values=real.map((part:Row)=>{const done=data.adv.filter((advance:Row)=>advance.partida===part.partida).reduce((sum:number,advance:Row)=>sum+Number(advance.cantidad||0),0);return Math.min(100,Number(part.cantidad_presupuestada)?done/Number(part.cantidad_presupuestada)*100:0)});const latest=data.attendance.map((item:Row)=>day(item.fecha_marcacion||item.created_at)).filter(Boolean).sort().at(-1);const present=new Set(data.attendance.filter((item:Row)=>day(item.fecha_marcacion||item.created_at)===latest&&String(item.asistencia).toLowerCase().includes('pres')).map((item:Row)=>item.rut||item.trabajador));return{progress:values.length?values.reduce((sum:number,value:number)=>sum+value,0)/values.length:0,present:present.size,total:data.workers.length,latest}},[data]);
  const upcoming=useMemo(()=>data.equip.flatMap((item:Row)=>(Array.isArray(item.planes_mantencion)?item.planes_mantencion:[]).map((plan:Row)=>{const remaining=Number(plan.intervalo||0)-(Number(item.horometro_inicial||0)-Number(plan.ultima_lectura||0));return{item,plan,remaining}})).sort((a:Row,b:Row)=>a.remaining-b.remaining),[data.equip]);
  const progressByPart=useMemo(()=>data.parts.filter((part:Row)=>!part.es_titulo).map((part:Row)=>{const done=data.adv.filter((advance:Row)=>advance.partida===part.partida).reduce((sum:number,advance:Row)=>sum+Number(advance.cantidad||0),0);const value=Number(part.cantidad_presupuestada)?Math.min(100,done/Number(part.cantidad_presupuestada)*100):0;return{label:part.partida,value,display:`${value.toFixed(1)}%`,color:value>=100?colors.green:value<40?colors.orange:colors.blue}}).sort((a:Row,b:Row)=>b.value-a.value).slice(0,8),[data.parts,data.adv]);
  return <Screen refreshing={loading} onRefresh={load}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={20}/><Text style={s.backText}>Volver a obras</Text></Pressable><Header title={nombre||'Obra'} subtitle="Vista operativa en terreno" icon="business-outline"/><Segments value={tab} options={tabs} onChange={setTab}/>{(tab==='avance'||tab==='asistencia')&&<WorkEntryActions mode={tab==='avance'?'progress':'attendance'} profile={profile!} workId={Number(id)} workName={nombre||''} parts={data.parts} onSaved={load}/>}<ErrorBox text={error}/>{loading&&!data.parts.length?<Loading/>:<>
    {tab==='avance'&&(data.parts.filter((item:Row)=>!item.es_titulo).length?data.parts.filter((item:Row)=>!item.es_titulo).map((part:Row)=>{const done=data.adv.filter((advance:Row)=>advance.partida===part.partida).reduce((sum:number,advance:Row)=>sum+Number(advance.cantidad||0),0);return <Card key={part.id}><Text style={s.name}>{part.partida}</Text><Text style={s.meta}>{done.toLocaleString('es-CL')} de {Number(part.cantidad_presupuestada||0).toLocaleString('es-CL')} {part.unidad}</Text><Progress value={Number(part.cantidad_presupuestada)?done/Number(part.cantidad_presupuestada)*100:0}/></Card>}):<Empty text="La obra aún no tiene partidas cargadas."/>)}
    {tab==='equipos'&&<><View style={s.actions}><MachineryActions mode="usage" equipment={data.equip} profile={profile!} onSaved={load}/><MachineryActions mode="failure" equipment={data.equip} profile={profile!} onSaved={load}/></View>{data.equip.length?data.equip.map((item:Row)=><Card key={item.id}><Text style={s.name}>{item.tipo} · {item.patente||'S/P'}</Text><Text style={s.meta}>{item.marca||'Sin marca'} · Lectura {Number(item.horometro_inicial||0).toLocaleString('es-CL')}</Text></Card>):<Empty text="No hay equipos asignados a esta obra."/>}<Text style={s.section}>Próximas mantenciones</Text>{upcoming.length?upcoming.slice(0,8).map((entry:Row,index:number)=><Card key={`${entry.item.id}-${index}`}><Badge tone={entry.remaining<=0?'red':entry.remaining<=10?'amber':'green'}>{entry.remaining<=0?'Vencida':'Próxima'}</Badge><Text style={s.name}>{entry.item.tipo} · {entry.item.patente}</Text><Text style={s.meta}>{entry.plan.nombre||'Mantención'} · {Math.max(0,entry.remaining)} {entry.plan.unidad||'horas'} restantes</Text></Card>):<Empty text="No hay planes de mantención configurados."/>}</>}
    {tab==='asistencia'&&<Card><Text style={s.metric}>{metrics.present} de {metrics.total}</Text><Text style={s.meta}>presentes en la última jornada registrada {metrics.latest||''}</Text></Card>}
    {tab==='subcontratos'&&<>{data.sub.length?data.sub.map((item:Row)=><Card key={item.id} onPress={()=>router.push({pathname:'/subcontrato/[id]',params:{id:String(item.id),obra:nombre||'',nombre:item.empresa_nombre||'Subcontrato'}})}><View style={s.row}><View style={s.flex}><Text style={s.name}>{item.empresa_nombre||'Subcontrato'}</Text><Text style={s.meta}>{item.rut_empresa||''} · {item.estado_cumplimiento||item.estado||'Activo'}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></View></Card>):<Empty text="No hay subcontratos registrados."/>}<View style={s.stats}><Metric value={data.subAdv.length} label="Avances enviados"/><Metric value={data.subAttendance.length} label="Asistencias"/><Metric value={data.subPayments.length} label="Estados de pago"/></View></>}
    {tab==='estadisticas'&&<><Card><Text style={s.label}>Avance físico promedio</Text><Text style={s.metric}>{metrics.progress.toFixed(1)}%</Text><Progress value={metrics.progress}/></Card><View style={s.stats}><Metric value={data.equip.length} label="Equipos"/><Metric value={data.sub.length} label="Subcontratos"/></View><Card><Text style={s.section}>Avance por partida</Text>{progressByPart.length?<SimpleBars data={progressByPart} max={100}/>:<Text style={s.meta}>Sin partidas con avance.</Text>}</Card></>}
  </>}</Screen>;
}
function Metric({value,label}:{value:number;label:string}){return <Card><Text style={s.metricSmall}>{value}</Text><Text style={s.meta}>{label}</Text></Card>}
const s=StyleSheet.create({back:{flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800',color:colors.ink},actions:{flexDirection:'row',gap:8},section:{fontSize:12,fontWeight:'900',textTransform:'uppercase',color:colors.ink},row:{flexDirection:'row',alignItems:'center',gap:8},flex:{flex:1},name:{fontSize:14,fontWeight:'900',color:colors.ink},meta:{fontSize:11,color:colors.muted},metric:{fontSize:34,fontWeight:'900',color:colors.green},metricSmall:{fontSize:26,fontWeight:'900',color:colors.blue},label:{fontSize:11,fontWeight:'800',textTransform:'uppercase',color:colors.muted},stats:{flexDirection:'row',gap:10}});
