create table if not exists public.mandante_proyectos (
  id uuid primary key default gen_random_uuid(),
  empresa_mandante text not null,
  codigo text not null,
  nombre text not null,
  descripcion text,
  ubicacion text,
  administrador_contrato text,
  ito_responsable text,
  presupuesto_contractual numeric not null default 0,
  fecha_inicio date,
  fecha_termino date,
  estado text not null default 'Activo' check (estado in ('Borrador','Activo','Suspendido','Cerrado','Archivado')),
  creado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_mandante, codigo)
);

create table if not exists public.mandante_contratos (
  id uuid primary key default gen_random_uuid(),
  proyecto_id uuid not null references public.mandante_proyectos(id) on delete restrict,
  empresa_mandante text not null,
  codigo text not null,
  nombre text not null,
  rut_contratista text not null,
  empresa_contratista text not null,
  empresa_obraxis_vinculada text,
  modalidad text not null default 'Portal externo' check (modalidad in ('Empresa Obraxis','Portal externo')),
  obra_contratista_id integer references public.obras(id) on delete restrict,
  obra_contratista_nombre text,
  administrador_contrato text,
  ito_responsable text,
  contacto_nombre text,
  contacto_email text,
  presupuesto_contractual numeric not null default 0,
  fecha_inicio date,
  fecha_termino date,
  estado text not null default 'Configuracion' check (estado in ('Configuracion','Invitado','Vinculado','Activo','Suspendido','Terminado','Archivado')),
  paquetes jsonb not null default '{"avance":true,"programacion":true,"hitos":true,"estados_pago":true,"rdi":true,"libro_obra":true,"calidad":true,"prevencion":true,"documentos":true,"acreditaciones":true}'::jsonb,
  periodicidad jsonb not null default '{}'::jsonb,
  exige_acreditacion boolean not null default true,
  alcance_acreditacion jsonb not null default '{"empresa":true,"personal":true,"equipos":true}'::jsonb,
  creado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (proyecto_id, codigo)
);

create table if not exists public.mandante_eventos (
  id bigint generated by default as identity primary key,
  empresa_mandante text not null,
  proyecto_id uuid references public.mandante_proyectos(id) on delete restrict,
  contrato_id uuid references public.mandante_contratos(id) on delete restrict,
  accion text not null,
  estado_resultante text,
  actor_nombre text,
  actor_rut text,
  actor_cargo text,
  actor_empresa text,
  detalle text,
  created_at timestamptz not null default now()
);

create index if not exists mandante_proyectos_empresa_idx on public.mandante_proyectos (empresa_mandante, estado);
create index if not exists mandante_contratos_empresa_idx on public.mandante_contratos (empresa_mandante, estado);
create index if not exists mandante_contratos_rut_idx on public.mandante_contratos (rut_contratista);
create index if not exists mandante_eventos_contrato_idx on public.mandante_eventos (contrato_id, created_at desc);

alter table public.mandante_proyectos enable row level security;
alter table public.mandante_contratos enable row level security;
alter table public.mandante_eventos enable row level security;

grant select, insert, update, delete on public.mandante_proyectos, public.mandante_contratos, public.mandante_eventos to authenticated;
grant usage, select on sequence public.mandante_eventos_id_seq to authenticated;

create policy mandante_proyectos_empresa on public.mandante_proyectos
for all to authenticated
using ((select private.usuario_puede_empresa(empresa_mandante)))
with check ((select private.usuario_puede_empresa(empresa_mandante)));

create policy mandante_contratos_empresa on public.mandante_contratos
for all to authenticated
using ((select private.usuario_puede_empresa(empresa_mandante)))
with check ((select private.usuario_puede_empresa(empresa_mandante)));

create policy mandante_eventos_empresa on public.mandante_eventos
for all to authenticated
using ((select private.usuario_puede_empresa(empresa_mandante)))
with check ((select private.usuario_puede_empresa(empresa_mandante)));

