grant select, insert, update on public.subcontrato_avances, public.subcontrato_asistencia, public.subcontrato_estados_pago to authenticated;
create policy "miembros contrato ven avances" on public.subcontrato_avances for select to authenticated using (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));
create policy "colaboradora envia avances" on public.subcontrato_avances for insert to authenticated with check (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and c.estado = 'Activo' and private.obraxis_actor_can_access_company(c.empresa_colaboradora)));
create policy "contratista revisa avances" on public.subcontrato_avances for update to authenticated using (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and private.obraxis_actor_can_access_company(c.empresa_contratista))) with check (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and private.obraxis_actor_can_access_company(c.empresa_contratista)));
create policy "miembros contrato ven asistencia" on public.subcontrato_asistencia for select to authenticated using (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));
create policy "colaboradora envia asistencia" on public.subcontrato_asistencia for insert to authenticated with check (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and c.estado = 'Activo' and private.obraxis_actor_can_access_company(c.empresa_colaboradora)));
create policy "miembros contrato ven estados pago" on public.subcontrato_estados_pago for select to authenticated using (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and (private.obraxis_actor_can_access_company(c.empresa_contratista) or private.obraxis_actor_can_access_company(c.empresa_colaboradora))));
create policy "colaboradora envia estados pago" on public.subcontrato_estados_pago for insert to authenticated with check (contrato_colaborativo_id is not null and exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and c.estado = 'Activo' and private.obraxis_actor_can_access_company(c.empresa_colaboradora)));
create policy "contratista revisa estados pago" on public.subcontrato_estados_pago for update to authenticated using (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and private.obraxis_actor_can_access_company(c.empresa_contratista))) with check (exists (select 1 from public.contratos_colaborativos c where c.id = contrato_colaborativo_id and private.obraxis_actor_can_access_company(c.empresa_contratista)));;
