create table if not exists public.maquinaria_arriendos (
  id bigint generated by default as identity primary key,
  empresa text not null,
  equipo_id bigint not null references public.inventario_maquinaria(id) on delete restrict,
  equipo_tipo text not null,
  equipo_patente text,
  empresa_arrendataria text not null,
  rut_empresa text,
  obra_cliente text,
  direccion_obra text,
  contacto_nombre text,
  contacto_telefono text,
  contacto_email text,
  tarifa_diaria numeric not null default 0 check (tarifa_diaria >= 0),
  tarifa_monto numeric not null default 0 check (tarifa_monto >= 0),
  unidad_tarifa text not null default '$/día',
  aplica_tarifa_minima boolean not null default false,
  unidad_tarifa_minima text not null default 'hrs/día',
  monto_tarifa_minima numeric not null default 0 check (monto_tarifa_minima >= 0),
  fecha_inicio date not null,
  fecha_fin date not null,
  observaciones text,
  estado text not null default 'Activo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint maquinaria_arriendos_fechas_validas check (fecha_fin >= fecha_inicio)
);

create index if not exists maquinaria_arriendos_empresa_fechas_idx
  on public.maquinaria_arriendos (empresa, fecha_inicio desc, fecha_fin desc);
create index if not exists maquinaria_arriendos_equipo_fechas_idx
  on public.maquinaria_arriendos (equipo_id, fecha_inicio, fecha_fin);

create table if not exists public.arriendos_maquinaria (
  id bigint generated by default as identity primary key,
  empresa text not null,
  obra_id bigint references public.obras(id) on delete restrict,
  obra_nombre text not null,
  equipo text not null,
  patente text,
  proveedor text not null,
  costo numeric not null default 0 check (costo >= 0),
  unidad_costo text not null default '$/mes',
  tipo_condicion_minima text not null default 'sin_minimo',
  cantidad_minima numeric not null default 0 check (cantidad_minima >= 0),
  modalidad_dias text not null default 'laborales',
  fecha_inicio date,
  fecha_termino date,
  observaciones text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint arriendos_maquinaria_fechas_validas
    check (fecha_inicio is null or fecha_termino is null or fecha_termino >= fecha_inicio)
);

create index if not exists arriendos_maquinaria_empresa_obra_idx
  on public.arriendos_maquinaria (empresa, obra_id, created_at desc);
create index if not exists arriendos_maquinaria_empresa_obra_nombre_idx
  on public.arriendos_maquinaria (empresa, obra_nombre, created_at desc);

alter table public.maquinaria_arriendos enable row level security;
alter table public.arriendos_maquinaria enable row level security;

drop policy if exists maquinaria_arriendos_empresa on public.maquinaria_arriendos;
create policy maquinaria_arriendos_empresa
on public.maquinaria_arriendos for all to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = maquinaria_arriendos.empresa or lower(u.empresa) = 'obraxis')
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = maquinaria_arriendos.empresa or lower(u.empresa) = 'obraxis')
  )
);

drop policy if exists arriendos_maquinaria_empresa on public.arriendos_maquinaria;
create policy arriendos_maquinaria_empresa
on public.arriendos_maquinaria for all to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = arriendos_maquinaria.empresa or lower(u.empresa) = 'obraxis')
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = arriendos_maquinaria.empresa or lower(u.empresa) = 'obraxis')
  )
);

revoke all on public.maquinaria_arriendos, public.arriendos_maquinaria from anon;
grant select, insert, update, delete on public.maquinaria_arriendos, public.arriendos_maquinaria to authenticated;
grant usage, select on sequence public.maquinaria_arriendos_id_seq to authenticated;
grant usage, select on sequence public.arriendos_maquinaria_id_seq to authenticated;

comment on table public.maquinaria_arriendos is
  'Contratos de equipos propios entregados en arriendo a terceros.';
comment on table public.arriendos_maquinaria is
  'Equipos externos tomados en arriendo e imputados a una obra.';
