create table if not exists public.obra_cuadrillas (
  id bigint generated by default as identity primary key,
  empresa text not null,
  obra_id integer references public.obras(id) on delete restrict,
  obra_nombre text not null,
  nombre text not null,
  lider text,
  especialidad text,
  miembros jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists obra_cuadrillas_empresa_obra_idx on public.obra_cuadrillas (empresa, obra_id);
alter table public.obra_cuadrillas enable row level security;
drop policy if exists obra_cuadrillas_empresa on public.obra_cuadrillas;
create policy obra_cuadrillas_empresa on public.obra_cuadrillas for all to authenticated
using (private.obraxis_actor_can_access_company(empresa))
with check (private.obraxis_actor_can_access_company(empresa));
revoke all on public.obra_cuadrillas from anon;
grant select, insert, update, delete on public.obra_cuadrillas to authenticated;
grant usage, select on sequence public.obra_cuadrillas_id_seq to authenticated;

create table if not exists public.obra_liquidaciones (
  id bigint generated by default as identity primary key,
  empresa text not null,
  obra_id integer references public.obras(id) on delete restrict,
  obra_nombre text not null,
  trabajador text not null,
  periodo text not null,
  num_folio text,
  monto_real numeric not null default 0 check (monto_real >= 0),
  partida text,
  created_at timestamptz not null default now()
);
create index if not exists obra_liquidaciones_empresa_obra_idx on public.obra_liquidaciones (empresa, obra_id, periodo);
alter table public.obra_liquidaciones enable row level security;
drop policy if exists obra_liquidaciones_empresa on public.obra_liquidaciones;
create policy obra_liquidaciones_empresa on public.obra_liquidaciones for all to authenticated
using (private.obraxis_actor_can_access_company(empresa))
with check (private.obraxis_actor_can_access_company(empresa));
revoke all on public.obra_liquidaciones from anon;
grant select, insert, update, delete on public.obra_liquidaciones to authenticated;
grant usage, select on sequence public.obra_liquidaciones_id_seq to authenticated;;
