alter table public.avances_produccion_partidas
  add column if not exists partida_id integer references public.partidas_obra(id) on delete restrict,
  add column if not exists cuadrilla_id bigint references public.obra_cuadrillas(id) on delete restrict,
  add column if not exists cuadrilla_nombre text,
  add column if not exists cuadrilla_miembros jsonb not null default '[]'::jsonb,
  add column if not exists horas_cuadrilla numeric check (horas_cuadrilla is null or horas_cuadrilla > 0);

create index if not exists avances_partida_cuadrilla_fecha_idx
  on public.avances_produccion_partidas (empresa, obra_id, cuadrilla_id, created_at);

create table if not exists public.obra_liquidaciones_partidas (
  id bigint generated by default as identity primary key,
  empresa text not null,
  liquidacion_id bigint not null references public.obra_liquidaciones(id) on delete cascade,
  nomina_id bigint not null references public.rrhh_nominas_mensuales(id) on delete restrict,
  nomina_item_id bigint not null references public.rrhh_nomina_items(id) on delete restrict,
  trabajador_id integer references public.maestro_personal(id) on delete restrict,
  obra_id integer not null references public.obras(id) on delete restrict,
  partida_id integer references public.partidas_obra(id) on delete restrict,
  partida text not null,
  cuadrilla_id bigint references public.obra_cuadrillas(id) on delete restrict,
  cuadrilla_nombre text,
  monto_imputado numeric not null default 0 check (monto_imputado >= 0),
  porcentaje_imputacion numeric not null default 0 check (porcentaje_imputacion between 0 and 100),
  ponderador numeric not null default 0,
  criterio text not null,
  created_at timestamptz not null default now()
);

create index if not exists obra_liquidaciones_partidas_nomina_idx
  on public.obra_liquidaciones_partidas (nomina_id, nomina_item_id);
create index if not exists obra_liquidaciones_partidas_obra_partida_idx
  on public.obra_liquidaciones_partidas (empresa, obra_id, partida_id);

alter table public.obra_liquidaciones_partidas enable row level security;
drop policy if exists obra_liquidaciones_partidas_empresa on public.obra_liquidaciones_partidas;
create policy obra_liquidaciones_partidas_empresa on public.obra_liquidaciones_partidas
  for all to authenticated
  using (private.obraxis_actor_can_access_company(empresa))
  with check (private.obraxis_actor_can_access_company(empresa));

revoke all on public.obra_liquidaciones_partidas from anon;
grant select, insert, update, delete on public.obra_liquidaciones_partidas to authenticated;
grant usage, select on sequence public.obra_liquidaciones_partidas_id_seq to authenticated;

create or replace function public.distribuir_nomina_a_obras(p_nomina_id bigint)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_empresa text;
  v_periodo text;
  v_inicio date;
  v_fin date;
  v_creadas integer := 0;
  v_detalles integer := 0;
  v_sin_destino integer := 0;
  v_sin_partida integer := 0;
begin
  select empresa, periodo into v_empresa, v_periodo
  from public.rrhh_nominas_mensuales
  where id = p_nomina_id and estado = 'Cerrada';

  if v_empresa is null then raise exception 'Nómina cerrada no encontrada o sin acceso'; end if;
  v_inicio := (v_periodo || '-01')::date;
  v_fin := (v_inicio + interval '1 month - 1 day')::date;

  delete from public.obra_liquidaciones_partidas
  where nomina_id = p_nomina_id and nomina_item_id is not null;
  delete from public.obra_liquidaciones
  where nomina_id = p_nomina_id and nomina_item_id is not null;

  with
  items as (
    select i.id item_id, i.trabajador_id, i.trabajador_nombre, i.trabajador_rut,
      greatest(0, round(coalesce(nullif(i.calculo ->> 'employerCost', '')::numeric,
        nullif(i.calculo ->> 'totalAssets', '')::numeric, i.sueldo_liquido, 0))) monto_total,
      upper(regexp_replace(coalesce(i.trabajador_rut, ''), '[^0-9kK]', '', 'g')) rut_normalizado,
      i.obra_nombre obra_ficha
    from public.rrhh_nomina_items i where i.nomina_id = p_nomina_id
  ),
  dias_habiles as (
    select i.*, d::date fecha from items i
    cross join lateral generate_series(v_inicio, v_fin, interval '1 day') d
    where extract(isodow from d) between 1 and 5
  ),
  asistencias as (
    select distinct d.item_id, d.fecha, a.obra_id, coalesce(a.obra_nombre, o.nombre) obra_nombre
    from dias_habiles d
    join public.asistencia_personal a on a.empresa = v_empresa and a.fecha_marcacion = d.fecha
      and upper(coalesce(a.asistencia, 'PRESENTE')) = 'PRESENTE'
      and ((d.rut_normalizado <> '' and a.rut_normalizado = d.rut_normalizado)
        or (d.rut_normalizado = '' and lower(btrim(coalesce(a.trabajador, ''))) = lower(btrim(d.trabajador_nombre))))
    join public.obras o on o.id = a.obra_id and o.empresa = v_empresa
  ),
  asistencia_con_peso as (
    select a.*, 1.0 / count(*) over (partition by a.item_id, a.fecha) peso from asistencias a
  ),
  asignaciones as (
    select d.item_id, d.fecha, o.id obra_id, o.nombre obra_nombre, 1.0::numeric peso
    from dias_habiles d
    join public.rrhh_asignaciones_personal ap on ap.empresa = v_empresa and ap.trabajador_id = d.trabajador_id
      and ap.obra_nombre is not null and ap.fecha_inicio <= d.fecha and coalesce(ap.fecha_termino, v_fin) >= d.fecha
    join public.obras o on o.empresa = v_empresa and lower(btrim(o.nombre)) = lower(btrim(ap.obra_nombre))
    where not exists (select 1 from asistencias a where a.item_id = d.item_id and a.fecha = d.fecha)
  ),
  base_diaria as (
    select item_id, fecha, obra_id, obra_nombre, peso, 'Asistencia'::text criterio from asistencia_con_peso
    union all
    select item_id, fecha, obra_id, obra_nombre, peso, 'Asignación'::text criterio from asignaciones
  ),
  base_obra as (
    select item_id, obra_id, obra_nombre, sum(peso)::numeric dias,
      case when bool_or(criterio = 'Asistencia') then 'Asistencia y asignaciones' else 'Historial de asignaciones' end criterio
    from base_diaria group by item_id, obra_id, obra_nombre
  ),
  fallback as (
    select i.item_id, o.id obra_id, o.nombre obra_nombre, 1::numeric dias,
      'Ficha vigente sin detalle diario'::text criterio
    from items i join public.obras o on o.empresa = v_empresa and lower(btrim(o.nombre)) = lower(btrim(i.obra_ficha))
    where not exists (select 1 from base_obra b where b.item_id = i.item_id)
  ),
  bases as (select * from base_obra union all select * from fallback),
  calculo as (
    select b.*, i.trabajador_id, i.trabajador_nombre, i.monto_total,
      sum(b.dias) over (partition by b.item_id) total_dias,
      floor(i.monto_total * b.dias / nullif(sum(b.dias) over (partition by b.item_id), 0)) monto_base,
      row_number() over (partition by b.item_id order by b.dias desc, b.obra_id) orden
    from bases b join items i on i.item_id = b.item_id
  ),
  ajuste as (
    select c.*, (c.monto_total - sum(c.monto_base) over (partition by c.item_id))::integer residuo
    from calculo c
  )
  insert into public.obra_liquidaciones (
    empresa, obra_id, obra_nombre, trabajador, periodo, num_folio, monto_real, partida,
    nomina_id, nomina_item_id, trabajador_id, monto_liquidacion_total,
    dias_imputados, porcentaje_imputacion, criterio_imputacion
  )
  select v_empresa, a.obra_id, a.obra_nombre, a.trabajador_nombre, v_periodo,
    'NOM-' || p_nomina_id || '-' || a.item_id,
    a.monto_base + case when a.orden <= a.residuo then 1 else 0 end,
    'Distribución pendiente', p_nomina_id, a.item_id, a.trabajador_id, a.monto_total,
    round(a.dias, 2), round(a.dias * 100 / nullif(a.total_dias, 0), 4), a.criterio
  from ajuste a;

  get diagnostics v_creadas = row_count;

  with reportes as (
    select l.id liquidacion_id, l.empresa, l.nomina_id, l.nomina_item_id, l.trabajador_id,
      l.trabajador, l.obra_id, l.monto_real,
      a.partida_id, a.partida, a.cuadrilla_id, a.cuadrilla_nombre,
      sum(coalesce(a.horas_cuadrilla, 1))::numeric ponderador
    from public.obra_liquidaciones l
    join public.avances_produccion_partidas a
      on a.empresa = l.empresa and a.obra_id = l.obra_id
      and (a.created_at at time zone 'America/Santiago')::date between v_inicio and v_fin
      and a.cuadrilla_id is not null
      and exists (
        select 1 from jsonb_array_elements_text(a.cuadrilla_miembros) miembro
        where lower(btrim(miembro)) = lower(btrim(l.trabajador))
      )
    where l.nomina_id = p_nomina_id
    group by l.id, l.empresa, l.nomina_id, l.nomina_item_id, l.trabajador_id,
      l.trabajador, l.obra_id, l.monto_real, a.partida_id, a.partida, a.cuadrilla_id, a.cuadrilla_nombre
  ),
  pesos as (
    select r.*, sum(r.ponderador) over (partition by r.liquidacion_id) total_ponderador,
      floor(r.monto_real * r.ponderador / nullif(sum(r.ponderador) over (partition by r.liquidacion_id), 0)) monto_base,
      row_number() over (partition by r.liquidacion_id order by r.ponderador desc, r.partida, r.cuadrilla_id) orden
    from reportes r
  ),
  ajustados as (
    select p.*, (p.monto_real - sum(p.monto_base) over (partition by p.liquidacion_id))::integer residuo
    from pesos p
  ),
  con_reportes as (
    select empresa, liquidacion_id, nomina_id, nomina_item_id, trabajador_id, obra_id,
      partida_id, partida, cuadrilla_id, cuadrilla_nombre,
      monto_base + case when orden <= residuo then 1 else 0 end monto_imputado,
      round(ponderador * 100 / nullif(total_ponderador, 0), 4) porcentaje,
      ponderador,
      'Avances de cuadrilla: horas o jornadas reportadas'::text criterio
    from ajustados
  ),
  sin_reportes as (
    select l.empresa, l.id liquidacion_id, l.nomina_id, l.nomina_item_id, l.trabajador_id, l.obra_id,
      null::integer partida_id, 'Gastos Generales de Obra'::text partida,
      null::bigint cuadrilla_id, null::text cuadrilla_nombre, l.monto_real monto_imputado,
      100::numeric porcentaje, 1::numeric ponderador,
      'Sin avance de cuadrilla vinculable en el período'::text criterio
    from public.obra_liquidaciones l
    where l.nomina_id = p_nomina_id
      and not exists (select 1 from reportes r where r.liquidacion_id = l.id)
  )
  insert into public.obra_liquidaciones_partidas (
    empresa, liquidacion_id, nomina_id, nomina_item_id, trabajador_id, obra_id,
    partida_id, partida, cuadrilla_id, cuadrilla_nombre, monto_imputado,
    porcentaje_imputacion, ponderador, criterio
  )
  select * from con_reportes
  union all
  select * from sin_reportes;

  get diagnostics v_detalles = row_count;

  update public.obra_liquidaciones l
  set partida = case
    when d.total = 1 then d.unica_partida
    else d.total || ' partidas según avance de cuadrillas'
  end
  from (
    select liquidacion_id, count(*) total, min(partida) unica_partida
    from public.obra_liquidaciones_partidas
    where nomina_id = p_nomina_id
    group by liquidacion_id
  ) d
  where l.id = d.liquidacion_id;

  select count(*) into v_sin_destino from public.rrhh_nomina_items i
  where i.nomina_id = p_nomina_id
    and not exists (select 1 from public.obra_liquidaciones l where l.nomina_item_id = i.id);
  select count(*) into v_sin_partida from public.obra_liquidaciones_partidas d
  where d.nomina_id = p_nomina_id and d.partida_id is null;

  return jsonb_build_object(
    'nomina_id', p_nomina_id,
    'imputaciones_obras', v_creadas,
    'imputaciones_partidas', v_detalles,
    'trabajadores_sin_destino', v_sin_destino,
    'imputaciones_sin_partida', v_sin_partida
  );
end;
$$;

revoke all on function public.distribuir_nomina_a_obras(bigint) from public, anon;
grant execute on function public.distribuir_nomina_a_obras(bigint) to authenticated;

comment on function public.distribuir_nomina_a_obras(bigint) is
  'Distribuye nómina por obra y luego por partidas según avances y fotografías de integrantes de cuadrilla.';
