-- Canal movil del Centro de Notificaciones Obraxis.
alter table public.notificaciones_reglas
  add column if not exists canal_push boolean not null default false;

create table if not exists public.notificaciones_dispositivos (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  perfil_id text not null,
  empresa text not null,
  expo_push_token text not null unique,
  dispositivo_id text not null,
  plataforma text not null check (plataforma in ('android','ios')),
  app_version text,
  activo boolean not null default true,
  ultimo_acceso_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (auth_user_id, empresa, dispositivo_id)
);

create index if not exists notificaciones_dispositivos_usuario_idx
  on public.notificaciones_dispositivos (auth_user_id, empresa, activo);

create table if not exists public.notificaciones_lecturas (
  entrega_id bigint not null references public.notificaciones_entregas(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  leida_at timestamptz not null default now(),
  primary key (entrega_id, auth_user_id)
);
create index if not exists notificaciones_lecturas_usuario_idx
  on public.notificaciones_lecturas (auth_user_id, leida_at desc);

create table if not exists public.notificaciones_push_entregas (
  id bigint generated by default as identity primary key,
  entrega_id bigint not null references public.notificaciones_entregas(id) on delete cascade,
  dispositivo_id uuid not null references public.notificaciones_dispositivos(id) on delete cascade,
  estado text not null default 'Pendiente' check (estado in ('Pendiente','Enviada','Error','Omitida')),
  expo_ticket_id text,
  error_detalle text,
  enviada_at timestamptz,
  created_at timestamptz not null default now(),
  unique (entrega_id, dispositivo_id)
);

create index if not exists notificaciones_push_entregas_estado_idx
  on public.notificaciones_push_entregas (estado, created_at desc);
create index if not exists notificaciones_push_entregas_dispositivo_idx
  on public.notificaciones_push_entregas (dispositivo_id, created_at desc);

alter table public.notificaciones_dispositivos enable row level security;
alter table public.notificaciones_lecturas enable row level security;
alter table public.notificaciones_push_entregas enable row level security;

drop policy if exists notificaciones_dispositivos_propios on public.notificaciones_dispositivos;
create policy notificaciones_dispositivos_propios on public.notificaciones_dispositivos
for all to authenticated
using ((select auth.uid()) = auth_user_id)
with check (
  (select auth.uid()) = auth_user_id
  and exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and u.id::text = perfil_id
      and lower(u.empresa) = lower(notificaciones_dispositivos.empresa)
  )
);

drop policy if exists notificaciones_lecturas_propias on public.notificaciones_lecturas;
create policy notificaciones_lecturas_propias on public.notificaciones_lecturas
for all to authenticated
using ((select auth.uid()) = auth_user_id)
with check ((select auth.uid()) = auth_user_id);

drop policy if exists notificaciones_push_propias on public.notificaciones_push_entregas;
create policy notificaciones_push_propias on public.notificaciones_push_entregas
for select to authenticated
using (
  exists (
    select 1 from public.notificaciones_dispositivos d
    where d.id = notificaciones_push_entregas.dispositivo_id
      and d.auth_user_id = (select auth.uid())
  )
);

revoke all on public.notificaciones_dispositivos, public.notificaciones_lecturas,
  public.notificaciones_push_entregas from anon;
grant select, insert, update, delete on public.notificaciones_dispositivos,
  public.notificaciones_lecturas to authenticated;
grant select on public.notificaciones_push_entregas to authenticated;

comment on table public.notificaciones_dispositivos is
  'Dispositivos moviles autenticados habilitados para recibir notificaciones de su empresa.';
comment on table public.notificaciones_push_entregas is
  'Auditoria por dispositivo del canal push, sin almacenar respuestas ni documentos sensibles.';
