create schema if not exists private;

create table if not exists public.auditoria_plataforma (
  id bigint generated by default as identity primary key,
  empresa text not null,
  obra_nombre text,
  modulo text not null,
  categoria text not null default 'operacion',
  accion text not null,
  descripcion text,
  entidad_tipo text,
  entidad_id text,
  actor_auth_user_id uuid,
  actor_usuario text,
  actor_nombre text,
  actor_rol text,
  actor_empresa text,
  origen text not null default 'plataforma',
  resultado text not null default 'exitoso',
  nivel text not null default 'informativo',
  metadatos jsonb not null default '{}'::jsonb,
  source_table text,
  source_id text,
  created_at timestamptz not null default now(),
  constraint auditoria_plataforma_resultado_check check (resultado in ('exitoso','fallido','pendiente','observado')),
  constraint auditoria_plataforma_nivel_check check (nivel in ('informativo','atencion','critico'))
);

create unique index if not exists auditoria_plataforma_source_uidx
  on public.auditoria_plataforma (source_table, source_id)
  where source_table is not null and source_id is not null;
create index if not exists auditoria_plataforma_empresa_fecha_idx on public.auditoria_plataforma (empresa, created_at desc);
create index if not exists auditoria_plataforma_obra_fecha_idx on public.auditoria_plataforma (obra_nombre, created_at desc);
create index if not exists auditoria_plataforma_modulo_fecha_idx on public.auditoria_plataforma (modulo, created_at desc);
create index if not exists auditoria_plataforma_actor_fecha_idx on public.auditoria_plataforma (actor_auth_user_id, created_at desc);

alter table public.auditoria_plataforma enable row level security;
revoke all on public.auditoria_plataforma from anon;
revoke insert, update, delete on public.auditoria_plataforma from authenticated;
grant select on public.auditoria_plataforma to authenticated;

create or replace function private.usuario_puede_ver_auditoria(p_empresa text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.usuarios u
    left join public.roles r on r.empresa = u.empresa and r.nombre = u.rol and coalesce(r.archivado, false) = false
    where u.auth_user_id = (select auth.uid())
      and (
        (u.empresa = 'Obraxis' and lower(coalesce(u.rol_base, u.rol, '')) in ('superusuario','superadmin'))
        or (
          u.empresa = p_empresa
          and (
            coalesce((u.permisos ->> 'admin.auditoria.ver')::boolean, false)
            or coalesce((r.permisos ->> 'admin.auditoria.ver')::boolean, false)
            or lower(coalesce(u.rol_base, u.rol, '')) in ('superusuario','superadmin','administrador','admin','gerencia')
          )
        )
      )
  );
$$;
revoke all on function private.usuario_puede_ver_auditoria(text) from public, anon, authenticated;
grant usage on schema private to authenticated;
grant execute on function private.usuario_puede_ver_auditoria(text) to authenticated;

drop policy if exists auditoria_select_autorizada on public.auditoria_plataforma;
create policy auditoria_select_autorizada on public.auditoria_plataforma
  for select to authenticated
  using ((select private.usuario_puede_ver_auditoria(empresa)));

create or replace function private.registrar_auditoria_cambio()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  payload jsonb := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  previous_payload jsonb := case when tg_op = 'UPDATE' then to_jsonb(old) else '{}'::jsonb end;
  v_empresa text;
  v_obra text;
  v_actor record;
  v_id text;
  v_modulo text := coalesce(tg_argv[0], tg_table_name);
  v_categoria text := coalesce(tg_argv[1], 'operacion');
  v_action text;
  v_changed text[];
begin
  v_empresa := coalesce(payload->>'empresa', payload->>'empresa_mandante', payload->>'empresa_contratista', payload->>'actor_empresa');
  if v_empresa is null or btrim(v_empresa) = '' then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;
  v_obra := coalesce(payload->>'obra_nombre', payload->>'obra', payload->>'proyecto_nombre');
  v_id := coalesce(payload->>'id', payload->>'codigo', payload->>'folio');
  v_action := case tg_op when 'INSERT' then 'creado' when 'UPDATE' then 'actualizado' else 'eliminado' end;

  select u.usuario, u.nombre, coalesce(u.rol_base, u.rol) as rol, u.empresa
    into v_actor
    from public.usuarios u where u.auth_user_id = (select auth.uid()) limit 1;

  if tg_op = 'UPDATE' then
    select array_agg(k order by k) into v_changed
    from jsonb_object_keys(payload) k
    where payload->k is distinct from previous_payload->k
      and k not in ('updated_at','contrasena','token','clave','api_key','respuesta','pregunta','contenido','archivo_base64','logo_base64');
  end if;

  insert into public.auditoria_plataforma (
    empresa, obra_nombre, modulo, categoria, accion, descripcion,
    entidad_tipo, entidad_id, actor_auth_user_id, actor_usuario,
    actor_nombre, actor_rol, actor_empresa, origen, resultado, nivel,
    metadatos, source_table, source_id, created_at
  ) values (
    v_empresa, v_obra, v_modulo, v_categoria, v_action,
    initcap(replace(tg_table_name, '_', ' ')) || ' ' || v_action,
    tg_table_name, v_id, (select auth.uid()), v_actor.usuario,
    coalesce(v_actor.nombre, payload->>'actor_nombre', payload->>'actor'),
    v_actor.rol, coalesce(v_actor.empresa, payload->>'actor_empresa', v_empresa),
    case when (select auth.uid()) is null then 'automatizacion' else 'plataforma' end,
    'exitoso', 'informativo',
    jsonb_strip_nulls(jsonb_build_object('campos_modificados', to_jsonb(v_changed), 'estado', coalesce(payload->>'estado', payload->>'estado_destino'))),
    tg_table_name, case when v_id is null then null else tg_op || ':' || v_id || ':' || coalesce(payload->>'updated_at', payload->>'created_at', clock_timestamp()::text) end,
    coalesce((payload->>'created_at')::timestamptz, now())
  ) on conflict do nothing;
  if tg_op = 'DELETE' then return old; else return new; end if;
exception when others then
  -- La auditorÃ­a nunca debe bloquear la operaciÃ³n de negocio.
  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;
revoke all on function private.registrar_auditoria_cambio() from public, anon, authenticated;

do $$
declare r record;
begin
  for r in
    select * from (values
      ('obras','obras','obra'), ('avances_produccion_partidas','avances','obra'),
      ('estados_pago_obra','estados_pago','obra'), ('libro_obra_digital','libro_obra','obra'),
      ('calidad_pac','calidad','obra'), ('calidad_rdi','calidad','obra'),
      ('calidad_no_conformidades','calidad','obra'), ('calidad_recepciones_partidas','calidad','obra'),
      ('prevencion_respuestas','prevencion','obra'), ('prevencion_cumplimiento_registros','prevencion','obra'),
      ('inventario_maquinaria','maquinaria','operacion'), ('maquinaria_mantenciones','maquinaria','operacion'),
      ('maquinaria_fallas','maquinaria','operacion'), ('maquinaria_reservas','maquinaria','operacion'),
      ('maestro_personal','rrhh','operacion'), ('asistencia_personal','rrhh','obra'),
      ('bodega_movimientos','bodega','operacion'), ('gastos_rendiciones','gastos','operacion'),
      ('dte_documentos_operacion','facturacion','tributario'), ('dte_eventos','facturacion','tributario'),
      ('clientes_portal_eventos','clientes','portal'), ('contratos_colaborativos_eventos','colaboracion','contrato'),
      ('mandante_eventos','mandante','contrato'), ('subcontrato_avances','subcontratos','obra'),
      ('subcontrato_asistencia','subcontratos','obra'), ('subcontrato_estados_pago','subcontratos','obra'),
      ('ia_consumos','ia','inteligencia_artificial'), ('copiloto_obra_consultas','ox','inteligencia_artificial'),
      ('ox_consultas_modulo','ox','inteligencia_artificial'), ('usuarios','administracion','seguridad'),
      ('roles','administracion','seguridad'), ('config_empresa','administracion','configuracion')
    ) as x(tabla, modulo, categoria)
    where to_regclass('public.' || x.tabla) is not null
  loop
    execute format('drop trigger if exists trg_auditoria_general on public.%I', r.tabla);
    execute format('create trigger trg_auditoria_general after insert or update or delete on public.%I for each row execute function private.registrar_auditoria_cambio(%L,%L)', r.tabla, r.modulo, r.categoria);
  end loop;
end $$;

-- Integra actividad histÃ³rica reciente sin copiar contenidos sensibles de IA.
insert into public.auditoria_plataforma (empresa, obra_nombre, modulo, categoria, accion, descripcion, entidad_tipo, entidad_id, actor_auth_user_id, actor_usuario, actor_nombre, actor_empresa, origen, resultado, metadatos, source_table, source_id, created_at)
select empresa, obra_nombre, 'ia', 'inteligencia_artificial', funcion,
       'EjecuciÃ³n de IA: ' || funcion, 'ia_consumos', id::text, auth_user_id, usuario, usuario, empresa,
       case when funcion ilike '%copiloto%' or funcion ilike '%ox%' then 'ox' else 'asistente_ia' end,
       case when lower(estado) in ('error','fallido') then 'fallido' else 'exitoso' end,
       jsonb_strip_nulls(jsonb_build_object('modelo', modelo, 'tokens_total', tokens_total, 'costo_usd', costo_usd, 'duracion_ms', duracion_ms)),
       'ia_consumos', id::text, created_at
from public.ia_consumos where created_at >= now() - interval '90 days'
on conflict do nothing;

insert into public.auditoria_plataforma (empresa, obra_nombre, modulo, categoria, accion, descripcion, entidad_tipo, entidad_id, actor_nombre, actor_empresa, origen, source_table, source_id, created_at)
select empresa, obra_nombre, 'bitacora', coalesce(categoria,'obra'), accion, detalle, 'bitacora_eventos_obra', id::text, actor, empresa, 'plataforma', 'bitacora_eventos_obra', id::text, created_at
from public.bitacora_eventos_obra where created_at >= now() - interval '90 days'
on conflict do nothing;

comment on table public.auditoria_plataforma is 'Registro transversal, multiempresa e inmutable de movimientos de Obraxis. No almacena documentos ni contenido de conversaciones IA.';

;
