create table if not exists public.contactos_publicos (
  id bigint generated by default as identity primary key, empresa text not null default 'Obraxis' check (empresa = 'Obraxis'),
  nombre text not null, empresa_interesada text, correo text not null, telefono text, mensaje text not null,
  estado text not null default 'nuevo' check (estado in ('nuevo','contactado','cotizacion_enviada','cerrado','descartado')),
  responsable_auth_user_id uuid references auth.users(id) on delete set null, responsable_nombre text, notas_internas text,
  origen text not null default 'landing_obraxis', resend_id text, ip_hash text, contactado_at timestamptz, cerrado_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists contactos_publicos_estado_fecha_idx on public.contactos_publicos (estado, created_at desc);
create index if not exists contactos_publicos_correo_idx on public.contactos_publicos (lower(correo));
alter table public.contactos_publicos enable row level security;
revoke all on public.contactos_publicos from anon;
grant select, update on public.contactos_publicos to authenticated;
revoke insert, delete, truncate, references, trigger on public.contactos_publicos from authenticated;
create or replace function private.usuario_puede_gestionar_contactos()
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select exists (
    select 1 from public.usuarios u
    left join public.roles r on r.empresa = u.empresa and r.nombre = u.rol and coalesce(r.archivado, false) = false
    where u.auth_user_id = (select auth.uid()) and u.empresa = 'Obraxis'
      and (lower(coalesce(u.rol_base, u.rol, '')) in ('superusuario','superadmin','administrador','admin','gerencia')
        or coalesce((u.permisos ->> 'admin.contactos.ver')::boolean, false)
        or coalesce((r.permisos ->> 'admin.contactos.ver')::boolean, false))
  );
$$;
revoke all on function private.usuario_puede_gestionar_contactos() from public, anon, authenticated;
grant usage on schema private to authenticated;
grant execute on function private.usuario_puede_gestionar_contactos() to authenticated;
create policy contactos_publicos_select on public.contactos_publicos for select to authenticated using ((select private.usuario_puede_gestionar_contactos()));
create policy contactos_publicos_update on public.contactos_publicos for update to authenticated
using ((select private.usuario_puede_gestionar_contactos())) with check ((select private.usuario_puede_gestionar_contactos()) and empresa = 'Obraxis');
create or replace function private.actualizar_contacto_publico()
returns trigger language plpgsql security invoker set search_path = public, pg_temp as $$
begin
 new.updated_at := now();
 if new.estado = 'contactado' and old.estado is distinct from new.estado then new.contactado_at := now(); end if;
 if new.estado in ('cerrado','descartado') and old.estado is distinct from new.estado then new.cerrado_at := now(); end if;
 return new;
end;
$$;
create trigger trg_contactos_publicos_updated before update on public.contactos_publicos for each row execute function private.actualizar_contacto_publico();
comment on table public.contactos_publicos is 'Bandeja comercial de solicitudes públicas recibidas desde obraxis.cl.';;
