CREATE TABLE IF NOT EXISTS public.rrhh_formatos_documentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT NOT NULL,
  titulo TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'Contrato Indefinido',
  contenido TEXT NOT NULL,
  archivo_nombre TEXT,
  variables JSONB NOT NULL DEFAULT '[]'::jsonb,
  advertencias JSONB NOT NULL DEFAULT '[]'::jsonb,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  estado TEXT NOT NULL DEFAULT 'Vigente' CHECK (estado IN ('Borrador','Vigente','Archivado')),
  actualizado_por TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS rrhh_formatos_documentos_empresa_idx
  ON public.rrhh_formatos_documentos (empresa, estado, titulo);

ALTER TABLE public.rrhh_formatos_documentos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rrhh_formatos_select ON public.rrhh_formatos_documentos;
CREATE POLICY rrhh_formatos_select ON public.rrhh_formatos_documentos FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = (SELECT auth.uid()) AND (u.empresa = rrhh_formatos_documentos.empresa OR lower(u.empresa) = 'obraxis')));

DROP POLICY IF EXISTS rrhh_formatos_insert ON public.rrhh_formatos_documentos;
CREATE POLICY rrhh_formatos_insert ON public.rrhh_formatos_documentos FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = (SELECT auth.uid()) AND (u.empresa = rrhh_formatos_documentos.empresa OR lower(u.empresa) = 'obraxis')));

DROP POLICY IF EXISTS rrhh_formatos_update ON public.rrhh_formatos_documentos;
CREATE POLICY rrhh_formatos_update ON public.rrhh_formatos_documentos FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = (SELECT auth.uid()) AND (u.empresa = rrhh_formatos_documentos.empresa OR lower(u.empresa) = 'obraxis')))
WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = (SELECT auth.uid()) AND (u.empresa = rrhh_formatos_documentos.empresa OR lower(u.empresa) = 'obraxis')));

DROP POLICY IF EXISTS rrhh_formatos_delete ON public.rrhh_formatos_documentos;
CREATE POLICY rrhh_formatos_delete ON public.rrhh_formatos_documentos FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE u.auth_user_id = (SELECT auth.uid()) AND (u.empresa = rrhh_formatos_documentos.empresa OR lower(u.empresa) = 'obraxis')));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.rrhh_formatos_documentos TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.rrhh_formatos_documentos_id_seq TO authenticated;

;
