CREATE TABLE IF NOT EXISTS public.colaboraciones_obra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_contratista TEXT NOT NULL,
  rut_contratista TEXT NOT NULL,
  empresa_colaboradora TEXT NOT NULL,
  rut_colaboradora TEXT NOT NULL,
  obra_nombre TEXT NOT NULL,
  correo_contacto TEXT,
  estado TEXT NOT NULL DEFAULT 'Pendiente de aceptación' CHECK (estado IN ('Pendiente de aceptación','Activa','Rechazada','Archivada')),
  permisos JSONB NOT NULL DEFAULT '["acreditaciones","avances","calidad","prevencion","libro_obra"]'::jsonb,
  invitado_por TEXT,
  invitado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  respondido_por TEXT,
  respondido_en TIMESTAMPTZ,
  observacion TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (rut_contratista, rut_colaboradora, obra_nombre)
);
ALTER TABLE public.colaboraciones_obra ENABLE ROW LEVEL SECURITY;
CREATE POLICY "collaborations visible to member companies"
ON public.colaboraciones_obra FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE lower(coalesce(u.correo,'')) = lower(coalesce(auth.jwt()->>'email','')) AND u.empresa IN (empresa_contratista, empresa_colaboradora)));
CREATE POLICY "contractor creates collaborations"
ON public.colaboraciones_obra FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE lower(coalesce(u.correo,'')) = lower(coalesce(auth.jwt()->>'email','')) AND u.empresa = empresa_contratista));
CREATE POLICY "member companies update collaboration"
ON public.colaboraciones_obra FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM public.usuarios u WHERE lower(coalesce(u.correo,'')) = lower(coalesce(auth.jwt()->>'email','')) AND u.empresa IN (empresa_contratista, empresa_colaboradora)))
WITH CHECK (EXISTS (SELECT 1 FROM public.usuarios u WHERE lower(coalesce(u.correo,'')) = lower(coalesce(auth.jwt()->>'email','')) AND u.empresa IN (empresa_contratista, empresa_colaboradora)));
CREATE INDEX IF NOT EXISTS idx_colaboraciones_obra_rut ON public.colaboraciones_obra (rut_contratista, rut_colaboradora, obra_nombre);;
