create table public.subcontrato_contratos (
  id bigint generated by default as identity primary key,
  empresa text not null,
  obra_id bigint not null references public.obras(id) on delete restrict,
  obra_nombre text not null,
  subcontratista_id bigint not null references public.acreditaciones_subcontratos(id) on delete restrict,
  codigo text not null,
  nombre text not null,
  tipo_vinculo text not null default 'Ejecución de partidas'
    check (tipo_vinculo in ('Ejecución de partidas','Prestación de servicios','Arriendo','Suministro','Otro')),
  descripcion text,
  moneda text not null default 'CLP' check (moneda in ('CLP','UF','USD')),
  monto_contrato numeric(18,2) not null default 0 check (monto_contrato >= 0),
  fecha_inicio date,
  fecha_termino date,
  estado text not null default 'Borrador'
    check (estado in ('Borrador','Vigente','Suspendido','Terminado','Cerrado')),
  reporta_avances boolean not null default false,
  reporta_asistencia boolean not null default false,
  reporta_estados_pago boolean not null default false,
  responsable_operacion_nombre text,
  responsable_operacion_email text,
  observaciones text,
  creado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa, codigo)
);

create table public.subcontrato_contrato_items (
  id bigint generated by default as identity primary key,
  contrato_id bigint not null references public.subcontrato_contratos(id) on delete cascade,
  empresa text not null,
  tipo_item text not null default 'Partida'
    check (tipo_item in ('Partida','Servicio','Arriendo','Suministro','Otro')),
  partida_id bigint references public.partidas_obra(id) on delete restrict,
  codigo text,
  descripcion text not null,
  unidad text,
  cantidad numeric(18,4) not null default 0 check (cantidad >= 0),
  precio_unitario numeric(18,4) not null default 0 check (precio_unitario >= 0),
  reporta_avance boolean not null default false,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (tipo_item <> 'Partida' or partida_id is not null)
);

create index subcontrato_contratos_empresa_obra_idx
  on public.subcontrato_contratos (empresa, obra_id);
create index subcontrato_contratos_subcontratista_idx
  on public.subcontrato_contratos (subcontratista_id);
create index subcontrato_contrato_items_contrato_idx
  on public.subcontrato_contrato_items (contrato_id, orden);
create index subcontrato_contrato_items_partida_idx
  on public.subcontrato_contrato_items (partida_id)
  where partida_id is not null;
create index subcontrato_contrato_items_empresa_idx
  on public.subcontrato_contrato_items (empresa);

alter table public.subcontrato_contratos enable row level security;
alter table public.subcontrato_contrato_items enable row level security;

create policy subcontrato_contratos_empresa
on public.subcontrato_contratos
for all
to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = subcontrato_contratos.empresa or lower(u.empresa) = 'obraxis')
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = subcontrato_contratos.empresa or lower(u.empresa) = 'obraxis')
  )
);

create policy subcontrato_contrato_items_empresa
on public.subcontrato_contrato_items
for all
to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = subcontrato_contrato_items.empresa or lower(u.empresa) = 'obraxis')
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = subcontrato_contrato_items.empresa or lower(u.empresa) = 'obraxis')
  )
);

revoke all on public.subcontrato_contratos, public.subcontrato_contrato_items from anon;
grant select, insert, update, delete on public.subcontrato_contratos, public.subcontrato_contrato_items to authenticated;
grant usage, select on sequence public.subcontrato_contratos_id_seq to authenticated;
grant usage, select on sequence public.subcontrato_contrato_items_id_seq to authenticated;

comment on table public.subcontrato_contratos is
  'Ficha contractual independiente de la acreditación, aplicable a partidas, servicios, arriendos y suministros.';
comment on column public.subcontrato_contratos.reporta_avances is
  'Habilita reportes de avance únicamente cuando el alcance contractual lo requiere.';
