create table if not exists public.acreditaciones_internas (
  id bigint generated by default as identity primary key,
  empresa text not null,
  obra_id bigint references public.obras(id) on delete restrict,
  obra_nombre text not null,
  destinatario_email text not null,
  asunto text not null,
  observaciones text,
  trabajadores_json jsonb not null default '[]'::jsonb,
  estado text not null default 'Enviado',
  creado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists acreditaciones_internas_empresa_fecha_idx
  on public.acreditaciones_internas (empresa, created_at desc);

create index if not exists acreditaciones_internas_obra_idx
  on public.acreditaciones_internas (obra_id, created_at desc)
  where obra_id is not null;

alter table public.acreditaciones_internas enable row level security;

drop policy if exists acreditaciones_internas_empresa on public.acreditaciones_internas;
create policy acreditaciones_internas_empresa
on public.acreditaciones_internas
for all
to authenticated
using (
  exists (
    select 1
    from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = acreditaciones_internas.empresa or lower(u.empresa) = 'obraxis')
  )
)
with check (
  exists (
    select 1
    from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = acreditaciones_internas.empresa or lower(u.empresa) = 'obraxis')
  )
);

revoke all on public.acreditaciones_internas from anon;
grant select, insert, update, delete on public.acreditaciones_internas to authenticated;
grant usage, select on sequence public.acreditaciones_internas_id_seq to authenticated;

comment on table public.acreditaciones_internas is
  'Historial multiempresa de solicitudes de acreditacion de personal propio enviadas desde Obraxis.';
