create table if not exists public.acreditaciones_config_docs (
  id bigint generated by default as identity primary key,
  empresa text not null unique,
  company_docs jsonb not null default '[]'::jsonb,
  worker_docs jsonb not null default '[]'::jsonb,
  equipo_docs jsonb not null default '[]'::jsonb,
  supplier_docs jsonb not null default '[]'::jsonb,
  supplier_worker_docs jsonb not null default '[]'::jsonb,
  supplier_equipo_docs jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.acreditaciones_subcontratos (
  id bigint generated by default as identity primary key,
  empresa text not null,
  empresa_nombre text not null,
  rut_empresa text not null,
  obra_asociada text,
  correo_contacto text,
  token_acceso text not null unique,
  credencial_pass text not null,
  estado text not null default 'Pendiente',
  estado_cumplimiento numeric not null default 0 check (estado_cumplimiento between 0 and 100),
  "companyDocs" jsonb not null default '{}'::jsonb,
  "personalList" jsonb not null default '[]'::jsonb,
  "equiposList" jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.acreditaciones_proveedores (
  id bigint generated by default as identity primary key,
  empresa text not null,
  empresa_nombre text not null,
  rut_empresa text not null,
  obra_asociada text,
  correo_contacto text,
  token_acceso text not null unique,
  credencial_pass text not null,
  estado text not null default 'Pendiente',
  estado_cumplimiento numeric not null default 0 check (estado_cumplimiento between 0 and 100),
  "companyDocs" jsonb not null default '{}'::jsonb,
  "personalList" jsonb not null default '[]'::jsonb,
  "equiposList" jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists acreditaciones_subcontratos_empresa_obra_idx on public.acreditaciones_subcontratos(empresa, obra_asociada);
create index if not exists acreditaciones_proveedores_empresa_obra_idx on public.acreditaciones_proveedores(empresa, obra_asociada);

alter table public.acreditaciones_config_docs enable row level security;
alter table public.acreditaciones_subcontratos enable row level security;
alter table public.acreditaciones_proveedores enable row level security;

create policy acreditaciones_config_docs_empresa on public.acreditaciones_config_docs
for all to authenticated
using (exists (select 1 from public.usuarios u where u.auth_user_id = (select auth.uid()) and u.empresa = acreditaciones_config_docs.empresa))
with check (exists (select 1 from public.usuarios u where u.auth_user_id = (select auth.uid()) and u.empresa = acreditaciones_config_docs.empresa));

create policy acreditaciones_subcontratos_empresa on public.acreditaciones_subcontratos
for all to authenticated
using (exists (select 1 from public.usuarios u where u.auth_user_id = (select auth.uid()) and u.empresa = acreditaciones_subcontratos.empresa))
with check (exists (select 1 from public.usuarios u where u.auth_user_id = (select auth.uid()) and u.empresa = acreditaciones_subcontratos.empresa));

create policy acreditaciones_proveedores_empresa on public.acreditaciones_proveedores
for all to authenticated
using (exists (select 1 from public.usuarios u where u.auth_user_id = (select auth.uid()) and u.empresa = acreditaciones_proveedores.empresa))
with check (exists (select 1 from public.usuarios u where u.auth_user_id = (select auth.uid()) and u.empresa = acreditaciones_proveedores.empresa));

revoke all on public.acreditaciones_config_docs, public.acreditaciones_subcontratos, public.acreditaciones_proveedores from anon;
grant select, insert, update, delete on public.acreditaciones_config_docs, public.acreditaciones_subcontratos, public.acreditaciones_proveedores to authenticated;
grant usage, select on sequence public.acreditaciones_config_docs_id_seq to authenticated;
grant usage, select on sequence public.acreditaciones_subcontratos_id_seq to authenticated;
grant usage, select on sequence public.acreditaciones_proveedores_id_seq to authenticated;
