create table if not exists public.prevencion_matrices_riesgo (
  id uuid primary key default gen_random_uuid(),
  empresa text not null,
  obra_id integer references public.obras(id) on delete restrict,
  nombre text not null,
  codigo text not null,
  version text not null default '1',
  fecha_revision date not null default current_date,
  metodologia text not null default 'ISP Chile · Guía IPER v3 (2024)',
  estado text not null default 'Borrador' check (estado in ('Borrador', 'Vigente', 'En revisión', 'Obsoleta')),
  columnas jsonb not null default '[]'::jsonb check (jsonb_typeof(columnas) = 'array'),
  archivo_path text,
  archivo_nombre text,
  archivo_tipo text,
  creado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, empresa),
  unique (empresa, codigo, version)
);

create table if not exists public.prevencion_matriz_riesgo_filas (
  id bigint generated by default as identity primary key,
  matriz_id uuid not null,
  empresa text not null,
  orden integer not null check (orden > 0),
  datos jsonb not null default '{}'::jsonb check (jsonb_typeof(datos) = 'object'),
  nivel_riesgo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint prevencion_matriz_riesgo_filas_matriz_empresa_fk
    foreign key (matriz_id, empresa)
    references public.prevencion_matrices_riesgo(id, empresa)
    on delete cascade,
  unique (matriz_id, orden)
);

create index if not exists prevencion_matrices_riesgo_empresa_obra_idx
  on public.prevencion_matrices_riesgo (empresa, obra_id, estado);
create index if not exists prevencion_matriz_riesgo_filas_matriz_nivel_idx
  on public.prevencion_matriz_riesgo_filas (matriz_id, nivel_riesgo);

alter table public.prevencion_matrices_riesgo enable row level security;
alter table public.prevencion_matriz_riesgo_filas enable row level security;

drop policy if exists prevencion_matrices_riesgo_select_empresa on public.prevencion_matrices_riesgo;
create policy prevencion_matrices_riesgo_select_empresa on public.prevencion_matrices_riesgo
for select to authenticated
using ((select private.obraxis_actor_can_access_company(empresa)));

drop policy if exists prevencion_matrices_riesgo_insert_empresa on public.prevencion_matrices_riesgo;
create policy prevencion_matrices_riesgo_insert_empresa on public.prevencion_matrices_riesgo
for insert to authenticated
with check ((select private.obraxis_actor_can_access_company(empresa)));

drop policy if exists prevencion_matrices_riesgo_update_empresa on public.prevencion_matrices_riesgo;
create policy prevencion_matrices_riesgo_update_empresa on public.prevencion_matrices_riesgo
for update to authenticated
using ((select private.obraxis_actor_can_access_company(empresa)))
with check ((select private.obraxis_actor_can_access_company(empresa)));

drop policy if exists prevencion_matrices_riesgo_delete_empresa on public.prevencion_matrices_riesgo;
create policy prevencion_matrices_riesgo_delete_empresa on public.prevencion_matrices_riesgo
for delete to authenticated
using ((select private.obraxis_actor_can_access_company(empresa)));

drop policy if exists prevencion_matriz_riesgo_filas_select_empresa on public.prevencion_matriz_riesgo_filas;
create policy prevencion_matriz_riesgo_filas_select_empresa on public.prevencion_matriz_riesgo_filas
for select to authenticated
using ((select private.obraxis_actor_can_access_company(empresa)));

drop policy if exists prevencion_matriz_riesgo_filas_insert_empresa on public.prevencion_matriz_riesgo_filas;
create policy prevencion_matriz_riesgo_filas_insert_empresa on public.prevencion_matriz_riesgo_filas
for insert to authenticated
with check ((select private.obraxis_actor_can_access_company(empresa)));

drop policy if exists prevencion_matriz_riesgo_filas_update_empresa on public.prevencion_matriz_riesgo_filas;
create policy prevencion_matriz_riesgo_filas_update_empresa on public.prevencion_matriz_riesgo_filas
for update to authenticated
using ((select private.obraxis_actor_can_access_company(empresa)))
with check ((select private.obraxis_actor_can_access_company(empresa)));

drop policy if exists prevencion_matriz_riesgo_filas_delete_empresa on public.prevencion_matriz_riesgo_filas;
create policy prevencion_matriz_riesgo_filas_delete_empresa on public.prevencion_matriz_riesgo_filas
for delete to authenticated
using ((select private.obraxis_actor_can_access_company(empresa)));

grant select, insert, update, delete on public.prevencion_matrices_riesgo to authenticated;
grant select, insert, update, delete on public.prevencion_matriz_riesgo_filas to authenticated;
grant usage, select on sequence public.prevencion_matriz_riesgo_filas_id_seq to authenticated;
grant all on public.prevencion_matrices_riesgo to service_role;
grant all on public.prevencion_matriz_riesgo_filas to service_role;
grant all on sequence public.prevencion_matriz_riesgo_filas_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'matrices-riesgo',
  'matrices-riesgo',
  false,
  20971520,
  array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-excel',
    'text/csv',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists matrices_riesgo_storage_select on storage.objects;
create policy matrices_riesgo_storage_select on storage.objects
for select to authenticated
using (
  bucket_id = 'matrices-riesgo'
  and exists (
    select 1 from public.prevencion_matrices_riesgo matriz
    where matriz.archivo_path = name
      and (select private.obraxis_actor_can_access_company(matriz.empresa))
  )
);

drop policy if exists matrices_riesgo_storage_insert on storage.objects;
create policy matrices_riesgo_storage_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'matrices-riesgo'
  and exists (
    select 1 from public.prevencion_matrices_riesgo matriz
    where matriz.id::text = (storage.foldername(name))[1]
      and (select private.obraxis_actor_can_access_company(matriz.empresa))
  )
);

drop policy if exists matrices_riesgo_storage_delete on storage.objects;
create policy matrices_riesgo_storage_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'matrices-riesgo'
  and exists (
    select 1 from public.prevencion_matrices_riesgo matriz
    where matriz.archivo_path = name
      and (select private.obraxis_actor_can_access_company(matriz.empresa))
  )
);
