create extension if not exists pgcrypto;
create table if not exists public.informes_programaciones (
id uuid primary key default gen_random_uuid(), empresa text not null, nombre text not null,
plantilla_codigo text not null check (plantilla_codigo in ('semanal_obra','mensual_obra','prevencion_general','cartera_obras','costos_corporativo','calidad_general')),
alcance_tipo text not null default 'Todas' check (alcance_tipo in ('Todas','Seleccionadas')), obras jsonb not null default '[]'::jsonb,
frecuencia text not null check (frecuencia in ('Semanal','Mensual')), dia_semana integer check (dia_semana between 1 and 7),
dia_mes integer check (dia_mes between 1 and 28), hora_envio time not null default '08:00', zona_horaria text not null default 'America/Santiago',
destinatarios_roles jsonb not null default '[]'::jsonb, destinatarios_usuarios jsonb not null default '[]'::jsonb,
correos_adicionales jsonb not null default '[]'::jsonb, incluir_pdf boolean not null default true, incluir_correo boolean not null default true,
secciones jsonb not null default '["resumen","avance","plazo","costos","prevencion","calidad","prioridades"]'::jsonb,
activa boolean not null default true, proxima_ejecucion timestamptz, ultima_ejecucion timestamptz, creado_por text,
created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.informes_ejecuciones (
id bigint generated by default as identity primary key, programacion_id uuid references public.informes_programaciones(id) on delete set null,
empresa text not null, plantilla_codigo text not null, nombre text not null, periodo_desde date, periodo_hasta date,
obras jsonb not null default '[]'::jsonb, destinatarios jsonb not null default '[]'::jsonb, indicadores jsonb not null default '{}'::jsonb,
contenido_html text, estado text not null default 'Pendiente' check (estado in ('Pendiente','Procesando','Enviado','Error','Vista previa')),
error_detalle text, ejecutado_por text, enviada_at timestamptz, created_at timestamptz not null default now());
create index if not exists informes_programaciones_empresa_idx on public.informes_programaciones (empresa, activa, proxima_ejecucion);
create index if not exists informes_ejecuciones_empresa_idx on public.informes_ejecuciones (empresa, created_at desc);
alter table public.informes_programaciones enable row level security; alter table public.informes_ejecuciones enable row level security;
grant select, insert, update, delete on public.informes_programaciones to authenticated;
grant select, insert, update on public.informes_ejecuciones to authenticated;
grant usage, select on sequence public.informes_ejecuciones_id_seq to authenticated;
create policy informes_programaciones_empresa on public.informes_programaciones for all to authenticated using (private.obraxis_actor_can_access_company(empresa)) with check (private.obraxis_actor_can_access_company(empresa));
create policy informes_ejecuciones_empresa on public.informes_ejecuciones for all to authenticated using (private.obraxis_actor_can_access_company(empresa)) with check (private.obraxis_actor_can_access_company(empresa));;
