create table if not exists public.subcontrato_operacion_perfiles (
  id bigint generated by default as identity primary key,
  empresa text not null,
  obra_id bigint not null references public.obras(id) on delete restrict,
  subcontratista_id bigint not null references public.acreditaciones_subcontratos(id) on delete restrict,
  contacto_nombre text not null,
  contacto_email text,
  token_acceso text not null unique,
  clave_hash text not null,
  activo boolean not null default true,
  creado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa, obra_id, subcontratista_id)
);

alter table public.subcontrato_avances
  add column if not exists contrato_operativo_id bigint references public.subcontrato_contratos(id) on delete restrict,
  add column if not exists contrato_item_id bigint references public.subcontrato_contrato_items(id) on delete restrict;
alter table public.subcontrato_asistencia
  add column if not exists contrato_operativo_id bigint references public.subcontrato_contratos(id) on delete restrict;
alter table public.subcontrato_estados_pago
  add column if not exists contrato_operativo_id bigint references public.subcontrato_contratos(id) on delete restrict;

create index if not exists subcontrato_operacion_perfiles_empresa_obra_idx
  on public.subcontrato_operacion_perfiles (empresa, obra_id);
create index if not exists subcontrato_operacion_perfiles_subcontratista_idx
  on public.subcontrato_operacion_perfiles (subcontratista_id);
create index if not exists subcontrato_avances_contrato_operativo_idx
  on public.subcontrato_avances (contrato_operativo_id) where contrato_operativo_id is not null;
create index if not exists subcontrato_avances_contrato_item_idx
  on public.subcontrato_avances (contrato_item_id) where contrato_item_id is not null;
create index if not exists subcontrato_asistencia_contrato_operativo_idx
  on public.subcontrato_asistencia (contrato_operativo_id) where contrato_operativo_id is not null;
create index if not exists subcontrato_estados_pago_contrato_operativo_idx
  on public.subcontrato_estados_pago (contrato_operativo_id) where contrato_operativo_id is not null;

alter table public.subcontrato_operacion_perfiles enable row level security;
create policy subcontrato_operacion_perfiles_empresa
on public.subcontrato_operacion_perfiles
for all to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = subcontrato_operacion_perfiles.empresa or lower(u.empresa) = 'obraxis')
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and (u.empresa = subcontrato_operacion_perfiles.empresa or lower(u.empresa) = 'obraxis')
  )
);

revoke all on public.subcontrato_operacion_perfiles from anon;
grant select, insert, update, delete on public.subcontrato_operacion_perfiles to authenticated;
grant usage, select on sequence public.subcontrato_operacion_perfiles_id_seq to authenticated;

comment on table public.subcontrato_operacion_perfiles is
  'Contacto y credencial operacional única del subcontratista por obra, independiente de acreditación y de cada contrato.';
