CREATE TABLE IF NOT EXISTS public.rrhh_centros_trabajo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa TEXT NOT NULL,
  numero INTEGER NOT NULL CHECK (numero > 0),
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'Otro' CHECK (tipo IN ('Oficina','Bodega','Obra','Taller','Otro')),
  obra_id INTEGER REFERENCES public.obras(id) ON DELETE SET NULL,
  direccion TEXT,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (empresa, numero),
  UNIQUE (obra_id)
);

ALTER TABLE public.maestro_personal ADD COLUMN IF NOT EXISTS centro_trabajo_id BIGINT REFERENCES public.rrhh_centros_trabajo(id) ON DELETE SET NULL;
ALTER TABLE public.obras ADD COLUMN IF NOT EXISTS centro_trabajo_id BIGINT REFERENCES public.rrhh_centros_trabajo(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS rrhh_centros_trabajo_empresa_idx ON public.rrhh_centros_trabajo(empresa, activo, numero);
CREATE INDEX IF NOT EXISTS maestro_personal_centro_trabajo_idx ON public.maestro_personal(centro_trabajo_id);
CREATE INDEX IF NOT EXISTS obras_centro_trabajo_idx ON public.obras(centro_trabajo_id);

ALTER TABLE public.rrhh_centros_trabajo ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rrhh_centros_trabajo_empresa ON public.rrhh_centros_trabajo;
CREATE POLICY rrhh_centros_trabajo_empresa ON public.rrhh_centros_trabajo
FOR ALL TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.usuarios u
    WHERE u.auth_user_id = (SELECT auth.uid())
      AND (u.empresa = rrhh_centros_trabajo.empresa OR lower(u.empresa) = 'obraxis')
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.usuarios u
    WHERE u.auth_user_id = (SELECT auth.uid())
      AND (u.empresa = rrhh_centros_trabajo.empresa OR lower(u.empresa) = 'obraxis')
  )
);

REVOKE ALL ON public.rrhh_centros_trabajo FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rrhh_centros_trabajo TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.rrhh_centros_trabajo_id_seq TO authenticated;

INSERT INTO public.rrhh_centros_trabajo (empresa, numero, nombre, tipo)
SELECT e.empresa, defaults.numero, defaults.nombre, defaults.tipo
FROM (
  SELECT DISTINCT empresa FROM public.obras WHERE empresa IS NOT NULL AND btrim(empresa) <> ''
  UNION
  SELECT DISTINCT empresa FROM public.maestro_personal WHERE empresa IS NOT NULL AND btrim(empresa) <> ''
  UNION
  SELECT DISTINCT empresa FROM public.usuarios WHERE empresa IS NOT NULL AND btrim(empresa) <> ''
) e
CROSS JOIN (VALUES (1, 'Oficina Central', 'Oficina'), (2, 'Bodega', 'Bodega')) defaults(numero, nombre, tipo)
ON CONFLICT (empresa, numero) DO NOTHING;

INSERT INTO public.rrhh_centros_trabajo (empresa, numero, nombre, tipo, obra_id, direccion)
SELECT COALESCE(o.empresa, 'Obraxis'), 1000 + o.id, o.nombre, 'Obra', o.id, o.ubicacion
FROM public.obras o
ON CONFLICT (obra_id) DO UPDATE SET nombre = EXCLUDED.nombre, direccion = EXCLUDED.direccion, updated_at = now();

UPDATE public.obras o
SET centro_trabajo_id = c.id
FROM public.rrhh_centros_trabajo c
WHERE c.obra_id = o.id AND o.centro_trabajo_id IS DISTINCT FROM c.id;

UPDATE public.maestro_personal p
SET centro_trabajo_id = COALESCE(
  (SELECT c.id FROM public.rrhh_centros_trabajo c JOIN public.obras o ON o.id = c.obra_id WHERE o.nombre = p.obra_nombre AND c.empresa = p.empresa LIMIT 1),
  (SELECT c.id FROM public.rrhh_centros_trabajo c WHERE c.empresa = p.empresa AND c.numero = CASE WHEN lower(COALESCE(p.centro_trabajo,'')) LIKE '%bodega%' THEN 2 ELSE 1 END LIMIT 1)
)
WHERE p.centro_trabajo_id IS NULL;

CREATE OR REPLACE FUNCTION public.rrhh_crear_centro_para_obra()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.rrhh_centros_trabajo (empresa, numero, nombre, tipo, obra_id, direccion)
  VALUES (COALESCE(NEW.empresa, 'Obraxis'), 1000 + NEW.id, NEW.nombre, 'Obra', NEW.id, NEW.ubicacion)
  ON CONFLICT (obra_id) DO UPDATE
    SET nombre = EXCLUDED.nombre, direccion = EXCLUDED.direccion, empresa = EXCLUDED.empresa, updated_at = now()
  RETURNING id INTO NEW.centro_trabajo_id;

  UPDATE public.obras SET centro_trabajo_id = NEW.centro_trabajo_id WHERE id = NEW.id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS rrhh_crear_centro_obra_ai ON public.obras;
CREATE TRIGGER rrhh_crear_centro_obra_ai
AFTER INSERT ON public.obras
FOR EACH ROW EXECUTE FUNCTION public.rrhh_crear_centro_para_obra();

NOTIFY pgrst, 'reload schema';;
